"use strict";

const SAVE_KEY = "maapan-stories-v2";
const OLD_SAVE_KEY = "maapan-stories-v1";
const DAY_SECONDS = 24;
const MORNING_SECONDS = 4;
const RESULT_SECONDS = 1.2;
const COLORS = ["#d96b5f", "#e3bb58", "#6e99a8"];
const NAMES = ["赤いマーパン", "黄色いマーパン", "青いマーパン"];
const SEEDS = [
  { id:"oneFruit", icon:"●", name:"木の実をひとつ", description:"木の実はひとつだけ。マーパンたちはどうするでしょう。", unlock:1 },
  { id:"manyFruit", icon:"●●", name:"木の実をたくさん", description:"今日は全員に届くほどの木の実があります。", unlock:2 },
  { id:"rain", icon:"☂", name:"大雨", description:"今日は大雨になります。雨宿りできる場所はひとつです。", unlock:1 },
  { id:"egg", icon:"◯", name:"謎の卵", description:"見たことのない卵を、草地へ置きます。", unlock:3 },
  { id:"sound", icon:"♪", name:"不思議な音", description:"草地の端から、不思議な音が聞こえてきます。", unlock:4 },
  { id:"path", icon:"↗", name:"新しい場所", description:"今まで閉じていた小道を開きます。", unlock:6 },
  { id:"none", icon:"○", name:"何もしない", description:"今日は何も変えず、これまでの記憶に任せます。", unlock:1 }
];
let sim, lastRealTime = 0, selectedSeed = null;

function hash01(text) { let h=2166136261; for(const c of String(text)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);} return ((h>>>0)%10000)/9999; }
function traitsFromDNA(id,dna){const r=o=>hash01(id+dna.slice(o,o+18));return{curiosity:r(0),sociability:r(19),caution:r(38),appetite:r(57),activity:r(76),attachment:r(95),harmony:r(109),moodSwing:r(120)};}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}

class MemoryBank {
  constructor(items=[]){this.items=items;}
  remember(m){this.items.push(m);if(this.items.length>42)this.items.splice(0,this.items.length-42);}
  matching(kinds,target=null){return this.items.filter(m=>(Array.isArray(kinds)?kinds.includes(m.kind):m.kind===kinds)&&(!target||m.target===target));}
  influence(kinds,target=null){return this.matching(kinds,target).reduce((n,m)=>n+m.strength*Math.max(.3,1-(sim.day-m.day)*.1),0);}
  recent(n=4){return this.items.slice(-n);}
}

class Agent {
  constructor(data,index){
    this.id=data.id;this.dna=data.dna;this.name=data.name;this.color=data.color;this.x=data.x;this.y=data.y;this.vx=0;this.vy=0;
    this.traits=data.traits||traitsFromDNA(this.id,this.dna);this.needs=data.needs||{hunger:35+index*8,fatigue:8,company:25+index*6};
    this.emotion=data.emotion||"おだやか";this.action="idle";this.reason="朝の気配を確かめている";this.memoryReason="";this.target=null;this.decisionAt=0;this.arrived=false;this.mark="";this.markUntil=0;this.lookAt=null;
    this.memory=new MemoryBank(data.memories||[]);this.marpan=new Marpan25D({id:this.id,dna:this.dna,bodyColor:this.color,eyeScale:.92+this.traits.curiosity*.2});this.marpan.enableAutoBlink(2100,4400);
  }
  serialize(){return{id:this.id,dna:this.dna,name:this.name,color:this.color,x:this.x,y:this.y,traits:this.traits,needs:this.needs,emotion:this.emotion,memories:this.memory.items};}
}

class Simulation {
  constructor(state){
    this.day=state?.day||1;this.minute=360;this.speed=1;this.phase="choosing";this.elapsed=0;this.morningElapsed=0;this.resultElapsed=0;this.events=state?.events||[];this.history=state?.history||[];this.relations=state?.relations||{};this.pending=state?.pending||[];this.worldFlags=state?.worldFlags||{};this.objects=[];this.weather="晴れ";this.activeSeed=null;this.dayEventCount=0;
    const starts=[[.25,.60],[.52,.65],[.72,.57]];this.agents=[];
    for(let i=0;i<3;i++){const old=state?.agents?.[i];const g=old||MarpanDNA.create({id:`story-marpan-${i+1}`});this.agents.push(new Agent(old||{...g,name:NAMES[i],color:COLORS[i],x:starts[i][0],y:starts[i][1]},i));}
    for(let i=0;i<3;i++)for(let j=i+1;j<3;j++){const k=this.key(i,j);if(!this.relations[k])this.relations[k]={warmth:16,trust:10,caution:8};}
    this.prepareMorning();
  }
  key(a,b){return[a,b].sort().join("-");} relation(a,b){return this.relations[this.key(a,b)];}
  prepareMorning(){this.phase="choosing";this.elapsed=0;this.morningElapsed=0;this.resultElapsed=0;this.minute=360;this.activeSeed=null;this.objects=[];this.weather="晴れ";this.dayEventCount=0;selectedSeed=null;for(const a of this.agents){a.target=null;a.action="idle";a.arrived=false;a.mark="";a.needs.hunger=clamp(a.needs.hunger+12,0,88);a.needs.fatigue=8;a.x=clamp(a.x,.13,.87);a.y=clamp(a.y,.53,.72);}this.processPending();renderSeedPicker();updatePanels();this.save();}
  processPending(){for(const p of this.pending.filter(p=>p.due<=this.day&&!p.done)){p.done=true;if(p.type==="eggCrack"){this.worldFlags.eggStage=(this.worldFlags.eggStage||0)+1;this.log(null,this.worldFlags.eggStage>1?"卵の殻が、内側から小さく動いた":"謎の卵に、小さなひびが入った","egg-crack",null,4,"数日前に置かれた卵が変化した");}}}
  startDay(seedId){if(this.phase!=="choosing")return;this.activeSeed=SEEDS.find(s=>s.id===seedId);if(!this.activeSeed)return;this.phase="running";this.elapsed=0;this.minute=420;this.installSeed(seedId);for(const a of this.agents){a.decisionAt=.8+hash01(a.id+this.day+seedId)*1.8;a.mark="?";a.markUntil=1.6;a.lookAt=this.focusPoint();}document.getElementById("seedPicker").classList.add("hidden");document.getElementById("dayProgress").classList.add("visible");this.log(null,seedOpening(seedId),"seed",null,2,"");}
  installSeed(id){if(id==="oneFruit")this.objects.push({id:`fruit-${this.day}`,type:"fruit",x:.5,y:.63,amount:1});if(id==="manyFruit")this.objects.push({id:`fruit-${this.day}`,type:"fruit",x:.5,y:.63,amount:9});if(id==="rain"){this.weather="大雨";this.objects.push({id:"shelter",type:"shelter",x:.18,y:.49});}if(id==="egg"){this.worldFlags.egg=true;this.worldFlags.eggStage=this.worldFlags.eggStage||0;this.objects.push({id:"egg",type:"egg",x:.53,y:.60});if(!this.pending.some(p=>p.type==="eggCrack"&&!p.done))this.pending.push({type:"eggCrack",due:this.day+2+Math.floor(Math.random()*2),done:false});}if(id==="sound")this.objects.push({id:"sound",type:"sound",x:.9,y:.51});if(id==="path"){this.worldFlags.path=true;this.objects.push({id:"path",type:"path",x:.88,y:.54});}if(this.worldFlags.egg&&id!=="egg")this.objects.push({id:"egg",type:"egg",x:.53,y:.60});}
  focusPoint(){const o=this.objects.find(o=>["fruit","egg","sound","path","shelter"].includes(o.type));return o?{x:o.x,y:o.y}:{x:.5,y:.58};}
  log(actor,text,kind="observe",target=null,strength=1,cause=""){
    const e={id:`${this.day}-${this.elapsed.toFixed(2)}-${this.events.length}`,day:this.day,minute:this.minute,actor:actor?.id||null,actorName:actor?.name||null,target:target?.id||null,targetName:target?.name||null,text,kind,strength,cause};this.events.push(e);if(this.events.length>240)this.events.splice(0,this.events.length-240);if(actor)actor.memory.remember({day:this.day,minute:this.minute,kind,target:target?.id||null,text,strength});if(strength>=2)this.dayEventCount++;updatePanels();return e;
  }
  update(dt){if(!this.speed)return;const step=dt*this.speed;if(this.phase==="choosing"){this.morningElapsed+=step;updateMorningCountdown();if(this.morningElapsed>=MORNING_SECONDS)this.startDay(selectedSeed||"none");return;}if(this.phase==="result"){this.resultElapsed+=step;if(this.resultElapsed>=RESULT_SECONDS)this.nextDay();return;}if(this.phase!=="running")return;this.elapsed+=step;this.minute=420+(this.elapsed/DAY_SECONDS)*690;for(const a of this.agents)this.updateAgent(a,step);this.avoidOverlap();if(this.elapsed>=DAY_SECONDS)this.finishDay();}
  updateAgent(a,dt){a.needs.hunger=clamp(a.needs.hunger+dt*.55,0,100);a.needs.fatigue=clamp(a.needs.fatigue+dt*.35,0,100);if(!a.target&&this.elapsed>=a.decisionAt)this.decide(a);if(a.target){const dx=a.target.x-a.x,dy=a.target.y-a.y,d=Math.hypot(dx,dy);const pace=(.045+a.traits.activity*.018)*dt;if(d>.018){a.vx=dx/d*pace;a.vy=dy/d*pace;a.x+=a.vx;a.y+=a.vy;a.lookAt=a.target;}else this.arrive(a);}else{a.vx*=.7;a.vy*=.7;}a.x=clamp(a.x,.09,.91);a.y=clamp(a.y,.44,.76);}
  decide(a){
    const focus=this.focusPoint(),choices=[],others=this.agents.filter(o=>o!==a);const add=(action,score,target,reason,memoryReason="")=>choices.push({action,score:score+Math.random()*18,target,reason,memoryReason});const pressure=22+(this.dayEventCount<2?18:5);
    if(this.activeSeed.id==="oneFruit"||this.activeSeed.id==="manyFruit"){const fruit=this.objects.find(o=>o.type==="fruit"&&o.amount>0);if(fruit){const received=a.memory.influence("received-fruit");add("fruit",pressure+a.needs.hunger*.8+a.traits.appetite*32,fruit,"木の実に気づき、空腹と相談している",received?"以前、木の実を譲ってもらった記憶が残っている":"");}}
    if(this.activeSeed.id==="rain")add("shelter",pressure+55+a.traits.caution*30,{type:"shelter",x:.18+(this.agents.indexOf(a)-1)*.055,y:.52},"強い雨を避けられる場所を探した",a.memory.influence("sheltered")?"以前の雨宿りの場所を覚えている":"");
    if(this.objects.some(o=>o.type==="egg")){const egg=this.objects.find(o=>o.type==="egg");add("egg",pressure+a.traits.curiosity*55-a.traits.caution*28,offsetTarget(egg,this.agents.indexOf(a),.065),"見たことのない卵が気になった");add("avoidEgg",18+a.traits.caution*55-a.traits.curiosity*25,{type:"avoid",x:a.x<egg.x?.16:.84,y:.56},"卵が何をするか分からず、距離を取った");}
    if(this.activeSeed.id==="sound"){add("sound",pressure+a.traits.curiosity*64-a.traits.caution*38,offsetTarget(focus,this.agents.indexOf(a),.055),"不思議な音の正体を確かめたい");add("fleeSound",22+a.traits.caution*62,{type:"flee",x:.17,y:.68},"知らない音を警戒した");}
    if(this.activeSeed.id==="path")add("explore",pressure+a.traits.curiosity*58+a.traits.activity*18,offsetTarget(focus,this.agents.indexOf(a),.045),"開いたばかりの小道の先が気になった");
    for(const o of others){const r=this.relation(this.agents.indexOf(a),this.agents.indexOf(o)),shared=a.memory.influence(["sheltered","received-fruit","together"],o.id);add("follow",18+a.traits.sociability*27+r.trust*.38+shared*4,offsetTarget(o,this.agents.indexOf(a),.07),`${o.name}の動きを見ていた`,shared?`${memoryLabel(a,o)}記憶が、近づく判断に影響したようです`:"");}
    add("wait",18+a.traits.caution*25,{type:"wait",x:a.x,y:a.y},"すぐには動かず、ほかの二匹を見ている");
    const best=choices.sort((x,y)=>y.score-x.score)[0];a.action=best.action;a.target=best.target;a.reason=best.reason;a.memoryReason=best.memoryReason;a.arrived=false;a.mark=best.action.startsWith("avoid")||best.action.startsWith("flee")?"!":"?";a.markUntil=this.elapsed+1.2;a.emotion=emotionFor(best.action);a.marpan.setExpression(expressionFor(best.action));
  }
  arrive(a){if(a.arrived)return;a.arrived=true;const action=a.action,target=a.target;a.target=null;a.mark="!";a.markUntil=this.elapsed+.8;a.marpan.bounce(.7);
    if(action==="fruit")this.resolveFruit(a,target);
    else if(action==="shelter")this.resolveShelter(a);
    else if(action==="egg")this.resolveEgg(a);
    else if(action==="avoidEgg"){this.log(a,`${a.name}は卵から離れ、遠くから見ていた`,"avoided-egg",null,2,a.reason);a.emotion="警戒している";}
    else if(action==="sound"){this.log(a,`${a.name}は音のする方へ、ゆっくり進んだ`,"followed-sound",null,2,a.reason);}
    else if(action==="fleeSound"){this.log(a,`${a.name}は音と反対の方へ後ずさった`,"fled-sound",null,2,a.reason);}
    else if(action==="explore"){this.log(a,`${a.name}が、最初に新しい小道へ入った`,"explored",null,3,a.reason);this.inspireFollowers(a);}
    else if(action==="follow"){const near=this.nearestAgent(a);if(near){const r=this.relation(this.agents.indexOf(a),this.agents.indexOf(near));r.warmth+=2;this.log(a,`${near.name}のあとをついていった`,"followed",near,2,a.memoryReason||a.reason);}}
    else if(action==="wait")this.log(a,`${a.name}は動かず、ほかの二匹の様子を見ていた`,"waited",null,2,a.reason);
    a.decisionAt=this.elapsed+3.3+Math.random()*2.2;
  }
  resolveFruit(a,fruit){if(!fruit||fruit.amount<=0){this.log(a,`${a.name}が着いたとき、木の実はもうなかった`,"missed-fruit",null,2,"ほかのマーパンより少し遅く気づいた");a.emotion="戸惑っている";return;}fruit.amount--;const watcher=this.agents.filter(o=>o!==a).sort((x,y)=>Math.hypot(x.x-a.x,x.y-a.y)-Math.hypot(y.x-a.x,y.y-a.y))[0];const r=watcher?this.relation(this.agents.indexOf(a),this.agents.indexOf(watcher)):null;const debt=watcher?a.memory.influence("received-fruit",watcher.id):0;const sharedPast=watcher?a.memory.influence("sheltered",watcher.id):0;const shareScore=a.traits.harmony*42+(r?.trust||0)*.7+debt*8+sharedPast*5+Math.random()*18;
    if(watcher&&shareScore>38&&(fruit.amount>0||this.activeSeed.id==="oneFruit")){if(this.activeSeed.id==="oneFruit")a.needs.hunger=Math.max(0,a.needs.hunger-15);else fruit.amount--;watcher.needs.hunger=Math.max(0,watcher.needs.hunger-32);const rel=this.relation(this.agents.indexOf(a),this.agents.indexOf(watcher));rel.warmth+=8;rel.trust+=6;const cause=debt?`以前、${watcher.name}に木の実を譲ってもらった記憶が影響したようです`:sharedPast?`以前、一緒に雨宿りした記憶が影響したようです`:a.traits.harmony>.62?"分け合う性質が強く表れたようです":"相手が見ていることに気づいた";this.log(a,`${a.name}は木の実を取り、${watcher.name}の前へ置いた`,"gave-fruit",watcher,4,cause);watcher.memory.remember({day:this.day,minute:this.minute,kind:"received-fruit",target:a.id,text:`${a.name}が木の実を譲ってくれた`,strength:4});a.memory.remember({day:this.day,minute:this.minute,kind:"gave-fruit",target:watcher.id,text:`${watcher.name}へ木の実を譲った`,strength:3});}
    else{a.needs.hunger=Math.max(0,a.needs.hunger-48);this.log(a,`${a.name}が木の実を食べた`,"ate-fruit",null,3,a.reason);}
  }
  resolveShelter(a){const sheltered=this.agents.filter(o=>o!==a&&o.action==="shelter"&&Math.hypot(o.x-a.x,o.y-a.y)<.15);if(sheltered.length){for(const o of sheltered){const r=this.relation(this.agents.indexOf(a),this.agents.indexOf(o));r.warmth+=5;r.trust+=3;a.memory.remember({day:this.day,minute:this.minute,kind:"sheltered",target:o.id,text:`${o.name}と同じ場所で雨宿りした`,strength:3});o.memory.remember({day:this.day,minute:this.minute,kind:"sheltered",target:a.id,text:`${a.name}と同じ場所で雨宿りした`,strength:3});}this.log(a,`${a.name}は${sheltered.map(o=>o.name).join("と")}と同じ木の下へ入った`,"sheltered",sheltered[0],4,a.reason);}else this.log(a,`${a.name}が、ひとりで木の下へ雨宿りした`,"sheltered-alone",null,3,a.reason);a.needs.fatigue=Math.max(0,a.needs.fatigue-20);}
  resolveEgg(a){const count=this.agents.filter(o=>o.action==="egg"&&Math.hypot(o.x-a.x,o.y-a.y)<.16).length;if(a.traits.attachment>.55){this.log(a,`${a.name}は卵のそばに座り、動かなかった`,"guarded-egg",null,4,"気になるものを見守り続ける性質が表れた");a.memory.remember({day:this.day,minute:this.minute,kind:"guarded-egg",target:"egg",text:"謎の卵を守った",strength:4});}else this.log(a,`${a.name}は卵へ近づき、${count>1?"ほかのマーパンと一緒に":"ひとりで"}じっと見た`,"watched-egg",null,3,a.reason);}
  inspireFollowers(leader){for(const o of this.agents.filter(x=>x!==leader&&x.action==="wait"&&x.traits.sociability>.45)){o.action="follow";o.target=offsetTarget(leader,this.agents.indexOf(o),.07);o.reason=`${leader.name}が先へ進むのを見た`;o.memoryReason=`${leader.name}の行動がきっかけになった`;o.mark="!";o.markUntil=this.elapsed+1.2;}}
  nearestAgent(a){return this.agents.filter(o=>o!==a).sort((x,y)=>Math.hypot(x.x-a.x,x.y-a.y)-Math.hypot(y.x-a.x,y.y-a.y))[0];}
  avoidOverlap(){for(let i=0;i<3;i++)for(let j=i+1;j<3;j++){const a=this.agents[i],b=this.agents[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=.105;if(d<min){const nx=d?dx/d:1,ny=d?dy/d:0,push=(min-d)*.055;a.x-=nx*push;b.x+=nx*push;a.y-=ny*push*.45;b.y+=ny*push*.45;}}}
  finishDay(){if(this.phase!=="running")return;this.phase="result";this.resultElapsed=0;this.minute=1140;if(this.dayEventCount<2)this.forceQuietEvent();const dayEvents=this.events.filter(e=>e.day===this.day),stories=NarrativeGenerator.create(this.day,dayEvents,this.agents,this.activeSeed);const entry={day:this.day,seed:this.activeSeed.id,events:dayEvents,stories};this.history.push(entry);this.save();updatePanels();document.getElementById("dayProgress").classList.remove("visible");if(this.day%10===0){this.phase="chronicle";showChronicle(this.history.slice(-10));}}
  forceQuietEvent(){const a=[...this.agents].sort((x,y)=>y.traits.caution-x.traits.caution)[0];this.log(a,`${a.name}は最後まで少し離れた場所から見ていた`,"stayed-apart",null,2,"慎重さが、近づかないという選択になった");}
  nextDay(){if(this.phase!=="result"&&this.phase!=="chronicle")return;this.day++;this.prepareMorning();}
  save(){const savedDay=this.phase==="result"?this.day+1:this.day;localStorage.setItem(SAVE_KEY,JSON.stringify({day:savedDay,events:this.events,history:this.history,relations:this.relations,pending:this.pending,worldFlags:this.worldFlags,agents:this.agents.map(a=>a.serialize())}));}
}

class NarrativeGenerator {
  static create(day,events,agents,seed){const important=events.filter(e=>e.kind!=="seed").sort((a,b)=>b.strength-a.strength||a.minute-b.minute);const chosen=events.filter(e=>e.kind==="seed"||important.slice(0,7).includes(e)).sort((a,b)=>a.minute-b.minute);const title=this.title(seed,important);const observer=chosen.map(e=>this.line(e)).join("\n\n");const views={observer};for(const a of agents){const own=chosen.filter(e=>!e.actor||e.actor===a.id||e.target===a.id);views[a.id]=own.map(e=>this.line(e,a)).join("\n\n")||`${a.name}は、その日を静かに覚えている。`;}return{title,views};}
  static title(seed,events){const top=events[0];if(top?.kind==="gave-fruit")return`${top.actorName.replace("いマーパン","")}が置いた木の実`;if(top?.kind==="egg-crack")return"小さなひび";if(top?.kind==="guarded-egg")return"卵のそばで";if(top?.kind==="explored")return`${top.actorName.replace("いマーパン","")}が見つけた道`;if(seed.id==="oneFruit")return"ひとつしかない木の実";if(seed.id==="manyFruit")return"満ち足りた草地";if(seed.id==="rain")return"雨の中の三匹";if(seed.id==="egg")return"卵";if(seed.id==="sound")return"草地の向こうの音";if(seed.id==="path")return"開いた小道";return top?top.text.replace(/[。、].*$/,""):"何もしなかった日";}
  static line(e,viewer=null){if(e.kind==="seed")return seedOpeningPast(e.text);let text=e.text;if(viewer){text=text.replaceAll(viewer.name,"自分");if(e.target===viewer.id&&e.kind==="gave-fruit")text=`${e.actorName}が、自分の前へ木の実を置いた`;}return`${formatTime(e.minute)}。${text}。${e.cause&&e.strength>=4?`\n${e.cause}。`:""}`;}
}

function setup(){const c=createCanvas(document.querySelector(".world").clientWidth,document.querySelector(".world").clientHeight);c.parent("canvas-wrap");pixelDensity(Math.min(2,window.devicePixelRatio||1));sim=new Simulation(loadState());wireUI();renderSeedPicker();updatePanels();lastRealTime=millis();}
function draw(){const now=millis(),dt=Math.min(.07,(now-lastRealTime)/1000);lastRealTime=now;sim.update(dt);drawWorld();updateClock();updateProgress();}
function drawWorld(){const t=sim.phase==="running"?sim.elapsed/DAY_SECONDS:sim.phase==="result"?1:0;const dusk=t>.72;background(dusk?"#d4c9b4":"#dcebe5");noStroke();fill(dusk?"#aebf9d":"#b8cfa9");rect(0,height*.42,width,height*.58);drawScenery();drawObjects();for(const a of [...sim.agents].sort((x,y)=>x.y-y.y))drawAgent(a);if(sim.weather==="大雨")drawRain();}
function drawScenery(){noStroke();fill("#758b6f");ellipse(width*.15,height*.39,width*.23,height*.2);fill("#5f735f");rect(width*.13,height*.31,width*.045,height*.27,8);fill("#e9e0cb");beginShape();vertex(width*.75,height*.47);vertex(width*.9,height*.47);vertex(width*.86,height*.35);vertex(width*.79,height*.35);endShape(CLOSE);fill("#718272");rect(width*.79,height*.38,width*.07,height*.09);fill(255,255,255,50);ellipse(width*.55,height*.69,width*.3,height*.1);if(sim.worldFlags.path){fill("#d5c8a8");beginShape();vertex(width*.78,height*.66);vertex(width,height*.53);vertex(width,height*.66);vertex(width*.8,height*.73);endShape(CLOSE);}}
function drawObjects(){for(const o of sim.objects){if(o.type==="fruit"&&o.amount>0){for(let i=0;i<o.amount;i++){fill("#8d5a39");stroke("#553a2b");ellipse(width*(o.x+(i%3-1)*.012),height*(o.y+Math.floor(i/3)*.012),10,8);}}else if(o.type==="egg"){fill("#ece5d3");stroke("#6b756d");strokeWeight(2);ellipse(width*o.x,height*o.y,31,40);if(sim.worldFlags.eggStage){stroke("#7b6c5d");line(width*o.x-2,height*o.y-12,width*o.x+3,height*o.y-4);line(width*o.x+3,height*o.y-4,width*o.x-1,height*o.y+3);}}else if(o.type==="sound"){noFill();stroke("#667c72");textSize(22);text("♪",width*o.x,height*o.y);}else if(o.type==="shelter"){noStroke();fill(74,94,74,35);ellipse(width*.18,height*.52,width*.22,height*.15);}}}
function drawAgent(a){const x=a.x*width,y=a.y*height,w=Math.min(145,width*.17);noStroke();fill(35,45,38,32);ellipse(x,y+w*.25,w*.58,w*.09);const look=a.lookAt||{x:a.x,y:a.y};a.marpan.setYaw(clamp((look.x-a.x)*2.2,-.42,.42));a.marpan.drawAt(x,y,{bodyWidth:w,bodyHeight:w*.68,lookX:look.x*width,lookY:look.y*height,pulse:a.action==="follow"?.08:0});noStroke();fill(44,56,48,180);textAlign(CENTER,CENTER);textFont("Yu Mincho");textSize(10);text(a.name,x,y+w*.48);if(a.mark&&sim.elapsed<a.markUntil){fill("#3e5146");textSize(19);text(a.mark,x+w*.4,y-w*.32);}}
function drawRain(){stroke(91,119,126,105);for(let i=0;i<95;i++){const x=(i*79+frameCount*4)%width,y=(i*43+frameCount*9)%height;line(x,y,x-5,y+15);}}
function mousePressed(){if(sim.phase!=="running"||mouseX<0||mouseX>width||mouseY<0||mouseY>height)return;const a=[...sim.agents].sort((x,y)=>Math.hypot(mouseX-x.x*width,mouseY-x.y*height)-Math.hypot(mouseX-y.x*width,mouseY-y.y*height))[0];if(a&&Math.hypot(mouseX-a.x*width,mouseY-a.y*height)<95)showMind(a);}function touchStarted(){mousePressed();return false;}function windowResized(){resizeCanvas(document.querySelector(".world").clientWidth,document.querySelector(".world").clientHeight);}

function wireUI(){document.querySelectorAll(".speed button").forEach(b=>b.onclick=()=>{sim.speed=Number(b.dataset.speed);document.querySelectorAll(".speed button").forEach(x=>x.classList.toggle("active",x===b));});document.getElementById("watchDay").onclick=()=>selectedSeed&&sim.startDay(selectedSeed);document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button,.panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.tab).classList.add("active");});document.querySelectorAll("dialog .close").forEach(b=>b.onclick=()=>{b.closest("dialog").close();if(b.closest("#storyDialog")&&["result","chronicle"].includes(sim.phase))sim.nextDay();});}
function renderSeedPicker(){if(!sim)return;const picker=document.getElementById("seedPicker");picker.classList.toggle("hidden",sim.phase!=="choosing");document.getElementById("seedDay").textContent=`第${sim.day}日`;document.getElementById("seedOptions").innerHTML=SEEDS.map(s=>`<button class="seed-option" data-seed="${s.id}" ${sim.day<s.unlock?"disabled":""}><span>${s.icon}</span>${sim.day<s.unlock?`第${s.unlock}日に解放`:s.name}</button>`).join("");document.querySelectorAll("[data-seed]").forEach(b=>b.onclick=()=>{selectedSeed=b.dataset.seed;document.querySelectorAll("[data-seed]").forEach(x=>x.classList.toggle("selected",x===b));const seed=SEEDS.find(s=>s.id===selectedSeed);document.getElementById("seedDescription").textContent=seed.description;document.getElementById("watchDay").disabled=false;});document.getElementById("seedDescription").textContent=`選ばなくても「何もしない」で${MORNING_SECONDS}秒後に始まります。`;document.getElementById("watchDay").disabled=true;}
function updateMorningCountdown(){if(!sim||sim.phase!=="choosing"||selectedSeed)return;const left=Math.max(1,Math.ceil(MORNING_SECONDS-sim.morningElapsed));document.getElementById("seedDescription").textContent=`選ばなくても「何もしない」で${left}秒後に始まります。`;}
function updateClock(){document.getElementById("dayLabel").textContent=`第${sim.day}日`;document.getElementById("timeLabel").textContent=sim.phase==="choosing"?"朝・種を選ぶ":sim.phase==="result"?"夜・観察記":`${phaseName(sim.minute)} ${formatTime(sim.minute)}`;}
function updateProgress(){const bar=document.querySelector("#dayProgress i");if(bar)bar.style.width=`${clamp(sim.elapsed/DAY_SECONDS*100,0,100)}%`;}
function updatePanels(){if(!sim)return;const todays=sim.events.filter(e=>e.day===sim.day).slice(-30).reverse();document.getElementById("eventLog").innerHTML=todays.length?todays.map(e=>`<div class="event"><time>${formatTime(e.minute)}</time><span>${escapeHTML(e.text)}${e.cause?`<button class="why" data-why="${e.id}">なぜ？</button>`:""}</span></div>`).join(""):`<p class="empty">物語の種を選ぶと、ここに三匹の答えが記されます。</p>`;document.querySelectorAll("[data-why]").forEach(b=>b.onclick=()=>{const e=sim.events.find(x=>x.id===b.dataset.why);const old=b.parentElement.querySelector(".event-reason");if(old)old.remove();else b.insertAdjacentHTML("afterend",`<small class="event-reason">${escapeHTML(e.cause)}</small>`);});document.getElementById("marpanList").innerHTML=sim.agents.map((a,i)=>`<article class="marpan-card" data-agent="${i}"><h3><i class="dot" style="background:${a.color}"></i>${a.name}</h3><p>${a.emotion}<br>${actionText(a)}</p></article>`).join("");document.querySelectorAll("[data-agent]").forEach(el=>el.onclick=()=>showMind(sim.agents[+el.dataset.agent]));let rel="";for(let i=0;i<3;i++)for(let j=i+1;j<3;j++){const r=sim.relation(i,j);rel+=`<article class="relation-card"><h3>${NAMES[i]} と ${NAMES[j]}</h3><p>${relationPhrase(r)}</p></article>`;}document.getElementById("relationList").innerHTML=rel;document.getElementById("historyList").innerHTML=sim.history.length?sim.history.slice().reverse().map((h,i)=>`<article class="history-card" data-history="${sim.history.length-1-i}"><h3>第${h.day}日　${escapeHTML(h.stories.title)}</h3><p>${SEEDS.find(s=>s.id===h.seed)?.name||"記録"}の日</p></article>`).join(""):`<p class="empty">夜になると、ここに一日ずつ物語が残ります。</p>`;document.querySelectorAll("[data-history]").forEach(el=>el.onclick=()=>showStory(sim.history[+el.dataset.history],false));}
function showMind(a){const others=sim.agents.filter(x=>x!==a).map(o=>`${o.name}：${relationPhrase(sim.relation(sim.agents.indexOf(a),sim.agents.indexOf(o)))}`).join("<br>");document.getElementById("mindContent").innerHTML=`<div class="mind-head"><i class="dot" style="background:${a.color}"></i><h2>${a.name}の頭の中</h2></div><div class="mind-grid"><div><small>個体ID</small><p>${a.id}</p></div><div><small>遺伝情報</small><p>${a.dna.slice(0,24)}…</p></div><div><small>性格傾向</small><p>${traitWords(a.traits)}</p></div><div><small>現在の欲求</small><p>${needWords(a.needs)}</p></div><div><small>現在の感情</small><p>${a.emotion}</p></div><div><small>関係</small><p>${others}</p></div><div><small>いまの行動</small><p>${actionText(a)}</p></div><div><small>選んだ理由</small><p>${a.reason}${a.memoryReason?`<br>${a.memoryReason}`:""}</p></div><div style="grid-column:1/-1"><small>最近の記憶</small><p>${a.memory.recent(4).map(m=>m.text).join("<br>")||"まだ強い記憶はない"}</p></div></div>`;document.getElementById("mindDialog").showModal();}
function showStory(entry,isNew=true){const dlg=document.getElementById("storyDialog"),content=document.getElementById("storyContent");const buttons=[`<button data-view="observer" class="active">観察者</button>`,...sim.agents.map(a=>`<button data-view="${a.id}">${a.name.replace("いマーパン","")}</button>`)].join("");content.innerHTML=`<h2>第${entry.day}日　${escapeHTML(entry.stories.title)}</h2><div class="perspectives">${buttons}</div><div class="story-body">${escapeHTML(entry.stories.views.observer)}</div>${isNew?`<button class="next-day" id="nextDay">次の日へ</button>`:""}`;content.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{content.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x===b));content.querySelector(".story-body").textContent=entry.stories.views[b.dataset.view]||entry.stories.views.observer;});if(isNew)document.getElementById("nextDay").onclick=()=>{dlg.close();sim.nextDay();};dlg.showModal();}
function showChronicle(entries){const dlg=document.getElementById("storyDialog"),content=document.getElementById("storyContent"),first=entries[0]?.day||sim.day,last=entries.at(-1)?.day||sim.day;const lines=entries.map(e=>`第${e.day}日　${e.stories.title}\n${chronicleMoment(e)}`).join("\n\n");content.innerHTML=`<h2>第${first}日〜第${last}日　十日間の観察記</h2><div class="story-body">${escapeHTML(lines)}</div><button class="next-day" id="nextDay">次の十日へ</button>`;document.getElementById("nextDay").onclick=()=>{dlg.close();sim.nextDay();};dlg.showModal();}
function chronicleMoment(entry){const event=[...entry.events].filter(e=>e.kind!=="seed").sort((a,b)=>b.strength-a.strength)[0];return event?event.text:"三匹は静かに一日を過ごした。";}

function offsetTarget(o,index,space){const a=(index-1)*2.1;return{type:o.type,x:clamp(o.x+Math.cos(a)*space,.1,.9),y:clamp(o.y+Math.sin(a)*space*.55,.45,.75)};}
function seedOpening(id){return{id:"",oneFruit:"草地の真ん中に、木の実がひとつ置かれた",manyFruit:"草地いっぱいに、木の実が置かれた",rain:"空が暗くなり、大雨が降りはじめた",egg:"草の上に、見たことのない卵が現れた",sound:"草地の端から、不思議な音が鳴った",path:"閉じていた小道が、静かに開いた",none:"観察者は何も変えず、三匹を見守った"}[id];}
function seedOpeningPast(text){return text.replace("置かれた","置かれていた").replace("降りはじめた","降りはじめた").replace("鳴った","聞こえた");}
function memoryLabel(a,o){const m=a.memory.matching(["sheltered","received-fruit","together"],o.id).at(-1);return m?`${m.day===sim.day-1?"昨日":"以前"}の「${m.text}」という`:"以前の";}
function emotionFor(a){return a==="fruit"?"木の実が気になる":a==="shelter"?"雨を警戒している":a==="egg"?"好奇心が動いている":a.startsWith("avoid")||a.startsWith("flee")?"怖がっている":a==="follow"?"誰かが気になる":a==="wait"?"慎重に見ている":"わくわくしている";}
function expressionFor(a){return a.startsWith("avoid")||a.startsWith("flee")||a==="shelter"?"worried":a==="wait"?"pupil":"surprised";}
function actionText(a){return{idle:"朝の草地を見ている",fruit:"木の実へ近づいている",shelter:"木の下へ急いでいる",egg:"卵を調べている",avoidEgg:"卵から離れている",sound:"音の方へ進んでいる",fleeSound:"音から逃げている",explore:"新しい小道へ向かっている",follow:"誰かのあとを追っている",wait:"その場で様子を見ている"}[a.action]||"次のことを考えている";}
function traitWords(t){return[[t.curiosity,"好奇心が強い"],[t.sociability,"誰かが気になる"],[t.caution,"慎重"],[t.appetite,"食いしんぼう"],[t.activity,"よく動く"],[t.harmony,"分け合いたがる"]].sort((a,b)=>b[0]-a[0]).slice(0,2).map(x=>x[1]).join("、");}
function needWords(n){const x=Object.entries(n).sort((a,b)=>b[1]-a[1])[0][0];return x==="hunger"?"おなかが空いている":x==="fatigue"?"休みたがっている":"誰かの気配を求めている";}
function relationPhrase(r){return r.trust>34?"互いのそばで安心している":r.warmth>26?"よく一緒にいる":r.caution>25?"少し警戒している":"まだ距離を測っている";}
function phaseName(m){return m<660?"朝":m<870?"昼":m<1030?"夕方":"夜";}function formatTime(m){const n=Math.floor(m)%1440;return`${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`;}
function escapeHTML(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function loadState(){try{return JSON.parse(localStorage.getItem(SAVE_KEY)||localStorage.getItem(OLD_SAVE_KEY)||"null");}catch{return null;}}
