const EXPRESSIONS=[{label:"通常",style:"pupil"},{label:"にこにこ",style:"happy"},{label:"びっくり",style:"surprised"},{label:"怒り",style:"angry"},{label:"心配",style:"worried"},{label:"泣く",style:"crying"},{label:"眠い",style:"sleepy"}];
// 家族差分はここだけを調整すれば、カタログと将来作品の両方へ反映できます。
const FAMILY=[
  {id:"mama",name:"マママーパン",role:"mama",scale:1.06,eyeScale:1,accessoryColor:"#986246"},
  {id:"papa",name:"パパマーパン",role:"papa",scale:1.08,eyeScale:1,accessoryColor:"#3977a5"},
  {id:"child",name:"こマーパン",role:"child",scale:.78,eyeScale:1.12,accessoryColor:"#8e5a42"},
  {id:"baby",name:"あかちゃんマーパン",role:"baby",scale:.53,eyeScale:1.28,accessoryColor:"#5d4738"},
  {id:"grandpa",name:"じいマーパン",role:"grandpa",scale:.94,eyeScale:.98,accessoryColor:"#a68f7c"},
  {id:"grandma",name:"ばあマーパン",role:"grandma",scale:.93,eyeScale:.98,accessoryColor:"#b4a69b"}
];
let members=[],selectedIndex=0,viewMode="catalog";
function setup(){const canvas=createCanvas(1200,760);canvas.parent("canvas-wrap");pixelDensity(1);textFont('"Hiragino Kaku Gothic ProN", "Yu Gothic", sans-serif');members=FAMILY.map(c=>{const m=new FamilyMarpan({familyRole:c.role,bodyScale:c.scale,eyeScale:c.eyeScale,accessoryColor:c.accessoryColor});m.enableAutoBlink(2400,4600);return m;});setupControls();resizeCanvasForViewport();}
function draw(){background("#f8f1e8");const px=touches.length?touches[0].x:mouseX,py=touches.length?touches[0].y:mouseY;if(viewMode==="size")drawSizeComparison(px,py);else drawCatalog(px,py);}
function drawCatalog(px,py){const columns=width<700?2:3,rows=ceil(members.length/columns),cardW=width/columns,cardH=height/rows;members.forEach((m,i)=>drawCard(m,i,cardW*(i%columns+.5),cardH*floor(i/columns)+cardH*.58,cardW,cardH,px,py));}
function drawCard(m,i,x,y,cardW,cardH,px,py){const base=min(cardW*.64,cardH*.55,255),selected=i===selectedIndex;noStroke();fill(selected?"#fffaf2":"#fbf8f3");rect(x-cardW/2+7,y-cardH*.48,cardW-14,cardH-12,8);stroke(selected?"#bb6b45":"#e2d7ca");strokeWeight(selected?2:1);noFill();rect(x-cardW/2+7,y-cardH*.48,cardW-14,cardH-12,8);noStroke();fill("#514237");textAlign(CENTER,CENTER);textSize(min(16,cardW*.06));text(FAMILY[i].name,x,y-cardH*.37);fill("#a28b78");textSize(10);text(expressionLabel(m.expression),x,y-cardH*.29);drawShadow(x,y,base*m.bodyScale);m.drawFamilyAt(x,y,base,{lookX:selected?px:x,lookY:selected?py:y});}
function drawSizeComparison(px,py){const groundY=height*.72;noStroke();fill("#eadccd");rect(0,groundY,width,height-groundY);stroke("#cdb9a3");line(0,groundY,width,groundY);const spacing=width/(members.length+1),maxBase=min(spacing*1.42,height*.46,210);members.forEach((m,i)=>{const bodyH=maxBase*m.bodyScale*.68,x=spacing*(i+1),y=groundY-bodyH*.5,selected=i===selectedIndex;drawShadow(x,y,maxBase*m.bodyScale);m.drawFamilyAt(x,y,maxBase,{lookX:selected?px:x,lookY:selected?py:y,animated:false});noStroke();fill("#725e4c");textAlign(CENTER,TOP);textSize(constrain(spacing*.1,10,14));text(FAMILY[i].name,x,groundY+22);});noStroke();fill("#8d7764");textAlign(LEFT,TOP);textSize(13);text("サイズのめやす",22,20);}
function drawShadow(x,y,w){noStroke();fill(58,38,26,24);ellipse(x,y+w*.36,w*.55,max(7,w*.05));}
function setupControls(){const select=document.querySelector("#member-select");FAMILY.forEach((c,i)=>select.add(new Option(c.name,i)));select.addEventListener("change",()=>{selectedIndex=Number(select.value);syncControls();});const container=document.querySelector("#expression-buttons");EXPRESSIONS.forEach(({label,style})=>{const b=document.createElement("button");b.type="button";b.textContent=label;b.dataset.style=style;b.addEventListener("click",()=>{setMemberExpression(members[selectedIndex],style);syncControls();});container.append(b);});document.querySelectorAll("#yaw-buttons button").forEach(b=>b.addEventListener("click",()=>{members[selectedIndex].setYaw(Number(b.dataset.yaw));syncControls();}));document.querySelector("#all-expression").addEventListener("click",()=>{const style=members[selectedIndex].expression;members.forEach(m=>setMemberExpression(m,style));syncControls();});document.querySelector("#view-mode").addEventListener("change",e=>{viewMode=e.target.value;});syncControls();}
function setMemberExpression(m,style){m.clearAllEyeSettings();m.setExpression(style);m.setEyeScale(m.baseEyeScale);m.bounce(style==="surprised"?.65:.25);}
function expressionLabel(style){return EXPRESSIONS.find(item=>item.style===style)?.label??"通常";}
function syncControls(){const m=members[selectedIndex];document.querySelector("#current-label").textContent=`${FAMILY[selectedIndex].name} / ${expressionLabel(m.expression)}`;document.querySelector("#member-select").value=selectedIndex;document.querySelectorAll("#expression-buttons button").forEach(b=>b.classList.toggle("is-active",b.dataset.style===m.expression));document.querySelectorAll("#yaw-buttons button").forEach(b=>b.classList.toggle("is-active",Number(b.dataset.yaw)===m.yaw));}
function mousePressed(){if(viewMode!=="catalog"||mouseY<0||mouseY>height)return;const columns=width<700?2:3,cardW=width/columns,cardH=height/ceil(members.length/columns),i=floor(mouseY/cardH)*columns+constrain(floor(mouseX/cardW),0,columns-1);if(i>=0&&i<members.length){selectedIndex=i;members[i].bounce(.25);syncControls();}}
function touchStarted(){return mousePressed();}function windowResized(){resizeCanvasForViewport();}function resizeCanvasForViewport(){resizeCanvas(1200,windowWidth<700?1040:760);}
