// Gitで管理している作品一覧。新しい作品はこの配列に1項目追加します。
// thumbnail がまだない場合も作品は掲載され、カードには準備中表示が出ます。
window.MOVING_SKETCH_WORKS = [
  {number:1,title:"Ma-pan: Do Re Mi",thumbnail:"./1_ma-pan/thumbnail.webp",url:"./1_ma-pan/",tags:["p5.js","Sound"],description:"3つの目がド・レ・ミの音と色に合わせて動きます。"},
  {number:2,title:"Ma-pan: Move",thumbnail:"./2_move/thumbnail.webp",url:"./2_move/",tags:["p5.js","Interactive"],description:"マウスを見つめながら小さなマーパンが追いかけます。"},
  {number:3,title:"Ma-pan: Design",thumbnail:"./3_design/thumbnail.webp",url:"./3_design/",tags:["p5.js","Character"],description:"マーパンの新しい表情を試すデザインスケッチ。"},
  {number:4,title:"Ma-pan: Color",thumbnail:"./4_Color/thumbnail.webp",url:"./4_Color/",tags:["p5.js","Color"],description:"カラーパレットから色を選び、マーパンの体を染めます。"},
  {number:5,title:"Ma-pan: Eye Size",thumbnail:"./5_eyesize/thumbnail.webp",url:"./5_eyesize/",tags:["p5.js","Character"],description:"3つの目の大きさを変えて表情を比べます。"},
  {number:6,title:"Ma-pan: Body Size",thumbnail:"./6_bodysize/thumbnail.webp",url:"./6_bodysize/",tags:["p5.js","Character"],description:"体の大きさと表情を見比べるスケッチ。"},
  {number:7,title:"Ma-pan: Golden Ratio",thumbnail:"./7_goldenratio/thumbnail.webp",url:"./7_goldenratio/",tags:["p5.js","Design"],description:"体と目を黄金比で設計した形を観察します。"},
  {number:8,title:"Ma-pan: Mouth",thumbnail:"./8_mouth/thumbnail.webp",url:"./8_mouth/",tags:["p5.js","Character"],description:"目や鼻、口の位置から生まれる表情を観察します。"},
  {number:9,title:"Ma-pan: Wink",thumbnail:"./9_wink/thumbnail.webp",url:"./9_wink/",tags:["p5.js","Character"],description:"左右の目を使ってウインクする表情スケッチ。"},
  {number:10,title:"Ma-pan: Eye",thumbnail:"./10_eye/thumbnail.webp",url:"./10_eye/",tags:["p5.js","Character"],description:"さまざまな目の表情を見比べます。"},
  {number:11,title:"Ma-pan: Rotate",thumbnail:"./11_rotate/thumbnail.webp",url:"./11_rotate/",tags:["p5.js","Motion"],description:"マーパンが左右へ回転するモーションスケッチ。"},
  {number:12,title:"Ma-pan: Screen Saver",thumbnail:"./12_screensaver/thumbnail.webp",url:"./12_screensaver/",tags:["p5.js","Motion"],description:"マーパンが画面の中を跳ね回るスクリーンセーバー。"},
  {number:13,title:"Ma-pan: Split",thumbnail:"./13_split/thumbnail.webp",url:"./13_split/",tags:["p5.js","Motion"],description:"分裂と合体を繰り返すマーパンのスケッチ。"},
  {number:14,title:"Ma-pan: Signal",thumbnail:"./14_signal/thumbnail.webp",url:"./14_signal/",tags:["p5.js","Interactive"],description:"目を信号に見立てて色を切り替えます。"},
  {number:15,title:"Ma-pan: Race Signal",thumbnail:"./15_racesignal/thumbnail.webp",url:"./15_racesignal/",tags:["p5.js","Sound"],description:"3・2・1・GOの音声に合わせて目が点灯します。"},
  {number:16,title:"Ma-pan: Star Struck",thumbnail:"./16_StarStruck/thumbnail.webp",url:"./16_StarStruck/",tags:["p5.js","Interactive"],description:"触れると目がダイヤ形に輝くリアクション作品。"},
  {number:17,title:"Ma-pan: Black Pen",thumbnail:"./17_blackpen/thumbnail.webp",url:"./17_blackpen/",tags:["p5.js","Drawing"],description:"黒いペンでマーパンを自由に描くスケッチ。"},
  {number:18,title:"Ma-pan: Coloring",thumbnail:"./18_coloring/thumbnail.webp",url:"./18_coloring/",tags:["p5.js","Drawing"],description:"色を選んでマーパンを塗る作品。"},
  {number:19,title:"Ma-pan: Bird",thumbnail:"./19_Bird/thumbnail.webp",url:"./19_Bird/",tags:["p5.js","Interactive"],description:"鳥に触れるとマーパンの目が変化します。"},
  {number:20,title:"Ma-pan: Stretch",thumbnail:"./20_Stretch/thumbnail.webp",url:"./20_Stretch/",tags:["p5.js","Motion"],description:"体が伸び縮みするモーションスケッチ。"},
  {number:21,title:"Ma-pan: Compress",thumbnail:"./21_compress/thumbnail.webp",url:"./21_compress/",tags:["p5.js","Motion"],description:"体をへこませながら進むマーパン。"},
  {number:22,title:"Ma-pan: Rolling",thumbnail:"./22_rolling/thumbnail.webp",url:"./22_rolling/",tags:["p5.js","Motion"],description:"2体のマーパンが回転しながら進みます。"},
  {number:23,title:"Ma-pan: Melody Flight",thumbnail:"./23_FlappyBird/thumbnail.webp",url:"./23_FlappyBird/",tags:["p5.js","Game","Sound"],description:"音の壁をくぐるメロディーフライト。"},
  {number:24,title:"Ma-pan: Tulip Flight",thumbnail:"./24_FlappyBird2/thumbnail.webp",url:"./24_FlappyBird2/",tags:["JavaScript","Game","Sound"],description:"チューリップのメロディーに合わせて飛びます。"},
  {number:25,title:"Ma-pan: Frog Song Flight",thumbnail:"./25_FlappyBird3/thumbnail.webp",url:"./25_FlappyBird3/",tags:["JavaScript","Game","Sound"],description:"かえるのうたに合わせたフライトゲーム。"},
  {number:26,title:"Ma-pan: Melody Fly",thumbnail:"./26_MelodyFly/thumbnail.webp",url:"./26_MelodyFly/",tags:["JavaScript","Game","Sound"],description:"メロディーを選んで遊べるフライトゲーム。"},
  {number:27,title:"Ma-pan: Melody Fly 4",thumbnail:"./27_MelodyFly4/thumbnail.webp",url:"./27_MelodyFly4/",tags:["p5.js","Game","Sound"],description:"8つの童謡からステージを選んで遊べます。"},
  {number:29,title:"Ma-pan: Facial",thumbnail:"./29_facial/F08_surprised.png",url:"./29_facial/",tags:["p5.js","Character"],description:"さまざまな表情を見比べる2.5Dカタログ。"},
  {number:30,title:"Ma-pan: Bread",thumbnail:"./30_Bread/thumbnail.webp",url:"./30_Bread/",tags:["p5.js","Character"],description:"パンの種類や焼き上がりで姿が変わるキャラクター図鑑。"},
  {number:31,title:"Ma-pan: Hill Climb",thumbnail:"./31_hilclimb/itch-cover.png",url:"./31_hilclimb/",tags:["p5.js","Game"],description:"でこぼこ道を進むヒルクライムゲーム。"},
  {number:32,title:"Ma-pan: Family",thumbnail:"./32_Family/Family.png",url:"./32_Family/",tags:["p5.js","Character"],description:"表情や体格の違うマーパン一家のカタログ。"},
  {number:33,title:"Ma-pan: Beat Clicker",thumbnail:"./33_CookieClicker/itch-cover-630x500.png",url:"./33_CookieClicker/",tags:["p5.js","Game","Sound"],description:"マーパンを叩いて演奏会場を育てるクリックゲーム。"},
  {number:34,title:"Eating Notes",thumbnail:"./34_Eatingnotes/itch-cover.png",url:"./34_Eatingnotes/",tags:["p5.js","Game","Sound"],description:"音符を食べながら育つリズムゲーム。"},
  {number:35,title:"Fish",thumbnail:"./35_Fish/スクリーンショット 2026-08-27 045457.png",url:"./35_Fish/",tags:["p5.js","Interactive"],description:"水の中を泳ぐ魚たちのスケッチ。"},
  {number:36,title:"Shadow",thumbnail:"./36_shadow/thumbnail.webp",url:"./36_shadow/",tags:["p5.js","Interactive"],description:"影の動きと表情を楽しむインタラクティブ作品。"},
  {number:37,title:"Ice Crash",thumbnail:"./37_IceCrash/IceCrash-cover-630x500.png",url:"./37_IceCrash/",tags:["p5.js","Game"],description:"氷の世界を舞台にしたアクションゲーム。"},
  {number:39,title:"Lava Lamp",thumbnail:"./39_lavalamp/thumbnail.webp",url:"./39_lavalamp/",tags:["p5.js","Generative"],description:"ゆっくり形を変える光を眺めるスケッチ。"},
  {number:40,title:"Story Generator",thumbnail:"./40_StoryGen/thumbnail.webp",url:"./40_StoryGen/",tags:["p5.js","Story"],description:"画面の中から物語が生まれるジェネレーター。"},
  {number:41,title:"Othello",thumbnail:"./41_Othello/thumbnail.webp",url:"./41_Othello/",tags:["JavaScript","Game"],description:"ブラウザで遊べるオセロゲーム。"}
];
