const canvas=document.querySelector('#art'),ctx=canvas.getContext('2d'),buttons=[...document.querySelectorAll('.mode')],progressEl=document.querySelector('#progress'),reading=document.querySelector('#reading');
const phrases={circle:[...'いろはにほへと'],vertical:[...'ちりぬるを'],symmetry:[...'わかよたれそ'],free:[...'つねならむ']};
let mode='circle',glyphs=[],strokes=[],active=false,start=0,dpr=1,w=0,h=0,soundOn=true,audio=null;const TAU=Math.PI*2;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),polar=(x,y,r,a)=>[x+Math.cos(a)*r,y+Math.sin(a)*r];
function curve(points,double=false,weight=3,delay=0){return{points,double,weight,delay}}
function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);compose()}
function compose(){const cx=w/2,cy=h/2+8,s=Math.min(w,h),chars=phrases[mode];glyphs=[];strokes=[];
 if(mode==='circle'){const ring=Math.min(s*.205,w*.25);chars.forEach((ch,i)=>{const a=-Math.PI/2+i*TAU/chars.length;glyphs.push({ch,x:cx+Math.cos(a)*ring,y:cy+Math.sin(a)*ring,a:a+Math.PI/2,size:clamp(s*.082,46,76)});const a0=a-.24,a1=a+.82,r0=ring*.92,r1=ring*1.67;strokes.push(curve([polar(cx,cy,r0,a0),polar(cx,cy,r1,a0+.08),polar(cx,cy,r1,a1-.08),polar(cx,cy,r0,a1)],true,2.05,i*.018))})}
 if(mode==='vertical'){const gap=clamp(h*.105,57,88),top=cy-gap*2;chars.forEach((ch,i)=>glyphs.push({ch,x:cx+Math.sin(i*1.5)*12,y:top+i*gap,a:(i%2?1:-1)*.035,size:clamp(s*.09,52,78)}));const y0=top-gap*.68,y1=top+gap*4.68;strokes.push(curve([[cx-42,y0],[cx+92,cy-gap],[cx-96,cy+gap],[cx+34,y1]],false,4.6));strokes.push(curve([[cx+15,y0-10],[cx-104,cy-gap*.45],[cx+105,cy+gap*.55],[cx-22,y1+8]],false,2.8,.035));strokes.push(curve([[cx+58,y0+15],[cx-18,cy-gap*.9],[cx+50,cy+gap*.9],[cx-66,y1-14]],false,1.75,.07))}
 if(mode==='symmetry'){const base=cy+s*.235,apex=cy-s*.27,spread=Math.min(w*.31,s*.31),slots=[[0,apex+38],[-spread*.32,cy-28],[spread*.32,cy-28],[-spread*.58,base-36],[spread*.58,base-36],[0,base-12]];chars.forEach((ch,i)=>glyphs.push({ch,x:cx+slots[i][0],y:slots[i][1],a:i===0?0:(i%2?-.18:.18),size:clamp(s*.078,45,70)}));const left=[[[cx,apex],[cx-spread*.08,apex+75],[cx-spread*.55,cy+30],[cx-spread,base]],[[cx-5,apex+42],[cx-spread*.42,cy-80],[cx-spread*.18,cy+55],[cx-spread*.82,base-12]],[[cx-12,cy-45],[cx-spread*.62,cy-8],[cx-spread*.36,base-25],[cx-spread*.92,base-6]],[[cx-18,cy+28],[cx-spread*.28,cy+82],[cx-spread*.58,base-52],[cx-spread*.76,base]]];left.forEach((p,i)=>{strokes.push(curve(p,false,[4.8,2.2,3.2,1.6][i],i*.025));strokes.push(curve(p.map(([x,y])=>[2*cx-x,y]),false,[4.8,2.2,3.2,1.6][i],i*.025))});strokes.push(curve([[cx-spread*.9,base],[cx-spread*.3,base-18],[cx+spread*.3,base+8],[cx+spread*.9,base]],false,3.8,.05))}
 if(mode==='free'){const base=cy+s*.15,span=Math.min(w*.34,s*.39);chars.forEach((ch,i)=>{const q=i/(chars.length-1);glyphs.push({ch,x:cx-span+q*span*2,y:base-Math.sin(q*Math.PI)*25,a:(q-.5)*.28,size:clamp(s*.082,48,74)})});strokes.push(curve([[cx-span*1.08,base-4],[cx-span*.58,base+92],[cx+span*.6,base+86],[cx+span*1.12,base-10]],false,5.2));strokes.push(curve([[cx-span,base+12],[cx-span*.45,base+55],[cx+span*.52,base+52],[cx+span*.96,base+6]],false,1.8,.025));strokes.push(curve([[cx-span*1.04,base],[cx-span*1.18,cy-42],[cx-span*.9,cy-110],[cx-span*.72,cy-142]],false,3.7,.04));strokes.push(curve([[cx+span*1.04,base],[cx+span*.94,cy-25],[cx+span*1.11,cy-46],[cx+span*1.2,cy-20]],false,2.2,.04));strokes.push(curve([[cx,base+8],[cx-4,cy-40],[cx+8,cy-130],[cx,cy-s*.29]],false,4.2,.06));strokes.push(curve([[cx-5,cy-s*.27],[cx-span*.78,cy-s*.18],[cx-span*.53,cy+18],[cx-20,base-18]],false,2.7,.085));strokes.push(curve([[cx+7,cy-s*.25],[cx+span*.67,cy-s*.11],[cx+span*.48,cy+25],[cx+18,base-12]],false,1.8,.095))}}
function cubic(p,t){const u=1-t,[a,b,c,d]=p;return[u*u*u*a[0]+3*u*u*t*b[0]+3*u*t*t*c[0]+t*t*t*d[0],u*u*u*a[1]+3*u*u*t*b[1]+3*u*t*t*c[1]+t*t*t*d[1]]}
function trace(s,amount,time,offset=0){const n=100,end=Math.max(1,Math.floor(n*amount));ctx.beginPath();for(let j=0;j<=end;j++){const q=cubic(s.points,j/n),v=Math.sin(j*.31+time*.0011)*.45;q[0]+=v+offset;q[1]+=offset*.18;j?ctx.lineTo(q[0],q[1]):ctx.moveTo(q[0],q[1])}ctx.strokeStyle='#171714';ctx.lineWidth=s.weight*(.94+Math.sin(time*.0013+s.delay*20)*.06);ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke()}
function drawStroke(s,master,time){const amount=clamp((master-s.delay)/(1-s.delay),0,1);if(!amount)return;if(s.double){trace(s,amount,time,-3.7);trace(s,amount,time,3.7)}else{trace(s,amount,time);ctx.save();ctx.globalAlpha=.14;trace({...s,weight:Math.max(.7,s.weight*.3)},amount,time,s.weight*.62);ctx.restore()}}
function drawGlyph(g,time,alive){ctx.save();ctx.translate(g.x,g.y);ctx.rotate(g.a+(alive?Math.sin(time*.0006+g.x)*.008:0));ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`500 ${g.size}px "Yu Mincho","Hiragino Mincho ProN",serif`;ctx.fillStyle='#171714';ctx.fillText(g.ch,0,0);ctx.globalAlpha=.13;ctx.translate(1,-.6);ctx.fillText(g.ch,0,0);ctx.restore()}
function eyes(fade,time){if(!fade)return;const cx=w/2,cy=mode==='free'?h/2+Math.min(w,h)*.09:h/2+8,r=clamp(Math.min(w,h)*.047,27,43);[-1,0,1].forEach((v,i)=>{ctx.save();ctx.translate(cx+v*r*.92,cy+(i===1?-r*.26:r*.16));ctx.scale(1,Math.max(.03,fade*(.9+Math.sin(time*.001+i)*.035)));ctx.beginPath();ctx.ellipse(0,0,9,6.3,0,0,TAU);ctx.fillStyle='#f3efe4';ctx.fill();ctx.lineWidth=1.3;ctx.strokeStyle='#171714';ctx.stroke();ctx.beginPath();ctx.arc(0,0,2.5,0,TAU);ctx.fillStyle='#a33526';ctx.fill();ctx.restore()})}
function render(time){ctx.clearRect(0,0,w,h);const elapsed=active?time-start:0,master=active?clamp(elapsed/1250,0,1):0,fade=clamp((elapsed-1280)/850,0,1),alive=fade>0;ctx.save();if(alive){const b=1+Math.sin(time*.0007)*.005;ctx.translate(w/2,h/2);ctx.scale(b,b);ctx.translate(-w/2,-h/2)}glyphs.forEach(g=>drawGlyph(g,time,alive));strokes.forEach(s=>drawStroke(s,master,time));ctx.restore();eyes(fade,time);progressEl.style.width=master*100+'%';requestAnimationFrame(render)}
function play(){if(!soundOn)return;if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();const now=audio.currentTime,sets={circle:[220,277.18,329.63,392],vertical:[196,246.94,293.66],symmetry:[220,330,440],free:[174.61,220,261.63,349.23]};sets[mode].forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type=i%2?'sine':'triangle';o.frequency.value=f;g.gain.setValueAtTime(0,now+i*.045);g.gain.linearRampToValueAtTime(.032,now+i*.045+.06);g.gain.exponentialRampToValueAtTime(.001,now+1.85);o.connect(g).connect(audio.destination);o.start(now+i*.045);o.stop(now+1.9)})}
function activate(){if(active)return;active=true;start=performance.now();document.body.classList.add('started');reading.textContent='ひとつの形になった';play()}
function reset(){active=false;start=0;document.body.classList.remove('started');progressEl.style.width='0';reading.textContent=phrases[mode].join('　')}
canvas.addEventListener('pointerdown',activate);buttons.forEach(btn=>btn.addEventListener('click',()=>{buttons.forEach(b=>b.classList.toggle('active',b===btn));mode=btn.dataset.mode;reset();compose()}));document.querySelector('#reset').addEventListener('click',reset);document.querySelector('#sound').addEventListener('click',e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?'音　あり':'音　なし';e.currentTarget.setAttribute('aria-pressed',String(soundOn))});addEventListener('resize',resize);resize();requestAnimationFrame(render);
