const PITCHES={ド:261.63,レ:293.66,ミ:329.63,ファ:349.23,ソ:392,ラ:440,シ:493.88};
const COLORS={ド:"#e87567",レ:"#e89b54",ミ:"#e4c34f",ファ:"#8fc36e",ソ:"#61adbd",ラ:"#778dca",シ:"#a184bd"};
const SONGS=[{id:"free",title:"フリービート",price:0,bpm:96,melody:[],unlocked:true},{id:"twinkle",title:"きらきら星",price:350,bpm:104,melody:["ド","ド","ソ","ソ","ラ","ラ","ソ","ファ","ファ","ミ","ミ","レ","レ","ド","ソ","ソ","ファ","ファ","ミ","ミ","レ","ソ","ソ","ファ","ファ","ミ","ミ","レ","ド","ド","ソ","ソ","ラ","ラ","ソ","ファ","ファ","ミ","ミ","レ","レ","ド"],unlocked:false}];
const UPGRADES=[{id:"metronome",icon:"♩",name:"メトロノーム",description:"拍ごとに音符を生み出す",baseCost:25,passive:1},{id:"speaker",icon:"▣",name:"スピーカー",description:"1回のタップ +1 音符",baseCost:80,click:1},{id:"choir",icon:"♬",name:"マーパン合唱団",description:"毎秒音符を生み出す仲間",baseCost:160,passive:4}];
let score=0,combo=0,fever=0,feverUntil=0,upgrades={},particles=[],popScale=1,popVelocity=0,lastBeat=-1,nextPassive=0,audioReady=false,audioStart=0,currentSong=SONGS[0],melodyNote=-1,melodyPulse=0,marpan;
function setup(){const canvas=createCanvas(900,650);canvas.parent("canvas-wrap");canvas.style("width","100%");canvas.style("height","auto");pixelDensity(1);textFont('"Avenir Next", "Yu Gothic", sans-serif');marpan=new Marpan25D({maxSize:420,bodyColor:"#fffdf4"});marpan.enableAutoBlink(2600,4800);UPGRADES.forEach((item)=>upgrades[item.id]=0);setupShop();setupMusic();resizeCanvasForViewport();nextPassive=millis()+1000;}
function draw(){const beat=beatPosition();if(beat.index!==lastBeat){lastBeat=beat.index;playBeat(beat.index);}if(millis()>=nextPassive){collectPassive();nextPassive=millis()+1000;}updatePhysics();drawScene(beat.phase);drawParticles();}
function beatPosition(){const beatMs=60000/currentSong.bpm,elapsed=max(0,millis()-(audioReady?audioStart:0));return{index:floor(elapsed/beatMs),phase:(elapsed%beatMs)/beatMs};}
function playBeat(index){if(!audioReady)return;const note=currentSong.melody.length?currentSong.melody[index%currentSong.melody.length]:null;if(note){melodyNote=index%currentSong.melody.length;melodyPulse=1;tone(PITCHES[note],.09,.22);}else tone(index%4===0?130.81:261.63,.045,.08);}
function drawScene(phase){const feverMode=millis()<feverUntil,pulse=pow(max(0,1-phase),3);background(feverMode?"#f7c9a0":"#f9e8c9");noStroke();fill(feverMode?"#f3aa82":"#f1d5a7");for(let i=0;i<12;i++)ellipse((i*107+frameCount*.25)%width,70+sin(frameCount*.01+i)*18,8+pulse*10,8+pulse*10);fill("#f4dba9");ellipse(width*.5,height*.53,min(width*.78,470)+pulse*24,min(width*.55,350)+pulse*24);drawVenue(phase,feverMode);const size=min(width*.58,385),bounce=sin(phase*TWO_PI)*10+pulse*(feverMode?22:13);marpan.setPosition(width*.5,height*.52+bounce);marpan.lookAt(mouseX,mouseY);marpan.drawAt(width*.5,height*.52+bounce,{bodyWidth:size*popScale,bodyHeight:size*.7/popScale,scaleX:1,scaleY:1});if(feverMode){fill("#fff7d1");textAlign(CENTER,CENTER);textStyle(BOLD);textSize(27);text("MARPAN FEVER!",width*.5,height*.18+sin(frameCount*.1)*4);textStyle(NORMAL);}melodyPulse*=.88;}
function drawVenue(phase,feverMode){if(upgrades.metronome)drawMetronome(width*.17,height*.46,phase,feverMode);if(upgrades.speaker){drawSpeaker(width*.81,height*.56,feverMode);drawSpeaker(width*.19,height*.67,feverMode);}const count=min(8,upgrades.choir);for(let i=0;i<count;i++){const x=width*(.28+i*.064),y=height*.77+sin(frameCount*.045+i)*5-(feverMode?8:0),note=Object.keys(PITCHES)[i%7];drawChoir(x,y,note,i===melodyNote%7?melodyPulse:0);}}
function drawMetronome(x,y,phase,feverMode){push();translate(x,y);stroke("#8e6347");strokeWeight(4);fill("#d48b5d");triangle(-24,30,24,30,17,-28);strokeWeight(3);line(0,5,0,-23+sin(phase*TWO_PI)*(feverMode?16:10));fill("#f4c84b");noStroke();ellipse(0,-25+sin(phase*TWO_PI)*(feverMode?16:10),8,8);pop();labelCount(x+31,y-30,"×"+upgrades.metronome);}
function drawSpeaker(x,y,feverMode){push();translate(x,y);scale(feverMode?1+sin(frameCount*.2)*.08:1+melodyPulse*.08);fill("#6ea9c5");stroke("#3f7286");strokeWeight(3);rect(-28,-30,56,60,6);fill("#f7e9cf");ellipse(0,-7,27,27);ellipse(0,20,12,12);pop();labelCount(x,y-43,"×"+upgrades.speaker);}
function drawChoir(x,y,note,active){push();translate(x,y-active*7);scale(1+active*.22);fill(COLORS[note]);noStroke();ellipse(0,0,45,34);fill("#352a25");ellipse(-8,-3,5,7);ellipse(8,-3,5,7);stroke("#352a25");strokeWeight(2);line(-7,8,7,8);pop();}
function labelCount(x,y,value){fill("#80624e");noStroke();textAlign(CENTER,CENTER);textStyle(BOLD);textSize(11);text(value,x,y);textStyle(NORMAL);}
function updatePhysics(){popVelocity+=(1-popScale)*.25;popScale+=popVelocity;popVelocity*=.72;for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.vy+=.08;p.life--;}particles=particles.filter((p)=>p.life>0);}
function mousePressed(){if(mouseX>=0&&mouseX<=width&&mouseY>=height*.2&&mouseY<=height*.88)tapMarpan();return false;}function touchStarted(){return false;}
function tapMarpan(){ensureAudio();const beatMs=60000/currentSong.bpm,near=Math.min((millis()-audioStart)%beatMs,beatMs-(millis()-audioStart)%beatMs);let judgement="NORMAL",base=1;if(near<=90){judgement="JUST";base=4;combo++;fever+=currentSong.melody.length?3:2;}else if(near<=185){judgement="GOOD";base=2;combo++;fever+=currentSong.melody.length?1:0;}else{combo=0;fever=max(0,fever-1);}const gain=round((base+upgrades.speaker)*(1+min(2,floor(combo/5)*.25))*(millis()<feverUntil?3:1));score+=gain;popScale=.78;popVelocity=-.12;showToast(`${judgement}! ♪+${gain}`);tone(judgement==="JUST"?523.25:261.63,.12,.12);burst(judgement,gain);if(fever>=100&&millis()>=feverUntil){fever=0;feverUntil=millis()+12000;showToast("MARPAN FEVER!");}syncUI();}
function ensureAudio(){if(audioReady)return;userStartAudio();audioReady=true;audioStart=millis();document.querySelector("#sound-label").textContent="音声 ON";}
function tone(frequency,volume,duration){if(!audioReady)return;const oscillator=new p5.Oscillator("triangle");oscillator.freq(frequency);oscillator.amp(volume);oscillator.start();oscillator.stop(duration);}
function burst(judgement,gain){for(let i=0;i<(judgement==="JUST"?12:5);i++)particles.push({x:width*.5,y:height*.53,vx:random(-4,4),vy:random(-6,-2),life:45+random(25),label:i%2?"♪":`+${gain}`,color:judgement==="JUST"?"#e4685d":"#d79542"});}function drawParticles(){textAlign(CENTER,CENTER);textStyle(BOLD);for(const p of particles){fill(p.color);textSize(p.label==="♪"?22:14);text(p.label,p.x,p.y);}textStyle(NORMAL);}
function collectPassive(){let rate=0;UPGRADES.forEach((item)=>rate+=(upgrades[item.id]||0)*(item.passive||0));if(rate){score+=rate;syncUI();}}
function setupShop(){const shop=document.querySelector("#shop");UPGRADES.forEach((item)=>{const article=document.createElement("article");article.className="upgrade";article.innerHTML=`<div class="upgrade-icon">${item.icon}</div><div><h3>${item.name} <span class="owned" data-owned="${item.id}">×0</span></h3><p>${item.description}</p></div><button class="buy" data-id="${item.id}"></button>`;article.querySelector("button").addEventListener("click",()=>buyUpgrade(item.id));shop.append(article);});}
function setupMusic(){const list=document.querySelector("#music-list");SONGS.forEach((song,index)=>{const item=document.createElement("article");item.className="music-item";item.innerHTML=`<div><b>${song.title}</b><small>${song.bpm} BPM / ${song.price?`解禁 ♪${song.price}`:"いつでも演奏OK"}</small></div><button data-song="${song.id}"></button>`;item.querySelector("button").addEventListener("click",()=>selectSong(index));list.append(item);});syncUI();}
function cost(item){return floor(item.baseCost*pow(1.16,upgrades[item.id]));}function buyUpgrade(id){const item=UPGRADES.find((value)=>value.id===id),price=cost(item);if(score<price)return;ensureAudio();score-=price;upgrades[id]++;showToast(`${item.name} ×${upgrades[id]}`);syncUI();}
function selectSong(index){const song=SONGS[index];if(!song.unlocked){if(score<song.price)return;score-=song.price;song.unlocked=true;showToast(`${song.title} 解禁!`);}currentSong=song;lastBeat=-1;melodyNote=-1;if(audioReady)audioStart=millis();document.querySelector("#bpm-label").textContent=`♩ ${song.bpm} BPM`;syncUI();}
function syncUI(){document.querySelector("#score").textContent=`♪ ${floor(score).toLocaleString("ja-JP")}`;document.querySelector("#combo").textContent=`${combo} COMBO`;document.querySelector("#fever-text").textContent=`${floor(min(100,fever))} / 100`;document.querySelector("#fever-fill").style.width=`${min(100,fever)}%`;document.querySelector("#rate-label").textContent=`毎秒 ♪${UPGRADES.reduce((total,item)=>total+(upgrades[item.id]||0)*(item.passive||0),0)}`;document.querySelector("#song-title").textContent=currentSong.title;UPGRADES.forEach((item)=>{const button=document.querySelector(`[data-id="${item.id}"]`),owned=document.querySelector(`[data-owned="${item.id}"]`);if(button){button.textContent=`♪ ${cost(item)}  (${upgrades[item.id]})`;button.disabled=score<cost(item);}if(owned)owned.textContent=`×${upgrades[item.id]}`;});SONGS.forEach((song)=>{const button=document.querySelector(`[data-song="${song.id}"]`);button.textContent=song.id===currentSong.id?"演奏中":song.unlocked?"選択":`♪ ${song.price}`;button.disabled=!song.unlocked&&score<song.price;button.parentElement.classList.toggle("is-active",song.id===currentSong.id);});}
let toastTimer;function showToast(message){const toast=document.querySelector("#toast");toast.textContent=message;toast.classList.remove("show");void toast.offsetWidth;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),650);}function windowResized(){resizeCanvasForViewport();}function resizeCanvasForViewport(){resizeCanvas(900,width<760?600:650);}