const DAMS={
  gravity:{label:"重力式",note:"重さで、どっしり支える",limit:10.5,color:"#cbc7bb"},
  fill:{label:"フィルダム",note:"土と岩の塊で、広く支える",limit:11.5,color:"#a98a62"},
  hollow:{label:"中空重力式",note:"少ない材料を、柱で支える",limit:9.8,color:"#d7d3c8"},
  arch:{label:"アーチ式",note:"力を、左右の岩盤へ逃がす",limit:10.8,color:"#d3d0c8"}
};
let damKey="gravity",marpans=[],debris=[],drops=[],load=0,phase="calm",phaseAt=0,showPressure=true,sizeChoice="small",audioCtx,muted=false,shake=0;
let stage={},stageObserver;

function setup(){
  const host=document.getElementById("sketch"),box=host.parentElement.getBoundingClientRect();
  const c=createCanvas(Math.max(320,Math.floor(box.width)),Math.max(180,Math.floor(box.height)));c.parent(host);pixelDensity(Math.min(devicePixelRatio,2));
  stageObserver=new ResizeObserver(()=>resizeToStage());stageObserver.observe(host.parentElement);requestAnimationFrame(resizeToStage);
  buildControls();resetWorld();
}
function buildControls(){
  const nav=document.getElementById("dam-picker");
  Object.entries(DAMS).forEach(([key,d])=>{const b=document.createElement("button");b.textContent=d.label;b.dataset.dam=key;b.addEventListener("click",()=>selectDam(key));nav.appendChild(b)});
  document.getElementById("reset").onclick=resetWorld;document.getElementById("again").onclick=resetWorld;
  document.getElementById("choose").onclick=()=>{document.getElementById("result").hidden=true;document.getElementById("dam-picker").scrollIntoView({behavior:"smooth"})};
  document.getElementById("pressure-toggle").onclick=e=>{showPressure=!showPressure;e.currentTarget.textContent=`水圧 ${showPressure?"ON":"OFF"}`;e.currentTarget.setAttribute("aria-pressed",showPressure)};
  document.getElementById("sound-toggle").onclick=e=>{muted=!muted;e.currentTarget.textContent=muted?"×":"♪";e.currentTarget.setAttribute("aria-pressed",!muted)};
  document.querySelectorAll(".size-button").forEach(b=>b.onclick=()=>{sizeChoice=b.dataset.size;document.querySelectorAll(".size-button").forEach(x=>x.classList.toggle("active",x===b))});
}
function selectDam(key){damKey=key;document.getElementById("dam-note").textContent=DAMS[key].note;document.querySelectorAll("[data-dam]").forEach(b=>b.classList.toggle("active",b.dataset.dam===key));resetWorld()}
function resetWorld(){marpans=[];debris=[];drops=[];load=0;phase="calm";phaseAt=millis();shake=0;document.getElementById("result").hidden=true;document.getElementById("hint").textContent="水面をタップして、マーパンを落としてみよう";document.getElementById("dam-note").textContent=DAMS[damKey].note;document.querySelectorAll("[data-dam]").forEach(b=>b.classList.toggle("active",b.dataset.dam===damKey))}
function layout(){stage={ground:height*.86,waterY:height*.25,damX:width*.62,damW:constrain(width*.14,70,160),damH:height*.61}}
function draw(){layout();background("#bfe5ee");push();translate(random(-shake,shake),random(-shake,shake));drawSky();drawTerrain();drawWater();drawPressure();drawDam();updateMarpans();drawEffects();pop();updateFailure();shake*=.9}
function drawSky(){noStroke();fill("#dff3f5");rect(0,0,width,height*.28);fill(255,245);for(let i=0;i<3;i++)ellipse(width*(.15+i*.29),height*.1+i%2*10,55,16)}
function drawTerrain(){noStroke();fill("#7f7665");rect(0,stage.ground,width,height-stage.ground);fill("#657065");beginShape();vertex(stage.damX-8,stage.ground);vertex(stage.damX+stage.damW*.9,stage.ground);vertex(stage.damX+stage.damW*1.45,height*.55);vertex(width,height*.52);vertex(width,stage.ground);endShape(CLOSE)}
function drawWater(){const breach=phase==="breach"||phase==="failed";noStroke();fill("#42aeca");beginShape();vertex(0,stage.waterY);for(let x=0;x<stage.damX;x+=14)vertex(x,stage.waterY+sin(x*.035+frameCount*.045)*3);vertex(stage.damX,stage.waterY);vertex(stage.damX,stage.ground);vertex(0,stage.ground);endShape(CLOSE);
  if(breach){fill(54,168,198,210);const t=constrain((millis()-phaseAt)/1500,0,1);beginShape();vertex(stage.damX-4,stage.waterY+stage.damH*.35);bezierVertex(stage.damX+width*.08,stage.waterY+stage.damH*.2,stage.damX+width*.18,stage.ground-20,width,stage.ground-5);vertex(width,stage.ground);vertex(stage.damX-5,stage.ground);endShape(CLOSE);if(t>0)for(let i=0;i<10;i++){fill(255,170);ellipse(stage.damX+((frameCount*5+i*91)%Math.max(30,width-stage.damX)),stage.ground-15-sin(i)*16,18+i%3*7,7)}}}
function drawPressure(){if(!showPressure||phase==="failed")return;const top=stage.waterY+18,bottom=stage.ground-16;for(let i=0;i<5;i++){const y=lerp(top,bottom,i/4),len=14+52*i/4*(1+load/DAMS[damKey].limit*.18);stroke(255,244,181,210);strokeWeight(2.5);line(stage.damX-len,y,stage.damX-8,y);line(stage.damX-8,y,stage.damX-17,y-6);line(stage.damX-8,y,stage.damX-17,y+6)}noStroke();fill(255,250,210);textSize(11);textStyle(BOLD);text("深いほど強い",stage.damX-92,bottom+18);textStyle(NORMAL)}
function stress(){return constrain(load/DAMS[damKey].limit,0,1.35)}
function drawDam(){const s=stress(),w=stage.damW,h=stage.damH,x=stage.damX,y=stage.ground,breaking=phase!=="calm";push();translate(x+(damKey==="gravity"?s*5:0),y);stroke("#243c40");strokeWeight(3);strokeJoin(ROUND);
  if(damKey==="gravity"){fill(DAMS.gravity.color);quad(-w*.18,-h,-w*.48,0,w*.42,0,w*.2,-h);drawConcreteLines(w,h);if(breaking)drawCrack(-w*.2,-h*.08-s*h*.18,s)}
  if(damKey==="fill"){fill("#9a805e");beginShape();vertex(-w*.27,-h*.93);vertex(-w*1.05,0);vertex(w*1.1,0);vertex(w*.28,-h*.93);endShape(CLOSE);drawFillStones(w,h);if(s>.45){noStroke();fill(70,151,162,120);ellipse(w*.7,-h*.16,18+s*24,7);stroke("#61513d");for(let i=0;i<floor(s*8);i++)line(w*(.55+i*.05),-h*(.12+i*.035),w*(.66+i*.05),-h*(.08+i*.02))}}
  if(damKey==="hollow"){fill(DAMS.hollow.color);quad(-w*.18,-h,-w*.48,0,w*.42,0,w*.2,-h);drawHollowDome(w,h,s,breaking)}
  if(damKey==="arch"){drawArchView(w,h,s,breaking)}drawDamEyes(w,h,s);pop()}
function drawConcreteLines(w,h){stroke(255,100);strokeWeight(1);for(let i=1;i<5;i++)line(-w*.35+i*3,-h*i/5,w*.3-i*2,-h*i/5)}
function drawFillStones(w,h){noStroke();fill("#77654c");for(let i=0;i<34;i++){const t=((i*47)%101)/100,y=-h*(.04+t*.82),half=lerp(w*.96,w*.25,t),x=(((i*73)%97)/96*2-1)*half;circle(x,y,3+(i*7)%7)}}
function drawHollowDome(w,h,s,breaking){const left=-w*.29,right=w*.28,base=-h*.055,top=-h*.68,lean=s*3;fill("#62777a");stroke("#243c40");strokeWeight(3);beginShape();vertex(left,base);vertex(left+lean,top+(right-left)*.5);bezierVertex(left+lean,top,right+lean,top,right+lean,top+(right-left)*.5);vertex(right,base);endShape(CLOSE);fill("#273f43");noStroke();beginShape();vertex(left+w*.1,base);vertex(left+w*.1+lean,top+(right-left)*.5);bezierVertex(left+w*.1+lean,top+w*.1,right-w*.1+lean,top+w*.1,right-w*.1+lean,top+(right-left)*.5);vertex(right-w*.1,base);endShape(CLOSE);if(breaking)drawCrack(lean,-h*.45,s)}
function drawArchView(w,h,s,breaking){fill(DAMS.arch.color);const bend=w*(.16+s*.08);beginShape();vertex(-w*.32,-h);bezierVertex(-w*.38+bend,-h*.68,-w*.45+bend,-h*.25,-w*.5,0);vertex(w*.44,0);bezierVertex(w*.38+bend,-h*.28,w*.31+bend,-h*.68,w*.18,-h);endShape(CLOSE);if(breaking)drawCrack(w*.08,-h*.5,s);
  for(let side of[-1,1]){for(let i=0;i<3;i++){const pulse=(frameCount*2+i*25)%70;stroke(255,222,106,210-pulse*2);strokeWeight(3);line(side*w*.08,-h*(.35+i*.16),side*(w*.46+pulse*.25),-h*(.35+i*.16))}}}
function drawDamEyes(w,h,s){const cy=-h*.58,spread=w*.11;noStroke();fill(255);stroke("#243c40");strokeWeight(2);for(let i=-1;i<=1;i++){const big=s>.88?1.35:1;ellipse(i*spread,cy,spread*.8*big,spread*1.05*big);fill("#243c40");const jitter=s>.72?sin(frameCount*.55+i)*3:0;circle(i*spread+jitter,cy,spread*.25);fill(255)}}
function drawCrack(x,y,s){if(s<.68)return;stroke("#3d4140");strokeWeight(2.5);noFill();const L=map(s,.68,1.2,12,90,true);beginShape();vertex(x,y);vertex(x+8,y+L*.22);vertex(x-3,y+L*.46);vertex(x+11,y+L*.7);vertex(x+4,y+L);endShape()}
function updateMarpans(){for(const m of marpans){if(phase==="breach"||phase==="failed"){m.vx+=.13;m.vy+=.05;m.x+=m.vx;m.y+=m.vy;m.rot+=m.vx*.025;if(m.y>stage.ground-10){m.y=stage.ground-10;m.vy*=-.45}}else{m.age++;if(m.age<35){m.y+=m.vy;m.vy+=.25}else{m.vy=lerp(m.vy,.35+.25*m.weight,.04);m.y=Math.min(stage.ground-m.size*.42,m.y+m.vy);m.x+=sin(frameCount*.025+m.seed)*.12}m.rot=sin(frameCount*.025+m.seed)*.06}m.actor.lookAt(mouseX,mouseY);push();translate(m.x,m.y);rotate(m.rot);m.actor.drawAt(0,0,{bodyWidth:m.size,bodyHeight:m.size*.7,bodyColor:m.weight>1?"#fff0c8":"#fffdf5",eyeScale:1+(stress()>.85?.18:0)});pop()}}
function drawEffects(){for(let i=drops.length-1;i>=0;i--){const d=drops[i];d.life-=.035;d.r+=2.5;noFill();stroke(255,255*d.life);strokeWeight(2);ellipse(d.x,d.y,d.r,d.r*.25);if(d.life<=0)drops.splice(i,1)}for(const d of debris){d.x+=d.vx;d.y+=d.vy;d.vy+=.18;push();translate(d.x,d.y);rotate(d.x*.03);fill(d.c);stroke("#263c3f");rect(-d.s/2,-d.s/2,d.s,d.s*.7);pop()}}
function addMarpan(x){if(phase!=="calm")return;initAudio();const giant=sizeChoice==="giant",large=sizeChoice==="large",weight=giant?DAMS[damKey].limit:large?1.8:1,size=giant?Math.min(112,width*.16):large?54:38;const m={x:constrain(x,size*.55,stage.damX-size*.6),y:stage.waterY-size*.8,size,weight,age:0,vy:giant?2.8:1.8,vx:0,rot:0,seed:random(20),actor:new Marpan25D({maxSize:size,autoBlink:true})};marpans.push(m);load+=weight;drops.push({x:m.x,y:stage.waterY,r:giant?22:8,life:1});tone(giant?110:260,giant?.18:.08,"sine",giant?.07:.045);setTimeout(()=>tone(giant?55:130,giant?.35:.16,"sine",giant?.04:.018),180);if(giant)document.getElementById("hint").textContent="巨大マーパンの重みが、一気に伝わった！";else if(load/DAMS[damKey].limit>.72){tone(58,.35,"sawtooth",.018);document.getElementById("hint").textContent=damKey==="fill"?"水がしみ込み、表面がこぼれはじめた…":"ダムが、きしみはじめた…"}}
function updateFailure(){if(phase==="calm"&&stress()>=1){phase="crack";phaseAt=millis();tone(95,.35,"square",.055);shake=2;document.getElementById("hint").textContent="亀裂が伸びている…"}else if(phase==="crack"&&millis()-phaseAt>950){phase="breach";phaseAt=millis();shake=8;noiseBurst(.8);for(let i=0;i<18;i++)debris.push({x:stage.damX+random(-stage.damW*.3,stage.damW*.4),y:stage.ground-random(10,stage.damH*.7),vx:random(1.5,6),vy:random(-3,1),s:random(7,22),c:DAMS[damKey].color});marpans.forEach(m=>{m.vx=random(2.5,6);m.vy=random(-2,1)})}else if(phase==="breach"&&millis()-phaseAt>1900){phase="failed";phaseAt=millis();document.getElementById("result").hidden=false}}
function mousePressed(){if(mouseX>=0&&mouseX<stage.damX-10&&mouseY>0&&mouseY<height)addMarpan(mouseX);return false}
function touchStarted(){if(touches.length&&touches[0].x<stage.damX-10)addMarpan(touches[0].x);return false}
function resizeToStage(){const host=document.getElementById("sketch"),box=host.parentElement.getBoundingClientRect(),w=Math.max(320,Math.floor(box.width)),h=Math.max(180,Math.floor(box.height));if(width!==w||height!==h)resizeCanvas(w,h)}
function windowResized(){resizeToStage()}
function initAudio(){if(muted)return;if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume()}
function tone(freq,dur,type="sine",vol=.03){if(muted)return;initAudio();if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,audioCtx.currentTime);g.gain.setValueAtTime(vol,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}
function noiseBurst(dur){if(muted)return;initAudio();const n=audioCtx.sampleRate*dur,b=audioCtx.createBuffer(1,n,audioCtx.sampleRate),a=b.getChannelData(0);for(let i=0;i<n;i++)a[i]=(Math.random()*2-1)*(1-i/n);const s=audioCtx.createBufferSource(),g=audioCtx.createGain();s.buffer=b;g.gain.value=.09;s.connect(g).connect(audioCtx.destination);s.start()}
