(() => {
  const canvas=document.querySelector('#scene'),ctx=canvas.getContext('2d');
  const waterButton=document.querySelector('#water'),message=document.querySelector('#message'),dustLabel=document.querySelector('#dustLabel');
  const W=1200,H=670,ground=568,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a);
  let scaleX=1,scaleY=1,last=performance.now(),time=0,water=false,shake=0;
  function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=r.width*d;canvas.height=r.height*d;scaleX=canvas.width/W;scaleY=canvas.height/H}
  Object.assign(window,{ctx,ground,clamp,rand,time});
  new ResizeObserver(resize).observe(canvas);resize();
  class Sound{
    constructor(){this.audio=null}
    wake(){this.audio??=new (window.AudioContext||window.webkitAudioContext)();this.audio.resume()}
    crack(size=1){if(!this.audio)return;const a=this.audio,n=Math.floor(1500*size),b=a.createBuffer(1,n,a.sampleRate),v=b.getChannelData(0);for(let i=0;i<n;i++)v[i]=(Math.random()*2-1)*Math.pow(1-i/n,2);const source=a.createBufferSource(),filter=a.createBiquadFilter(),gain=a.createGain();v[0]=1;source.buffer=b;filter.type='lowpass';filter.frequency.value=rand(350,900)/size;gain.gain.value=.22;source.connect(filter).connect(gain).connect(a.destination);source.start()}
    creak(){if(!this.audio)return;const a=this.audio,o=a.createOscillator(),g=a.createGain();o.type='sawtooth';o.frequency.setValueAtTime(110,a.currentTime);o.frequency.exponentialRampToValueAtTime(54,a.currentTime+.55);g.gain.setValueAtTime(.035,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.57);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.6)}
  }
  class Effects{
    constructor(){this.bits=[];this.dust=[];this.mist=[];this.haze=0}
    burst(x,y,count,big=false){for(let i=0;i<count;i++)this.bits.push({x,y,vx:rand(-120,120),vy:rand(-180,40),size:rand(big?5:2,big?14:7),life:rand(1.5,3.5),rot:rand(-2,2),material:'concrete'});for(let i=0;i<count*2;i++)this.dust.push({x,y,vx:rand(-65,65),vy:rand(-55,0),size:rand(12,35),life:rand(.7,2),alpha:rand(.12,.35)});this.haze=clamp(this.haze+count*(water?.0015:.009),0,.82)}
    update(dt,target){for(const b of this.bits){b.vy+=700*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;b.rot+=dt*2;if(b.y>ground-b.size){b.y=ground-b.size;b.vy*=-.19;b.vx*=.84}b.life-=dt}this.bits=this.bits.filter(b=>b.life>0);for(const d of this.dust){d.x+=d.vx*dt;d.y+=d.vy*dt;d.size+=dt*13;d.life-=dt*(water?2.8:1)}this.dust=this.dust.filter(d=>d.life>0);this.haze=Math.max(0,this.haze-dt*(water?.15:.012));if(water){for(let i=0;i<3;i++)this.mist.push({x:76,y:366,vx:(target.x-76)/rand(.7,1.1),vy:(target.y-366)/rand(.7,1.1)-rand(30,100),life:rand(.7,1.1)})}for(const m of this.mist){m.vy+=180*dt;m.x+=m.vx*dt;m.y+=m.vy*dt;m.life-=dt}this.mist=this.mist.filter(m=>m.life>0)}
    draw(){ctx.fillStyle='#8b8880';for(const b of this.bits){ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.rot);ctx.fillRect(-b.size/2,-b.size/2,b.size,b.size*.7);ctx.restore()}for(const d of this.dust){ctx.fillStyle=`rgba(167,163,151,${d.alpha*clamp(d.life,0,1)})`;ctx.beginPath();ctx.arc(d.x,d.y,d.size,0,7);ctx.fill()}ctx.fillStyle='rgba(235,242,237,.92)';for(const m of this.mist){ctx.beginPath();ctx.arc(m.x,m.y,2.5,0,7);ctx.fill()}ctx.fillStyle=`rgba(244,242,232,${this.haze*.8})`;ctx.fillRect(0,0,W,H)}
  }
  class Excavator{
    constructor(){this.base={x:958,y:550};this.tip={x:693,y:235};this.target={...this.tip};this.active=false;this.grip=0;this.current=null;this.cool=0;this.disabled=false;this.hitTime=0;this.nearby=null}
    update(dt,building,effects,sound){if(this.disabled){this.hitTime+=dt;this.active=false;this.target={x:753,y:530};}this.tip.x+=(this.target.x-this.tip.x)*Math.min(1,dt*9);this.tip.y+=(this.target.y-this.tip.y)*Math.min(1,dt*9);this.cool-=dt;const nearby=this.disabled?null:building.hit(this.tip.x,this.tip.y);this.nearby=nearby;const p=this.active&&!this.disabled?nearby:null;if(p!==this.current)this.grip=0;this.current=p;if(p){this.grip+=dt;if(this.grip>.23&&this.cool<=0){building.damage(p,p.kind==='wall'?.43:.35,effects,sound);this.cool=.26;shake=4}}else this.grip=0}
    draw(){const b=this.base,t=this.tip,elbow={x:850,y:290},joint={x:755+(t.x-700)*.15,y:175+(t.y-240)*.25};ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#354342';ctx.lineWidth=24;ctx.beginPath();ctx.moveTo(b.x-38,b.y-76);ctx.lineTo(elbow.x,elbow.y);ctx.lineTo(joint.x,joint.y);ctx.lineTo(t.x,t.y);ctx.stroke();ctx.strokeStyle='#e9aa55';ctx.lineWidth=17;ctx.stroke();ctx.strokeStyle='#66716d';ctx.lineWidth=9;ctx.beginPath();ctx.moveTo(b.x-54,b.y-80);ctx.lineTo(872,386);ctx.lineTo(joint.x,joint.y);ctx.stroke();ctx.fillStyle='#d98d49';ctx.strokeStyle='#354342';ctx.lineWidth=4;ctx.beginPath();ctx.roundRect(858,425,196,105,20);ctx.fill();ctx.stroke();ctx.fillStyle='#f3b569';ctx.beginPath();ctx.roundRect(924,390,105,90,13);ctx.fill();ctx.stroke();if(typeof marpanFaceCanvas!=='undefined'&&marpanFaceCanvas)ctx.drawImage(marpanFaceCanvas,931,397,87,77);ctx.fillStyle='#364241';ctx.beginPath();ctx.roundRect(842,514,226,42,20);ctx.fill();for(let x=868;x<1050;x+=37){ctx.fillStyle='#747d78';ctx.beginPath();ctx.arc(x,535,13,0,7);ctx.fill()}ctx.save();ctx.translate(t.x,t.y);ctx.rotate(Math.atan2(t.y-joint.y,t.x-joint.x));ctx.fillStyle='#53605b';ctx.strokeStyle='#303b38';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,-9);ctx.lineTo(-25,-31+(this.active?9:this.nearby?3:0));ctx.lineTo(12,-22);ctx.lineTo(30,-6);ctx.lineTo(12,0);ctx.closePath();ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(0,9);ctx.lineTo(-25,31-(this.active?9:this.nearby?3:0));ctx.lineTo(12,22);ctx.lineTo(30,6);ctx.lineTo(12,0);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}
  }
  const sound=new Sound(),effects=new Effects();let building=new Building(),excavator=new Excavator(),gameOver=false,accidentTimeout=null;const over=document.querySelector('#gameOver'),structureLabel=document.querySelector('#structureLabel');
  function pointer(e){const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*W,y=(e.clientY-r.top)/r.height*H;excavator.target={x:clamp(x,70,1080),y:clamp(y,85,ground-8)}}
  canvas.addEventListener('pointerdown',e=>{if(gameOver)return;sound.wake();canvas.setPointerCapture(e.pointerId);pointer(e);excavator.active=true});canvas.addEventListener('pointermove',e=>{if(excavator.active)pointer(e)});for(const type of ['pointerup','pointercancel'])canvas.addEventListener(type,()=>{excavator.active=false;excavator.current=null});
  waterButton.onclick=()=>{if(gameOver)return;water=!water;waterButton.setAttribute('aria-pressed',water);waterButton.textContent=`💧 散水 ${water?'ON':'OFF'}`;sound.wake()};function reset(){if(accidentTimeout)clearTimeout(accidentTimeout);accidentTimeout=null;building=new Building();effects.bits=[];effects.dust=[];effects.haze=0;excavator=new Excavator();gameOver=false;over.hidden=true;water=false;waterButton.setAttribute('aria-pressed','false');waterButton.textContent='💧 散水 OFF'}document.querySelector('#reset').onclick=reset;document.querySelector('#resetOver').onclick=reset;
  function background(){ctx.fillStyle='#dceeee';ctx.fillRect(0,0,W,H);ctx.fillStyle='#e8f2e9';for(let i=0;i<9;i++){ctx.beginPath();ctx.arc(i*170+40,ground+25,90,Math.PI,0);ctx.fill()}ctx.fillStyle='#dfd9c6';ctx.fillRect(0,ground,W,H-ground);ctx.strokeStyle='#a4a799';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,ground);ctx.lineTo(W,ground);ctx.stroke();ctx.fillStyle='#789a86';for(let i=0;i<3;i++){const x=70+i*1110;ctx.fillRect(x,409,7,159);ctx.fillRect(x-18,409,43,8)}}
  function hose(){ctx.strokeStyle='#427e99';ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(0,560);ctx.bezierCurveTo(10,480,55,500,78,365);ctx.stroke();ctx.fillStyle='#f4ae61';ctx.fillRect(59,352,37,22);ctx.fillStyle='#405d60';ctx.fillRect(88,356,18,13)}
  function frame(now){let dt=Math.min((now-last)/1000,.04);last=now;time+=dt;window.time=time;building.update(dt,effects,sound);if(building.impact&&!excavator.disabled){excavator.disabled=true;excavator.active=false;shake=17;sound.crack(2.2);sound.creak();accidentTimeout=setTimeout(()=>{gameOver=true;over.hidden=false},750)}excavator.update(dt,building,effects,sound);effects.update(dt,excavator.tip);shake=Math.max(0,shake-dt*25);ctx.setTransform(scaleX,0,0,scaleY,0,0);ctx.save();ctx.translate(rand(-shake,shake),rand(-shake,shake));background();hose();building.draw();effects.draw();excavator.draw();ctx.restore();message.textContent=building.complete?'解体完了':excavator.disabled?'崩落事故':building.phase==='pause'?'バキッ……':building.phase==='warning'?'ミシ…… 支えが限界に近い':building.phase==='falling'?'ガラガラガラ！':building.danger>.95?'柱に亀裂。下の支えに注意':effects.haze>.43?'粉塵で見えにくい！ 散水しよう':excavator.current?'バリバリ！ 押し続けて圧砕':'先端を部材に合わせて、押し続けて挟もう';dustLabel.textContent=`視界：${effects.haze>.47?'粉塵が濃い':effects.haze>.2?'少しかすむ':'良好'}`;structureLabel.textContent=`構造：${building.phase==='falling'||building.phase==='warning'||building.danger>1?'危険':building.danger>.9?'注意':'安定'}`;requestAnimationFrame(frame)}requestAnimationFrame(frame);
})();
