"use strict";
const COLORS=["#fffdf8","#faf4e8","#f4ead8","#fff8e9","#eee3d0"];
const SHAPES=[[.72,.72],[.9,.66],[1.13,.59],[.62,.92],[1.35,.62],[1.52,.88]];
let shelf,buns=[],dragging=null,dragDX=0,dragDY=0,audioCtx=null,shake=0,bendPulse=0,nextId=1,hint;

function setup(){const c=createCanvas(windowWidth,windowHeight);c.parent("sketch");pixelDensity(min(devicePixelRatio||1,2));hint=document.getElementById("hint");document.getElementById("reset").onclick=()=>{unlockAudio();resetWork()};buildShelf();resetWork()}
function buildShelf(){const sw=min(width*.68,760),top=max(34,height*.05),bottom=height<620?height*.76:height*.72;shelf={x:(width-sw)/2,y:top,w:sw,h:bottom-top,rows:height<590?3:4,post:max(18,sw*.045)};shelf.innerX=shelf.x+shelf.post;shelf.innerW=shelf.w-shelf.post*2;shelf.rowH=(shelf.h-shelf.post*.72)/shelf.rows}
function rowTop(r){return shelf.y+shelf.post*.35+r*shelf.rowH}function rowFloor(r){return shelf.y+shelf.post*.35+(r+1)*shelf.rowH-shelf.post*.25}function shelfLoad(r){return buns.filter(b=>b.stored&&b.row===r).reduce((n,b)=>n+b.baseW,0)/shelf.innerW}
function makeBun(x,y,i,scale=1){const base=constrain(min(width,height)*.068*scale,38,72),sh=SHAPES[i%SHAPES.length],bw=base*sh[0]*1.55,bh=base*sh[1]*1.22;return{id:nextId++,actor:new Marpan25D({maxSize:bw,bodyColor:COLORS[i%COLORS.length],autoBlink:true}),x,y,baseW:bw,baseH:bh,sx:1,sy:1,tx:1,ty:1,pressure:0,front:0,row:-1,stored:false,falling:false,vx:0,vy:0,rot:random(-.12,.12)}}
function resetWork(){buns=[];dragging=null;shake=0;bendPulse=0;hint.classList.remove("hidden");for(let r=0;r<shelf.rows;r++){const count=width<600?3:5,gap=shelf.innerW/(count+1);for(let i=0;i<count;i++){const b=makeBun(shelf.innerX+gap*(i+1),0,(r*2+i)%4,.82);b.stored=true;b.row=r;b.y=rowFloor(r)-b.baseH*.48;b.rot=0;buns.push(b)}}const loose=width<600?5:8;for(let i=0;i<loose;i++){const shape=(i+2)%SHAPES.length,side=i%2?-1:1;let x=width*.5+side*(shelf.w*.34+random(18,max(24,(width-shelf.w)*.22)));if(width<600)x=35+i*(width-70)/max(1,loose-1);const y=shelf.y+shelf.h+32+random(max(18,height-(shelf.y+shelf.h)-76));buns.push(makeBun(constrain(x,28,width-28),constrain(y,30,height-25),shape,shape===5?1.05:.92))}}
function unlockAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume()}
function sound(kind){unlockAudio();const now=audioCtx.currentTime,g=audioCtx.createGain(),o=audioCtx.createOscillator(),f=audioCtx.createBiquadFilter(),p={pon:[210,115,.15,"sine"],muni:[145,68,.23,"triangle"],gyu:[105,46,.3,"sawtooth"],mugyu:[82,32,.42,"square"],poto:[150,55,.2,"sine"]}[kind];o.type=p[3];o.frequency.setValueAtTime(p[0],now);o.frequency.exponentialRampToValueAtTime(p[1],now+p[2]);f.type="lowpass";f.frequency.value=kind==="mugyu"?380:650;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(kind==="poto"?.11:.075,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+p[2]);o.connect(f).connect(g).connect(audioCtx.destination);o.start();o.stop(now+p[2]+.03)}
function insert(b,x,y){const row=constrain(floor((y-(shelf.y+shelf.post*.35))/shelf.rowH),0,shelf.rows-1),load=shelfLoad(row);b.stored=true;b.falling=false;b.row=row;b.x=constrain(x,shelf.innerX-b.baseW*.12,shelf.innerX+shelf.innerW+b.baseW*.12);b.y=constrain(y,rowTop(row)+b.baseH*.3,rowFloor(row)-b.baseH*.22);b.vx=b.vy=0;b.rot=0;b.front=constrain((load-.48)*.9,0,.48);shake=max(shake,6+max(0,load-.5)*9);bendPulse=1.8;sound(load<.58?"muni":load<.78?"gyu":"mugyu");resolveRow(row,b,22);overflow(row,b,load);hint.classList.add("hidden")}
function resolveRow(row,focus,iterations=4){const list=buns.filter(b=>b.stored&&b.row===row);for(let k=0;k<iterations;k++)for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){const a=list[i],b=list[j],dx=b.x-a.x,dy=b.y-a.y,rx=(a.baseW*a.sx+b.baseW*b.sx)*.42,ry=(a.baseH*a.sy+b.baseH*b.sy)*.4,q=dx*dx/(rx*rx)+dy*dy/(ry*ry);if(q<1){const ov=1-sqrt(max(.001,q)),len=sqrt(dx*dx+dy*dy)||1,nx=dx/len,ny=dy/len,push=ov*min(rx,ry)*.36,aw=a===focus?.25:.5,bw=b===focus?.25:.5;a.x-=nx*push*aw;a.y-=ny*push*aw;b.x+=nx*push*bw;b.y+=ny*push*bw;a.pressure=max(a.pressure,ov);b.pressure=max(b.pressure,ov)}}const load=shelfLoad(row),sq=constrain((load-.72)/.75,0,.46);list.forEach(b=>{b.x=constrain(b.x,shelf.innerX-b.baseW*.18,shelf.innerX+shelf.innerW+b.baseW*.18);b.y=constrain(b.y,rowTop(row)+b.baseH*.17,rowFloor(row)-b.baseH*.15);b.tx=1-sq-constrain(b.pressure*.2,0,.16);b.ty=1+constrain(sq*.62+b.pressure*.22,0,.34);b.front=max(b.front,sq*.32)})}
function overflow(row,newB,load){const list=buns.filter(b=>b.stored&&b.row===row&&b!==newB);list.forEach(b=>b.front=constrain(b.front+.1+max(0,load-.5)*.16,0,.72));if(list.length){const edge=list.slice().sort((a,b)=>abs(b.x-(shelf.x+shelf.w/2))-abs(a.x-(shelf.x+shelf.w/2)))[0];setTimeout(()=>dropBun(edge),220)}}
function dropBun(b){if(!b.stored)return;b.stored=false;b.falling=true;b.row=-1;b.vx=(b.x<shelf.x+shelf.w/2?-1:1)*random(35,85);b.vy=45;b.front=0;sound("poto");shake=8}
function updatePhysics(){const dt=min(.033,deltaTime/1000);shake*=pow(.04,dt);bendPulse*=pow(.16,dt);buns.forEach(b=>{b.pressure*=pow(.14,dt);b.sx=lerp(b.sx,b.tx,min(1,dt*9));b.sy=lerp(b.sy,b.ty,min(1,dt*9));b.tx=lerp(b.tx,1,dt*.28);b.ty=lerp(b.ty,1,dt*.28);if(b.falling&&b!==dragging){b.vy+=720*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;b.rot+=b.vx*dt*.0025;const floorY=height-b.baseH*.3;if(b.y>floorY){b.y=floorY;b.vy*=-.24;b.vx*=.72;if(abs(b.vy)<25){b.falling=false;b.vy=0}}}});for(let r=0;r<shelf.rows;r++)if(shelfLoad(r)>.55)resolveRow(r,null,1)}
function draw(){updatePhysics();drawRoom();drawShelfBack();buns.filter(b=>b.stored).sort((a,b)=>a.front-b.front).forEach(drawBun);drawShelfFront();buns.filter(b=>!b.stored&&b!==dragging).forEach(drawBun);if(dragging)drawBun(dragging)}
function drawRoom(){const g=drawingContext.createLinearGradient(0,0,0,height);g.addColorStop(0,"#f2eadb");g.addColorStop(.7,"#e6dac4");g.addColorStop(1,"#cfc0a8");drawingContext.fillStyle=g;drawingContext.fillRect(0,0,width,height);noStroke();fill(101,76,51,18);rect(0,shelf.y+shelf.h+16,width,height);stroke(101,76,51,28);line(0,shelf.y+shelf.h+16,width,shelf.y+shelf.h+16)}
function drawShelfBack(){push();translate(random(-shake,shake),random(-shake,shake)*.4);noStroke();fill(47,27,13,42);rect(shelf.x+10,shelf.y+13,shelf.w,shelf.h+13,8);fill("#754829");rect(shelf.x,shelf.y,shelf.w,shelf.h,7);fill("#c69a66");rect(shelf.innerX,shelf.y+shelf.post*.35,shelf.innerW,shelf.h-shelf.post*.7);for(let r=0;r<shelf.rows;r++){const g=drawingContext.createLinearGradient(0,rowTop(r),0,rowFloor(r));g.addColorStop(0,"#a9794d");g.addColorStop(1,"#cba170");drawingContext.fillStyle=g;drawingContext.fillRect(shelf.innerX,rowTop(r),shelf.innerW,rowFloor(r)-rowTop(r))}pop()}
function drawShelfFront(){push();translate(random(-shake,shake),random(-shake,shake)*.4);noStroke();fill("#7d4d2a");rect(shelf.x,shelf.y,shelf.post,shelf.h);rect(shelf.x+shelf.w-shelf.post,shelf.y,shelf.post,shelf.h);rect(shelf.x,shelf.y,shelf.w,shelf.post*.48);for(let r=0;r<shelf.rows;r++){const bend=constrain((shelfLoad(r)-.68)*7+bendPulse*2,0,10),y=rowFloor(r);beginShape();vertex(shelf.x,y-2);quadraticVertex(shelf.x+shelf.w/2,y+bend,shelf.x+shelf.w,y-2);vertex(shelf.x+shelf.w,y+shelf.post*.34);quadraticVertex(shelf.x+shelf.w/2,y+shelf.post*.34+bend,shelf.x,y+shelf.post*.34);endShape(CLOSE)}pop()}
function drawBun(b){const bob=!b.stored&&!b.falling&&b!==dragging?sin(millis()*.002+b.id)*1.1:0;push();translate(b.x,b.y+bob);rotate(b.rot);const bulge=1+min(.2,b.front);scale(b.sx*bulge,b.sy*(1-min(.12,b.front*.32)));b.actor.lookAt(mouseX,mouseY);b.actor.drawAt(0,0,{bodyWidth:b.baseW,bodyHeight:b.baseH,bodyColor:b.actor.bodyColor,dentAmount:constrain(b.pressure*.9,0,.48),dentDirectionX:b.x<shelf.x+shelf.w/2?-1:1});pop()}
function pick(x,y){return buns.slice().reverse().find(b=>abs(x-b.x)<b.baseW*b.sx*.6&&abs(y-b.y)<b.baseH*b.sy*.65)}
function mousePressed(){unlockAudio();const b=pick(mouseX,mouseY);if(!b)return false;dragging=b;dragDX=mouseX-b.x;dragDY=mouseY-b.y;b.stored=false;b.falling=false;b.row=-1;b.sx=b.sy=b.tx=b.ty=1;b.vx=b.vy=0;return false}function mouseDragged(){if(!dragging)return;dragging.x=mouseX-dragDX;dragging.y=mouseY-dragDY;dragging.rot=lerp(dragging.rot,0,.24);return false}function mouseReleased(){if(!dragging)return false;const b=dragging;dragging=null;if(mouseX>shelf.x-shelf.post*.2&&mouseX<shelf.x+shelf.w+shelf.post*.2&&mouseY>shelf.y&&mouseY<shelf.y+shelf.h)insert(b,mouseX-dragDX,mouseY-dragDY);else{b.falling=true;b.vy=40}return false}function touchStarted(){return mousePressed()}function touchMoved(){mouseDragged();return false}function touchEnded(){return mouseReleased()}function windowResized(){resizeCanvas(windowWidth,windowHeight);buildShelf();resetWork()}
