const PITCHES={C4:261.63,D4:293.66,E4:329.63,F4:349.23,G4:392,A4:440,B4:493.88,C5:523.25};
const NOTE_COLORS={C4:"#e87567",D4:"#e89b54",E4:"#e4c34f",F4:"#8fc36e",G4:"#61adbd",A4:"#778dca",B4:"#a184bd",C5:"#e66f86"};
const SONGS=[
 {id:"free",title:"フリービート",price:0,bpm:96,notes:[],unlocked:true},
 {id:"twinkle",title:"きらきら星",price:180,bpm:100,notes:["C4","C4","G4","G4","A4","A4","G4","F4","F4","E4","E4","D4","D4","C4"]},
 {id:"hands",title:"むすんでひらいて",price:550,bpm:100,notes:["E4","E4","D4","C4","C4","D4","D4","E4","D4","C4","G4","G4","F4","E4","E4","D4","C4","D4","E4","C4"]},
 {id:"mary",title:"メリーさんのひつじ",price:1200,bpm:116,notes:["E4","D4","C4","D4","E4","E4","E4","D4","D4","D4","E4","G4","G4","E4","D4","C4","D4","E4","E4","E4","E4","D4","D4","E4","D4","C4"]},
 {id:"butterfly",title:"ちょうちょう",price:2600,bpm:108,notes:["G4","E4","E4","F4","D4","D4","C4","D4","E4","F4","G4","G4","G4","G4","E4","E4","E4","F4","D4","D4","D4","C4","E4","G4","G4","C4","C4","C4"]},
 {id:"frog",title:"かえるのうた",price:5200,bpm:120,notes:["C4","D4","E4","F4","E4","D4","C4","E4","F4","G4","A4","G4","F4","E4","C4","C4","C4","C4","C4","C4","D4","D4","E4","E4","F4","F4","E4","D4","C4"]},
 {id:"buzz",title:"ぶんぶんぶん",price:11000,bpm:120,notes:["G4","F4","E4","D4","E4","F4","D4","C4","E4","F4","G4","E4","D4","E4","F4","D4","E4","F4","G4","E4","D4","E4","F4","D4","G4","F4","E4","D4","E4","F4","D4","C4"]},
 {id:"tulip",title:"チューリップ",price:23000,bpm:112,notes:["C4","D4","E4","C4","D4","E4","G4","E4","D4","C4","D4","E4","D4","C4","D4","E4","C4","D4","E4","G4","E4","D4","C4","D4","E4","C4","G4","G4","E4","G4","A4","A4","G4","E4","E4","D4","D4","C4"]},
 {id:"chestnut",title:"大きな栗の木の下で",price:48000,bpm:104,notes:["C4","C4","D4","E4","E4","G4","E4","E4","D4","D4","C4","E4","E4","F4","G4","C5","A4","C5","G4","C5","C5","B4","G4","A4","A4","A4","A4","G4","C4","C4","D4","E4","E4","G4","E4","E4","D4","D4","C4"]}
];
const UPGRADES=[
 {id:"metronome",icon:"♩",name:"メトロノーム",description:"拍ごとに音符を生み出す",baseCost:25,passive:1},
 {id:"speaker",icon:"◉",name:"スピーカー",description:"1回のタップに +1音符",baseCost:80,click:1},
 {id:"choir",icon:"♫",name:"マーパン合唱団",description:"毎秒4音符。仲間が舞台に登場",baseCost:160,passive:4}
];
const EN_SONGS={free:"Free Beat",twinkle:"Twinkle, Twinkle, Little Star",hands:"Close Your Hands, Open Your Hands",mary:"Mary Had a Little Lamb",butterfly:"Butterfly",frog:"The Frog Song",buzz:"Buzz, Buzz, Buzz",tulip:"Tulips",chestnut:"Under the Spreading Chestnut Tree"};
const EN_UPGRADES={
 metronome:{name:"Metronome",description:"Produces notes on every beat"},
 speaker:{name:"Speaker",description:"Adds +1 note to every tap"},
 choir:{name:"Marpan Choir",description:"Produces 4 notes per second and adds friends to the stage"}
};
const UI_TEXT={
 ja:{pageTitle:"マーパン・ビートクリッカー",soundOff:"タップで音声開始",soundOn:"音声 ON",scoreLabel:"音符",chooseMusic:"曲を選ぶ",hint:"マーパンを叩いて音符を集めよう。拍に合うほどボーナス！",shopTitle:"演奏会場を育てる",libraryTitle:"曲を集める",perSecond:"毎秒",howtoBeat:"ポン、ポン、ポン",howto:"リズムに乗るほどマーパンたちの演奏が育ちます。",playing:"演奏中",select:"選択",unlock:"解放",available:"いつでも演奏OK",notEnough:"音符が足りません",choir:"合唱団",unlocked:"解放！"},
 en:{pageTitle:"Marpan Beat Clicker",soundOff:"Tap to enable sound",soundOn:"Sound ON",scoreLabel:"Notes",chooseMusic:"Choose Music",hint:"Tap Marpan to collect notes. Keep the beat for bigger bonuses!",shopTitle:"Grow the Stage",libraryTitle:"Collect Songs",perSecond:"per sec.",howtoBeat:"Tap, tap, tap",howto:"The better your rhythm, the bigger the Marpans’ performance grows.",playing:"Playing",select:"Select",unlock:"Unlock",available:"Always available",notEnough:"Not enough notes",choir:"Choir",unlocked:"unlocked!"}
};
let language="ja";
let score=0,combo=0,fever=0,feverUntil=0,upgrades={},particles=[],popScale=1,popVelocity=0,lastBeat=-1,nextPassive=0,audioReady=false,audioStart=0,currentSong=SONGS[0],melodyNote=-1,melodyPulse=0,marpan,choir=[],drumstick,lastTapAt=-999;

function preload(){drumstick=loadSound("drumstick-count.mp3",()=>{},()=>{drumstick=null;});}
function setup(){const canvas=createCanvas(900,650);canvas.parent("canvas-wrap");pixelDensity(1);textFont('"Avenir Next","Yu Gothic",sans-serif');marpan=new Marpan25D({maxSize:420,bodyColor:"#fffdf4"});marpan.enableAutoBlink(2600,4800);choir=Object.keys(NOTE_COLORS).map((note,i)=>{const m=new Marpan25D({maxSize:48,bodyColor:NOTE_COLORS[note],eyeScale:.72});m.enableAutoBlink(1800+i*170,3400+i*190);return m;});UPGRADES.forEach(item=>upgrades[item.id]=0);setupShop();setupMusic();document.querySelector("#music-button").addEventListener("click",()=>document.querySelector("#music-shop").scrollIntoView({behavior:"smooth",block:"center"}));document.querySelector("#language-button").addEventListener("click",()=>{language=language==="ja"?"en":"ja";applyLanguage();});applyLanguage();resizeCanvasForViewport();nextPassive=millis()+1000;}
function draw(){const beat=beatPosition();if(beat.index!==lastBeat){lastBeat=beat.index;playBeat(beat.index);}if(millis()>=nextPassive){collectPassive();nextPassive=millis()+1000;}updatePhysics();drawScene(beat.phase);drawParticles();}
function beatPosition(){const beatMs=60000/currentSong.bpm,elapsed=max(0,millis()-(audioReady?audioStart:0));return{index:floor(elapsed/beatMs),phase:(elapsed%beatMs)/beatMs};}
function playBeat(index){if(!audioReady)return;const note=currentSong.notes.length?currentSong.notes[index%currentSong.notes.length]:null;if(note){melodyNote=index%currentSong.notes.length;melodyPulse=1;playTone(PITCHES[note],.09,.18);}else if(index%4===0)playTone(130.81,.045,.06);}
function drawScene(phase){const feverMode=millis()<feverUntil,pulse=pow(max(0,1-phase),3);background(feverMode?"#f7c9a0":"#f9e8c9");drawStageBackdrop(pulse,feverMode);drawVenue(phase,feverMode);const size=min(width*.58,385),bounce=sin(phase*TWO_PI)*6+pulse*(feverMode?22:10);marpan.setPosition(width*.5,height*.5+bounce);marpan.lookAt(mouseX,mouseY);marpan.drawAt(width*.5,height*.5+bounce,{bodyWidth:size*popScale,bodyHeight:size*.7/popScale});if(feverMode){fill("#8e4d3b");noStroke();textAlign(CENTER,CENTER);textStyle(BOLD);textSize(27);text("MARPAN FEVER!",width*.5,height*.14+sin(frameCount*.1)*4);textStyle(NORMAL);}melodyPulse*=.86;}
function drawStageBackdrop(pulse,feverMode){noStroke();for(let i=0;i<12;i++){fill(feverMode?"#fff0b8":"#f1d5a7");circle((i*107+frameCount*.25)%width,64+sin(frameCount*.01+i)*18,8+pulse*8);}fill("#f4dba9");ellipse(width*.5,height*.52,min(width*.8,520)+pulse*18,min(width*.57,370)+pulse*18);stroke("#d9b887");strokeWeight(3);line(width*.12,height*.83,width*.88,height*.83);}
function drawVenue(phase,feverMode){if(upgrades.metronome)drawMetronome(width*.16,height*.43,phase,feverMode);if(upgrades.speaker){drawSpeaker(width*.82,height*.5,feverMode);if(upgrades.speaker>4)drawSpeaker(width*.18,height*.64,feverMode);}const count=min(8,upgrades.choir);for(let i=0;i<count;i++){const x=width*(.27+i*.066),y=height*.78+sin(frameCount*.035+i)*3,note=Object.keys(NOTE_COLORS)[i],active=currentSong.notes[melodyNote]===note?melodyPulse:0;const m=choir[i];m.setPosition(x,y-active*9);m.lookAt(width*.5,height*.45);m.drawAt(x,y-active*9,{bodyWidth:42*(1+active*.18),bodyHeight:30*(1+active*.18)});}if(upgrades.choir)labelCount(width*.5,height*.85,t("choir")+" ×"+upgrades.choir);}
function drawMetronome(x,y,phase,feverMode){push();translate(x,y);stroke("#8e6347");strokeWeight(4);fill("#d48b5d");triangle(-24,30,24,30,17,-28);strokeWeight(3);line(0,5,sin(phase*TWO_PI)*(feverMode?17:11),-25);fill("#f4c84b");noStroke();circle(sin(phase*TWO_PI)*(feverMode?17:11),-25,8);pop();labelCount(x+31,y-30,"×"+upgrades.metronome);}
function drawSpeaker(x,y,feverMode){push();translate(x,y);scale((feverMode?1.02:1)+melodyPulse*.07);fill("#6ea9c5");stroke("#3f7286");strokeWeight(3);rect(-28,-30,56,60,6);fill("#f7e9cf");circle(0,-7,27);circle(0,20,12);pop();labelCount(x,y-43,"×"+upgrades.speaker);}
function labelCount(x,y,value){fill("#80624e");noStroke();textAlign(CENTER,CENTER);textStyle(BOLD);textSize(11);text(value,x,y);textStyle(NORMAL);}
function updatePhysics(){popVelocity+=(1-popScale)*.25;popScale+=popVelocity;popVelocity*=.72;particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.08;p.life--;});particles=particles.filter(p=>p.life>0);}
function mousePressed(){if(millis()-lastTapAt<80)return false;if(mouseX>=0&&mouseX<=width&&mouseY>=height*.18&&mouseY<=height*.86){lastTapAt=millis();tapMarpan();}return false;}function touchStarted(){return mousePressed();}
function tapMarpan(){ensureAudio();playDrumstick();const beatMs=60000/currentSong.bpm,position=(millis()-audioStart)%beatMs,near=min(position,beatMs-position);let judgement="NORMAL",base=1;if(near<=90){judgement="JUST";base=4;combo++;fever+=currentSong.notes.length?3:2;}else if(near<=185){judgement="GOOD";base=2;combo++;fever+=currentSong.notes.length?1:0;}else{combo=0;fever=max(0,fever-1);}const gain=round((base+upgrades.speaker)*(1+min(2,floor(combo/5)*.25))*(millis()<feverUntil?3:1));score+=gain;popScale=.78;popVelocity=-.12;showToast(judgement+"! ♪+"+gain);burst(judgement,gain);if(fever>=100&&millis()>=feverUntil){fever=0;feverUntil=millis()+12000;showToast("MARPAN FEVER!");}syncUI();}
function ensureAudio(){if(audioReady)return;userStartAudio();audioReady=true;audioStart=millis();document.querySelector("#sound-label").textContent=t("soundOn");}
function playDrumstick(){if(drumstick&&drumstick.isLoaded()){drumstick.stop();drumstick.play(0,1,.8,.04,.14);}else playTone(950,.035,.035);}
function playTone(frequency,volume,duration){if(!audioReady)return;const oscillator=new p5.Oscillator("sine");oscillator.freq(frequency);oscillator.amp(0);oscillator.start();oscillator.amp(volume,.008);oscillator.amp(0,duration*.75);oscillator.stop(duration);}
function burst(judgement,gain){for(let i=0;i<(judgement==="JUST"?12:5);i++)particles.push({x:width*.5,y:height*.51,vx:random(-4,4),vy:random(-6,-2),life:45+random(25),label:i%2?"♪":"+"+gain,color:judgement==="JUST"?"#e4685d":"#d79542"});}
function drawParticles(){textAlign(CENTER,CENTER);textStyle(BOLD);for(const p of particles){fill(p.color);noStroke();textSize(p.label==="♪"?22:14);text(p.label,p.x,p.y);}textStyle(NORMAL);}
function collectPassive(){const rate=UPGRADES.reduce((sum,item)=>sum+(upgrades[item.id]||0)*(item.passive||0),0);if(rate){score+=rate*(millis()<feverUntil?3:1);syncUI();}}
function setupShop(){const shop=document.querySelector("#shop");UPGRADES.forEach(item=>{const article=document.createElement("article");article.className="upgrade";article.dataset.upgrade=item.id;article.innerHTML='<div class="upgrade-icon">'+item.icon+'</div><div><h3><span class="upgrade-name"></span> <span class="owned" data-owned="'+item.id+'">×0</span></h3><p class="upgrade-description"></p></div><button class="buy" data-id="'+item.id+'"></button>';article.querySelector("button").addEventListener("click",()=>buyUpgrade(item.id));shop.append(article);});}
function setupMusic(){const list=document.querySelector("#music-list");SONGS.forEach((song,index)=>{song.unlocked=song.unlocked||song.price===0;const item=document.createElement("article");item.className="music-item";item.dataset.music=song.id;item.innerHTML='<div><b></b><small></small></div><button data-song="'+song.id+'"></button>';item.querySelector("button").addEventListener("click",()=>selectSong(index));list.append(item);});syncUI();}
function cost(item){return floor(item.baseCost*pow(1.16,upgrades[item.id]));}
function buyUpgrade(id){const item=UPGRADES.find(v=>v.id===id),price=cost(item);if(score<price){showToast(t("notEnough"));return;}ensureAudio();score-=price;upgrades[id]++;showToast(upgradeName(item)+" ×"+upgrades[id]);syncUI();}
function selectSong(index){const song=SONGS[index];if(!song.unlocked){if(score<song.price){showToast(t("notEnough"));return;}score-=song.price;song.unlocked=true;showToast(songTitle(song)+" "+t("unlocked"));}currentSong=song;lastBeat=-1;melodyNote=-1;if(audioReady)audioStart=millis();document.querySelector("#bpm-label").textContent="♩ "+song.bpm+" BPM";syncUI();}
function t(key){return UI_TEXT[language][key];}function songTitle(song){return language==="en"?(EN_SONGS[song.id]||song.title):song.title;}function upgradeName(item){return language==="en"?EN_UPGRADES[item.id].name:item.name;}function upgradeDescription(item){return language==="en"?EN_UPGRADES[item.id].description:item.description;}
function applyLanguage(){document.documentElement.lang=language;document.title=t("pageTitle");document.querySelector("#page-title").textContent=t("pageTitle");document.querySelector("#score-label").textContent=t("scoreLabel");document.querySelector("#music-button").textContent=t("chooseMusic");document.querySelector("#game-hint").textContent=t("hint");document.querySelector("#shop-title").textContent=t("shopTitle");document.querySelector("#library-title").textContent=t("libraryTitle");document.querySelector("#howto-beat").textContent=t("howtoBeat");document.querySelector("#howto-text").textContent=t("howto");document.querySelector("#sound-label").textContent=audioReady?t("soundOn"):t("soundOff");const button=document.querySelector("#language-button");button.textContent=language==="ja"?"EN":"日本語";button.setAttribute("aria-label",language==="ja"?"Switch to English":"日本語に切り替える");UPGRADES.forEach(item=>{const card=document.querySelector('[data-upgrade="'+item.id+'"]');card.querySelector(".upgrade-name").textContent=upgradeName(item);card.querySelector(".upgrade-description").textContent=upgradeDescription(item);});SONGS.forEach(song=>{const card=document.querySelector('[data-music="'+song.id+'"]');card.querySelector("b").textContent=songTitle(song);card.querySelector("small").textContent=song.bpm+" BPM / "+(song.price?t("unlock")+" ♪"+song.price:t("available"));});syncUI();}
function syncUI(){document.querySelector("#score").textContent="♪ "+floor(score).toLocaleString(language==="ja"?"ja-JP":"en-US");document.querySelector("#combo").textContent=combo+" COMBO";document.querySelector("#fever-text").textContent=floor(min(100,fever))+" / 100";document.querySelector("#fever-fill").style.width=min(100,fever)+"%";document.querySelector("#rate-label").textContent=t("perSecond")+" ♪"+UPGRADES.reduce((sum,item)=>sum+(upgrades[item.id]||0)*(item.passive||0),0);document.querySelector("#song-title").textContent=songTitle(currentSong);UPGRADES.forEach(item=>{const button=document.querySelector('[data-id="'+item.id+'"]'),owned=document.querySelector('[data-owned="'+item.id+'"]');button.textContent="♪ "+cost(item);button.disabled=score<cost(item);owned.textContent="×"+upgrades[item.id];});SONGS.forEach(song=>{const button=document.querySelector('[data-song="'+song.id+'"]');button.textContent=song.id===currentSong.id?t("playing"):song.unlocked?t("select"):"♪ "+song.price;button.disabled=!song.unlocked&&score<song.price;button.parentElement.classList.toggle("is-active",song.id===currentSong.id);});}
let toastTimer;function showToast(message){const toast=document.querySelector("#toast");toast.textContent=message;toast.classList.remove("show");void toast.offsetWidth;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),650);}
function windowResized(){resizeCanvasForViewport();}function resizeCanvasForViewport(){resizeCanvas(900,windowWidth<760?600:650);}
