const NOTE_NAMES = ["ド", "レ", "ミ", "ファ", "ソ", "ラ", "シ", "ド"]; const FREQUENCIES = [261.63, 293.66, 329.63, 349.23, 392, 440, 493.88, 523.25];
const NOTE_COLORS = ["#e87567", "#e6a24e", "#d5bd4b", "#77b66e", "#55a5a8", "#6f91c1", "#9c7ac0"]; const STAGES = ["微生物世界", "水中世界", "草むら", "動物世界", "人間世界", "街", "巨大生物", "山", "惑星", "宇宙"]; const SAVE_KEY = "eating-notes-save-v1";
let marpan, state, particles = [], rests = [], feed = null, mic, fft, micOn = false, audioReady = false, lastSave = 0, toastTimer, previousStage = 0, lastMoodTick = 0, nextMessageAt = 0, message = null, nextBgmAt = 0, bgmIndex = 0, playPulse = 0;
const TWINKLE = [0, 0, 4, 4, 5, 5, 4, 3, 3, 2, 2, 1, 1, 0];
function defaultState() { return { bornAt: Date.now(), lastPlayedAt: Date.now(), growth: 0, total: 0, micTotal: 0, manualTotal: 0, notes: [0,0,0,0,0,0,0], hunger: 42, mood: 72, clean: 100, history: [] }; }
function setup() { createCanvas(900, 610).parent("canvas-wrap"); pixelDensity(1); textFont('"Avenir Next", "Yu Gothic", sans-serif'); state = loadState(); previousStage = getStage(); lastMoodTick = Date.now(); nextMessageAt = millis() + random(9000, 16000); marpan = new Marpan25D({ maxSize: 410, bodyColor: "#f9fff6" }); marpan.enableAutoBlink(2300, 4300); makeNoteButtons(); makeLegend(); setupDOM(); syncUI(); }
function loadState() { try { const saved = JSON.parse(localStorage.getItem(SAVE_KEY)); return saved ? { ...defaultState(), ...saved } : defaultState(); } catch (error) { return defaultState(); } }
function saveState() { state.lastPlayedAt = Date.now(); localStorage.setItem(SAVE_KEY, JSON.stringify(state)); lastSave = millis(); }
function draw() { updateGame(); drawWorld(); drawParticles(); if (millis() - lastSave > 3000) saveState(); }
function updateGame() { for (const item of particles) { item.x += item.vx; item.y += item.vy; item.vy += .04; item.life--; } particles = particles.filter((item) => item.life > 0); if (feed) { feed.progress += .035; feed.x = lerp(feed.startX, width * .5, min(1, feed.progress)); feed.y = lerp(feed.startY, height * .52, min(1, feed.progress)) - sin(min(1, feed.progress) * PI) * 65; if (feed.progress >= 1) finishFeed(); } if (Date.now() - lastMoodTick > 12000) { state.mood = max(0, state.mood - 1); state.hunger = max(0, state.hunger - 1); lastMoodTick = Date.now(); syncUI(); } if (millis() > nextMessageAt && !message && !feed) { createMessage(); nextMessageAt = millis() + random(16000, 28000); } if (audioReady && millis() > nextBgmAt) playBgmNote(); if (frameCount % 720 === 0 && state.total > 0) { rests.push({ x:random(width*.18, width*.82), y:random(height*.16, height*.78), wobble:random(TWO_PI), spin:random(-.02,.02) }); state.clean = max(0, state.clean - 3); syncUI(); } }
function drawWorld() { const stage = getStage(); const scale = min(1.8, 1 + state.growth / 120); const pulse = sin(frameCount * .06) * (state.mood < 30 ? .8 : 2) + playPulse; if (stage > previousStage) { showToast("世界が小さくなった！"); previousStage = stage; } drawHabitat(stage); drawComparison(stage, scale); const bodyW = min(width * .48, 320 + scale * 20); const bodyH = bodyW * .68; const cx = width*.5; const cy = height*.53 + pulse; const bodyColor = mixedColor(); marpan.setPosition(cx, cy); marpan.lookAt(mouseX, mouseY); marpan.setBodyColor(bodyColor); marpan.setExpression(feed ? "happy" : state.mood < 30 ? "worried" : "pupil"); marpan.drawAt(cx, cy, { bodyWidth:bodyW, bodyHeight:bodyH, scaleX:1 + (feed ? sin(frameCount*.35)*.05 : 0), scaleY:1 - (feed ? abs(sin(frameCount*.35))*.04 : 0) }); drawFeed(); drawRests(); drawMessage(); drawStageLabel(stage, scale); playPulse *= .86; }
function drawHabitat(stage) { background(stageBackground(stage)); drawStars(stage); noStroke(); fill(stage === 1 ? "#9dd5d0" : "#c9e7d9"); ellipse(width*.5,height*.53,width*.9,height*.66); stroke("#8ebeb4"); strokeWeight(3); noFill(); rect(10,10,width-20,height-20,18); noStroke(); if (stage === 1) drawWaterLife(); }
function stageBackground(stage) { return ["#dff0ea","#cde9e7","#e6efd2","#f4eacb","#efe4d5","#e5ddd2","#d9dce7","#cbd5dd","#cbd9eb","#1e3346"][stage]; }
function drawStars(stage) { noStroke(); for (let i=0;i<18;i++) { const x=(i*83+frameCount*(stage>7?.05:.18))%width; const y=32+(i*47)%height; fill(stage>8?"#f6e8a9":stage>4?"#c2b39e":"#a9d8c9"); ellipse(x,y,stage>8?3:5,stage>8?3:5); } }
function drawComparison(stage, scale) { if (stage === 1) return; const labels = [["細胞","・","・"],["","",""] , ["草","虫","石"],["鳥","猫","魚"],["椅子","人","自転車"],["家","車","街灯"],["ビル","車","塔"],["山","雲","鳥"],["月","地球","衛星"],["惑星","星","銀河"]][stage]; textAlign(CENTER,CENTER); textStyle(BOLD); textSize(min(24,width*.035)); fill(stage>8?"#f4e9c6":"#6e8881"); labels.forEach((label,index)=>{ if(label) text(label,width*(.18+index*.32)+sin(frameCount*.01+index)*8,height*(.25+.19*(index%2))+cos(frameCount*.012+index)*6); }); textStyle(NORMAL); }
function drawWaterLife() { noStroke(); fill("#bce9e4"); for (let i=0;i<12;i++) ellipse((i*97+frameCount*.22)%width, 40+(i*53)%height, 7+i%3*3, 7+i%3*3); stroke("#579d98"); strokeWeight(4); for (let i=0;i<6;i++) { const x=55+i*155; line(x,height*.82,x+sin(frameCount*.025+i)*12,height*.45); line(x+12,height*.82,x+22+sin(frameCount*.025+i)*10,height*.57); } noStroke(); for (let i=0;i<3;i++) drawFish(100+i*330,height*(.27+.18*(i%2)),1+i*.15); }
function drawFish(x,y,fishScale) { push(); translate(x+sin(frameCount*.012+x)*18,y); scale(fishScale); fill("#5a9ea5"); ellipse(0,0,58,30); triangle(-25,0,-48,-18,-48,18); fill("#f7f3df"); ellipse(17,-5,7,7); fill("#20343a"); ellipse(18,-5,3,3); pop(); }
function drawStageLabel(stage, scale) { noStroke(); fill(stage>8?"#f5e9c4":"#547871"); textAlign(LEFT,TOP); textSize(12); text(`世界 ${stage+1} / 10  ・  成長 ${floor(state.growth)}%`,18,16); }
function drawFeed() { if (!feed) return; push(); translate(feed.x, feed.y); rotate(sin(frameCount*.12)*.15); noStroke(); fill(NOTE_COLORS[feed.index]); ellipse(0,0,38,38); fill("#fffdf6"); textAlign(CENTER,CENTER); textStyle(BOLD); textSize(22); text("♪",0,-1); pop(); }
function drawRests() { textAlign(CENTER,CENTER); textSize(46); rests.forEach((rest)=>{ push(); translate(rest.x,rest.y+sin(frameCount*.04+rest.wobble)*5); rotate(frameCount*rest.spin); fill("#557d78"); text("𝄽",0,0); pop(); }); }
function drawMessage() { if (!message) return; const bubbleX=width*.68,bubbleY=height*.18; push(); stroke("#6e9c90"); strokeWeight(2); fill("#fffdf4"); rect(bubbleX-125,bubbleY-28,250,56,12); noStroke(); triangle(bubbleX-15,bubbleY+28,bubbleX+4,bubbleY+28,bubbleX-10,bubbleY+43); fill("#355e59"); textAlign(CENTER,CENTER); textSize(15); text(message.text,bubbleX,bubbleY); pop(); }
function mixedColor() { let total = state.notes.reduce((sum,value)=>sum+value,0); if (!total) return "#f9fff6"; let red=0,green=0,blue=0; state.notes.forEach((count,index)=>{ const color = colorFromHex(NOTE_COLORS[index]); red += color[0]*count; green += color[1]*count; blue += color[2]*count; }); return `rgb(${floor(red/total)},${floor(green/total)},${floor(blue/total)})`; }
function colorFromHex(hex) { return [parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)]; }
function feedNote(index, source="手動") { if (feed || state.hunger >= 100) { showToast("もうたべられないよ"); return; } ensureAudio(); const pitch = FREQUENCIES[index]; tone(pitch,.18,.28); state.notes[index % 7]++; state.total++; source === "マイク" ? state.micTotal++ : state.manualTotal++; state.hunger = min(100,state.hunger+4); state.mood = min(100,state.mood+3); if (message && message.note === index % 7) { state.mood = min(100,state.mood+15); playPulse = -16; burstSparkles(width*.5,height*.5); showToast("それ！うれしい！"); message = null; } state.growth += .9; state.history.push({ note:NOTE_NAMES[index % 7], pitch, volume:source === "マイク" ? .6 : .4, duration:.28, source, at:Date.now() }); state.history = state.history.slice(-120); feed = { index:index%7, label:NOTE_NAMES[index], source, progress:0, startX:width*.5, startY:height*.96 }; for (let i=0;i<10;i++) particles.push({x:feed.startX+random(-25,25),y:feed.startY, vx:random(-2,2),vy:random(-4,-1),life:45+random(25),color:NOTE_COLORS[index%7],label:i%2?"♪":NOTE_NAMES[index]}); document.querySelectorAll(".note-button")[index].classList.add("is-pressed"); setTimeout(()=>document.querySelectorAll(".note-button")[index].classList.remove("is-pressed"),140); syncUI(); }
function finishFeed() { const label = feed.label; feed = null; marpan.bounce(1); showToast(`${label}をみつけた！`); saveState(); }
function ensureAudio() { if (audioReady) return; userStartAudio(); audioReady = true; nextBgmAt = millis() + 500; }
function tone(frequency, volume, duration) { if (!audioReady) return; const oscillator = new p5.Oscillator("sine"); oscillator.freq(frequency); oscillator.amp(volume); oscillator.start(); oscillator.stop(duration); }
function playBgmNote() { const cleanFactor = state.clean / 100; nextBgmAt = millis() + 520; if (random() > cleanFactor) { bgmIndex = (bgmIndex + 1) % TWINKLE.length; return; } tone(FREQUENCIES[TWINKLE[bgmIndex]], .035 * cleanFactor, .22); bgmIndex = (bgmIndex + 1) % TWINKLE.length; }
function getStage() { return min(STAGES.length-1, floor(state.growth / 12)); }
function makeNoteButtons() { const container=document.querySelector("#note-buttons"); NOTE_NAMES.forEach((name,index)=>{ const button=document.createElement("button"); button.type="button"; button.className="note-button"; button.textContent=name; button.setAttribute("aria-label",`${name}の鍵盤`); button.style.setProperty("--note-color",NOTE_COLORS[index%7]); button.addEventListener("click",()=>feedNote(index)); container.append(button); }); }
function makeLegend() { const container=document.querySelector("#note-legend"); NOTE_NAMES.slice(0,7).forEach((name,index)=>{ const row=document.createElement("div"); row.className="legend-row"; row.innerHTML=`<i class="legend-dot" style="background:${NOTE_COLORS[index]}"></i><span>${name}</span><div class="legend-track"><i data-bar="${index}" style="width:0;background:${NOTE_COLORS[index]}"></i></div><b data-count="${index}">0</b>`; container.append(row); }); }
function syncUI() { const stage=getStage(); const latest=state.history[state.history.length-1]; document.querySelector("#stage-label").textContent=STAGES[stage]; document.querySelector("#hunger").textContent=floor(state.hunger); document.querySelector("#mood").textContent=floor(state.mood); document.querySelector("#clean").textContent=floor(state.clean); document.querySelector("#total-notes").textContent=state.total; document.querySelector("#time-lived").textContent=`一緒に過ごした時間 ${floor((Date.now()-state.bornAt)/60000)}分`; document.querySelector("#last-note").textContent=latest ? `${latest.note} ♪` : "まだ食べていないよ"; document.querySelector("#last-source").textContent=latest ? `${latest.source}から見つけた音` : "音をひとつ選んでね"; const max=maxValue(state.notes); state.notes.slice(0,7).forEach((count,index)=>{ document.querySelector(`[data-count="${index}"]`).textContent=count; document.querySelector(`[data-bar="${index}"]`).style.width=`${max?count/max*100:0}%`; }); }
function maxValue(values) { return max(1,...values); }
function drawParticles() { textAlign(CENTER,CENTER); textStyle(BOLD); for (const p of particles) { fill(p.color); textSize(p.label === "♪" ? 20 : 14); text(p.label,p.x,p.y); } textStyle(NORMAL); }
function setupMic() { mic = new p5.AudioIn(); fft = new p5.FFT(.85,1024); mic.start(()=>{ micOn=true; document.querySelector("#mic-button").textContent="聞いているよ… クリックで食べる"; document.querySelector("#mic-button").classList.add("is-on"); showToast("声や音をきかせてね"); },()=>showToast("マイクを使えないので音符で遊べるよ")); fft.setInput(mic); }
function analyzeMic() { if (!micOn) return; const level=mic.getLevel(); if (level<.035) { showToast("もう少し大きな音をきかせてね"); return; } const centroid=fft.getCentroid(); let index=0; if (centroid>80) { let best=Infinity; FREQUENCIES.slice(0,7).forEach((frequency,i)=>{ const difference=abs(centroid-frequency); if(difference<best){best=difference;index=i;} }); } else index=floor(random(7)); feedNote(index,"マイク"); }
function showToast(message) { const toast=document.querySelector("#toast"); toast.textContent=message; toast.classList.remove("show"); void toast.offsetWidth; toast.classList.add("show"); clearTimeout(toastTimer); toastTimer=setTimeout(()=>toast.classList.remove("show"),1100); }
function setupDOM() { document.querySelector("#mic-button").addEventListener("click",()=>{ ensureAudio(); if(!micOn) setupMic(); else analyzeMic(); }); document.querySelector("#record-button").addEventListener("click",openRecord); document.querySelector("#close-record").addEventListener("click",closeRecord); document.querySelector("#record-modal").addEventListener("click",(event)=>{if(event.target.id === "record-modal") closeRecord();}); if(state.total) document.querySelector("#welcome").textContent="おかえり！"; }
function openRecord() { document.querySelector("#record-modal").hidden=false; const favorite=state.notes.indexOf(max(...state.notes)); document.querySelector("#record-total").textContent=state.total; document.querySelector("#record-favorite").textContent=state.total?NOTE_NAMES[favorite]:"-"; document.querySelector("#record-mic").textContent=state.micTotal; document.querySelector("#record-manual").textContent=state.manualTotal; document.querySelector("#record-stage").textContent=`成長段階：${STAGES[getStage()]}`; document.querySelector("#record-born").textContent=`誕生：${new Date(state.bornAt).toLocaleDateString("ja-JP")} ／ 一緒に過ごした時間 ${floor((Date.now()-state.bornAt)/60000)}分`; document.querySelector("#record-bars").innerHTML=state.notes.slice(0,7).map((count,index)=>`<div class="record-bar"><b>${NOTE_NAMES[index]}</b><i style="width:${state.total?count/state.total*100:0}%;background:${NOTE_COLORS[index]}"></i><span>${state.total?floor(count/state.total*100):0}%</span></div>`).join(""); }
function closeRecord() { document.querySelector("#record-modal").hidden=true; }
function createMessage() { const options = [{ text:"ドがたべたい！", note:0 }, { text:"レの音がきになる", note:1 }, { text:"ミがたべたい！", note:2 }, { text:"おそとの音がたべたい", note:null }, { text:"ひまだなあ…", note:null }, { text:"いっしょにあそぼ", note:null }]; message = random(options); }
function playWithMarpan() { ensureAudio(); state.mood=min(100,state.mood+5); playPulse=-12; marpan.bounce(1); tone(523.25,.08,.08); burstSparkles(width*.5,height*.5); if (message && message.note === null) { state.mood=min(100,state.mood+12); message=null; showToast("いっしょにあそべた！"); } syncUI(); }
function burstSparkles(x,y) { for(let i=0;i<14;i++) particles.push({x,y,vx:random(-4,4),vy:random(-5,1),life:35+random(20),color:random(NOTE_COLORS),label:"✦"}); }
function mousePressed() { if (mouseY>height*.9) return false; for (let index=rests.length-1;index>=0;index--){ if(dist(mouseX,mouseY,rests[index].x,rests[index].y)<42){ const rest=rests.splice(index,1)[0]; state.clean=min(100,state.clean+7); ensureAudio(); tone(784,.08,.08); burstSparkles(rest.x,rest.y); showToast("休符を掃除したよ"); syncUI(); return false;} } playWithMarpan(); return false; }
function touchStarted() { return false; } function windowResized() { resizeCanvas(900,width<760?650:610); }
