"use strict";
const canvas=document.getElementById("stressCanvas"),ctx=canvas.getContext("2d"),hint=document.getElementById("hint");
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
let W=0,H=0,dpr=1,last=performance.now(),mode="none",load=0,targetLoad=0,broken=false,crack=0,crackStep=0,flash=0,shake=0,overloadSince=0;
let language="ja";try{language=localStorage.getItem("marpan-stress-language")==="en"?"en":"ja"}catch(_){ }
const TEXT={ja:{hint:"左右のグリップを引く",compare:"同じ力で引いて比べる",cut:"小さな傷。もう一度引っ張る",broken:"破断",stress:"応力の色",pull:"引張操作",shapes:"切れ込み形状",names:["傷なし","丸い穴","丸い切り欠き","鋭いV字"],canvas:"左右のグリップを引いて、マーパン素材の応力集中を観察する作品",switchLanguage:"Switch to English"},en:{hint:"Pull both grips",compare:"Pull with the same force to compare",cut:"A tiny cut. Pull again",broken:"FRACTURE",stress:"Stress colors",pull:"Pull controls",shapes:"Notch shape",names:["No damage","Round hole","Rounded notch","Sharp V-notch"],canvas:"Pull the grips and observe stress concentration inside the Marpan material",switchLanguage:"日本語に切り替え"}};
const t=key=>TEXT[language][key];
let activeGrip=null,dragStart=0,dragLoad=0,holdLeft=false,holdRight=false,audio=null,nextBlink=performance.now()+2500;
const colors=[[38,113,205],[42,181,131],[241,211,55],[244,125,38],[255,41,35],[255,255,245]];
function stressColor(v){v=clamp(v,0,1);const p=v*(colors.length-1),i=Math.min(colors.length-2,p|0),t=p-i;return `rgb(${lerp(colors[i][0],colors[i+1][0],t)|0},${lerp(colors[i][1],colors[i+1][1],t)|0},${lerp(colors[i][2],colors[i+1][2],t)|0})`}
function layout(){const mobile=W<700;const maxW=Math.min(W*(mobile?.72:.67),900),baseH=Math.min(H*(mobile?.25:.29),245);return{cx:W/2,cy:H*(mobile?.42:.47),baseW:maxW,baseH,stretch:load*Math.min(W*.12,130),gripW:mobile?29:36}}
function sheetPath(g,part="whole"){const w=g.baseW+g.stretch*2,h=g.baseH*(1-load*.16),x=g.cx-w/2,y=g.cy-h/2,r=Math.min(35,h*.19),n=notchGeometry(g),split=n?.x??g.cx,sep=broken?Math.min(w*.035,(performance.now()-crackStep)*.018):0;ctx.beginPath();if(part==="left")ctx.roundRect(x-sep,y,Math.max(1,split-x),h,[r,0,0,r]);else if(part==="right")ctx.roundRect(split+sep,y,Math.max(1,x+w-split),h,[0,r,r,0]);else ctx.roundRect(x,y,w,h,r);return{x,y,w,h,r}}
function notchGeometry(g){const box={x:g.cx-(g.baseW+g.stretch*2)/2,y:g.cy-g.baseH*(1-load*.16)/2,w:g.baseW+g.stretch*2,h:g.baseH*(1-load*.16)},nx=box.x+box.w*.29;if(mode==="hole")return{x:nx,y:g.cy,r:box.h*.105};if(mode==="round")return{x:nx,y:box.y,r:box.h*.105,tipX:nx,tipY:box.y+box.h*.105};if(mode==="v")return{x:nx,y:box.y,depth:box.h*.065,tipX:nx,tipY:box.y+box.h*(.065+crack)};return null}
function localStress(px,py,g){const n=notchGeometry(g),base=.06+load*.52;if(!n)return base+Math.sin(px*.025)*.012;if(mode==="hole"){const dx=Math.abs(px-n.x),dy=py-n.y,d=Math.hypot(dx,dy),ring=Math.exp(-Math.pow((d-n.r)/(n.r*.52),2)),sides=Math.pow(Math.abs(dx)/(d+.1),3);return base+load*.28*ring*(.25+.75*sides)}const d=Math.hypot(px-n.tipX,py-n.tipY);const radius=mode==="round"?n.r*.82:Math.max(5,g.baseH*.025);const focus=Math.exp(-d*d/(2*radius*radius));return base+load*(mode==="round"?.46:1.05+crack*1.3)*focus}
function drawField(g,part="whole"){const b=sheetPath(g,part);ctx.save();ctx.clip();const cell=W<700?7:9;for(let y=b.y-5;y<b.y+b.h+5;y+=cell)for(let x=b.x-5;x<b.x+b.w+5;x+=cell){ctx.fillStyle=stressColor(localStress(x+cell/2,y+cell/2,g));ctx.fillRect(x,y,cell+1,cell+1)}ctx.restore();ctx.strokeStyle="#20352e";ctx.lineWidth=Math.max(2.5,g.baseW*.004);sheetPath(g,part);ctx.stroke()}
function cutOut(g){const n=notchGeometry(g);if(!n||broken)return;ctx.save();sheetPath(g);ctx.clip();ctx.fillStyle="#eeeadd";ctx.strokeStyle="#20352e";ctx.lineWidth=2.4;if(mode==="hole"){ctx.beginPath();ctx.arc(n.x,n.y,n.r,0,Math.PI*2);ctx.fill();ctx.stroke()}else if(mode==="round"){ctx.beginPath();ctx.arc(n.x,n.y,n.r,0,Math.PI*2);ctx.fill();ctx.stroke()}else{const mouth=n.depth*.95;ctx.beginPath();ctx.moveTo(n.x-mouth,n.y-3);ctx.lineTo(n.tipX,n.tipY);ctx.lineTo(n.x+mouth,n.y-3);ctx.fill();ctx.stroke();drawCrack(n,g)}ctx.restore()}
function drawCrack(n,g){if(crack<=.002)return;const len=g.baseH*crack,segments=Math.max(2,Math.ceil(len/11));ctx.strokeStyle="#1a211e";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(n.x,n.y+n.depth);for(let i=1;i<=segments;i++){const x=n.x+Math.sin(i*5.31)*Math.min(3,1+i*.25),y=n.y+n.depth+len*i/segments;ctx.lineTo(x,y)}ctx.stroke()}
function drawEyes(g){if(broken)return;const h=g.baseH*(1-load*.16),eyeW=clamp(g.baseW*.075,34,66),eyeH=eyeW*1.08,blink=performance.now()>nextBlink&&performance.now()<nextBlink+170;if(performance.now()>nextBlink+170)nextBlink=performance.now()+2200+Math.random()*2200;for(let i=-1;i<=1;i++){const x=g.cx+i*eyeW*1.55,y=g.cy,eh=blink?3:eyeH;ctx.fillStyle="#fff";ctx.strokeStyle="#121212";ctx.lineWidth=2.5;ctx.beginPath();ctx.ellipse(x,y,eyeW/2,eh/2,0,0,Math.PI*2);ctx.fill();ctx.stroke();if(!blink){ctx.fillStyle="#121212";ctx.beginPath();ctx.arc(x+load*3,y,eyeW*.17,0,Math.PI*2);ctx.fill()}}}
function drawGrips(g){const w=g.baseW+g.stretch*2,h=g.baseH*(1-load*.16),x1=g.cx-w/2,x2=g.cx+w/2;for(const [side,x] of [["left",x1],["right",x2]]){ctx.save();ctx.translate(x, g.cy);ctx.fillStyle=activeGrip===side?"#26352e":"#657970";ctx.strokeStyle="#26352e";ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(side==="left"?-g.gripW:0,-h*.34,g.gripW,h*.68,7);ctx.fill();for(let j=-1;j<=1;j++){ctx.strokeStyle="#eeeadd88";ctx.beginPath();ctx.moveTo(side==="left"?-g.gripW+7:7,j*h*.15);ctx.lineTo(side==="left"?-7:g.gripW-7,j*h*.15);ctx.stroke()}ctx.restore()}return{x1,x2,h}}
function render(){const g=layout();ctx.clearRect(0,0,W,H);ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);if(broken){drawField(g,"left");drawField(g,"right")}else drawField(g);cutOut(g);drawEyes(g);drawGrips(g);if(flash>0){const n=notchGeometry(g),fx=n?.tipX??g.cx,fy=n?.tipY??g.cy;if(!broken||flash>.15){const grad=ctx.createRadialGradient(fx,fy,0,fx,fy,g.baseH*.14);grad.addColorStop(0,`rgba(255,255,255,${flash})`);grad.addColorStop(1,"rgba(255,40,25,0)");ctx.fillStyle=grad;ctx.beginPath();ctx.arc(fx,fy,g.baseH*.14,0,Math.PI*2);ctx.fill()}}ctx.restore()}
function breakMaterial(now){broken=true;crackStep=now;flash=1;shake=9;targetLoad=Math.max(targetLoad,.75);hint.textContent=t("broken");hint.classList.remove("hidden");crackSound(1)}
function tick(now){const dt=Math.min(.035,(now-last)/1000);last=now;if(holdLeft||holdRight)targetLoad=clamp(targetLoad+dt*.34,0,1);if(!activeGrip&&!holdLeft&&!holdRight)targetLoad=Math.max(0,targetLoad-dt*.035);load+=(targetLoad-load)*Math.min(1,dt*8);flash=Math.max(0,flash-dt*2.8);shake*=.86;if(!broken&&mode==="none"){if(load>.985){if(!overloadSince)overloadSince=now;if(now-overloadSince>850)breakMaterial(now)}else overloadSince=0}if(!broken&&mode==="v"&&load>.54){const threshold=.62-crack*.38;if(load>threshold&&now-crackStep>Math.max(85,360-crack*330)){const jump=crack<.19?.04:crack<.5?.09:.16;crack+=jump;crackStep=now;flash=1;shake=crack*7;crackSound(crack);if(crack>=.92)breakMaterial(now)}}render();requestAnimationFrame(tick)}
function crackSound(amount){try{audio??=new AudioContext();const o=audio.createOscillator(),gain=audio.createGain();o.type="square";o.frequency.setValueAtTime(900+amount*1250,audio.currentTime);o.frequency.exponentialRampToValueAtTime(160,audio.currentTime+.055);gain.gain.setValueAtTime(.035+amount*.05,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.07);o.connect(gain).connect(audio.destination);o.start();o.stop(audio.currentTime+.075)}catch(_){}}
function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
canvas.addEventListener("pointerdown",e=>{const p=point(e),g=layout(),gr=drawGrips(g),nearY=Math.abs(p.y-g.cy)<gr.h*.48;if(nearY&&Math.abs(p.x-gr.x1)<55)activeGrip="left";else if(nearY&&Math.abs(p.x-gr.x2)<55)activeGrip="right";else{const box=sheetPath(g);if(p.x>box.x&&p.x<box.x+box.w&&Math.abs(p.y-box.y)<35){selectMode("v");hint.textContent=t("cut");hint.classList.remove("hidden")}return}canvas.setPointerCapture(e.pointerId);dragStart=p.x;dragLoad=targetLoad;hint.classList.add("hidden")});
canvas.addEventListener("pointermove",e=>{if(!activeGrip)return;const dx=point(e).x-dragStart,target=activeGrip==="left"?-dx:dx;targetLoad=clamp(dragLoad+target/Math.min(W*.3,300),0,1)});
canvas.addEventListener("pointerup",()=>activeGrip=null);canvas.addEventListener("pointercancel",()=>activeGrip=null);
function resetState(){load=targetLoad=crack=flash=shake=overloadSince=0;broken=false;crackStep=performance.now();hint.textContent=mode==="none"?t("hint"):t("compare");hint.classList.remove("hidden")}
function selectMode(next){mode=next;document.querySelectorAll("[data-shape]").forEach(b=>b.classList.toggle("active",b.dataset.shape===mode));resetState()}
document.querySelectorAll("[data-shape]").forEach(b=>b.onclick=()=>selectMode(b.dataset.shape));document.getElementById("reset").onclick=resetState;
function updateLanguage(){document.documentElement.lang=language;document.getElementById("languageButton").textContent=language==="ja"?"EN":"日本語";document.getElementById("languageButton").setAttribute("aria-label",t("switchLanguage"));document.getElementById("legend").setAttribute("aria-label",t("stress"));document.getElementById("pullButtons").setAttribute("aria-label",t("pull"));document.getElementById("specimens").setAttribute("aria-label",t("shapes"));canvas.setAttribute("aria-label",t("canvas"));document.querySelectorAll("[data-shape] span").forEach((s,i)=>s.textContent=t("names")[i]);if(!broken)hint.textContent=mode==="none"?t("hint"):t("compare");else hint.textContent=t("broken")}
document.getElementById("languageButton").onclick=()=>{language=language==="ja"?"en":"ja";try{localStorage.setItem("marpan-stress-language",language)}catch(_){ }updateLanguage()};
for(const [id,key] of [["pullLeft","left"],["pullRight","right"]]){const b=document.getElementById(id),set=v=>{if(key==="left")holdLeft=v;else holdRight=v;if(v)hint.classList.add("hidden")};b.addEventListener("pointerdown",e=>{e.preventDefault();b.setPointerCapture(e.pointerId);set(true)});b.addEventListener("pointerup",()=>set(false));b.addEventListener("pointercancel",()=>set(false))}
function resize(){W=innerWidth;H=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener("resize",resize);resize();updateLanguage();requestAnimationFrame(tick);
