const NOTE_NAMES = ["ド", "レ", "ミ", "ファ", "ソ", "ラ", "シ", "ド"]; const FREQUENCIES = [261.63, 293.66, 329.63, 349.23, 392, 440, 493.88, 523.25];
const NOTE_COLORS = ["#e87567", "#e6a24e", "#d5bd4b", "#77b66e", "#55a5a8", "#6f91c1", "#9c7ac0"]; const STAGES = ["微生物世界", "水中世界", "草むら", "動物世界", "人間世界", "街", "巨大生物", "山", "惑星", "宇宙"]; const SAVE_KEY = "eating-notes-save-v1";
let marpan, state, particles = [], rests = [], feed = null, mic, fft, micOn = false, micListening = false, lastMicNoteAt = 0, audioReady = false, lastSave = 0, toastTimer, previousStage = 0, lastMoodTick = 0, nextMessageAt = 0, message = null, nextBgmAt = 0, bgmIndex = 0, playPulse = 0, language = "ja";
const TWINKLE = [0, 0, 4, 4, 5, 5, 4, 3, 3, 2, 2, 1, 1, 0];
function defaultState() { return { bornAt: Date.now(), lastPlayedAt: Date.now(), growth: 0, total: 0, micTotal: 0, manualTotal: 0, notes: [0,0,0,0,0,0,0], hunger: 42, mood: 72, clean: 100, history: [] }; }
function setup() { createCanvas(900, 610).parent("canvas-wrap"); pixelDensity(1); textFont('"Avenir Next", "Yu Gothic", sans-serif'); state = loadState(); previousStage = getStage(); lastMoodTick = Date.now(); nextMessageAt = millis() + random(9000, 16000); marpan = new Marpan25D({ maxSize: 410, bodyColor: "#f9fff6" }); marpan.enableAutoBlink(2300, 4300); makeNoteButtons(); makeLegend(); setupDOM(); syncUI(); }
function loadState() { try { const saved = JSON.parse(localStorage.getItem(SAVE_KEY)); return saved ? { ...defaultState(), ...saved } : defaultState(); } catch (error) { return defaultState(); } }
function saveState() { state.lastPlayedAt = Date.now(); localStorage.setItem(SAVE_KEY, JSON.stringify(state)); lastSave = millis(); }
function draw() { updateGame(); drawWorld(); drawParticles(); if (micListening) analyzeMicContinuously(); if (millis() - lastSave > 3000) saveState(); }
function updateGame() { for (const item of particles) { item.x += item.vx; item.y += item.vy; item.vy += .04; item.life--; } particles = particles.filter((item) => item.life > 0); if (feed) { feed.progress += .035; feed.x = lerp(feed.startX, width * .5, min(1, feed.progress)); feed.y = lerp(feed.startY, height * .52, min(1, feed.progress)) - sin(min(1, feed.progress) * PI) * 65; if (feed.progress >= 1) finishFeed(); } if (Date.now() - lastMoodTick > 12000) { state.mood = max(0, state.mood - 1); state.hunger = max(0, state.hunger - 1); lastMoodTick = Date.now(); syncUI(); } if (millis() > nextMessageAt && !message && !feed) { createMessage(); nextMessageAt = millis() + random(16000, 28000); } if (audioReady && millis() > nextBgmAt) playBgmNote(); if (frameCount % 720 === 0 && state.total > 0) { rests.push({ x:random(width*.18, width*.82), y:random(height*.16, height*.78), wobble:random(TWO_PI), spin:random(-.02,.02) }); state.clean = max(0, state.clean - 3); syncUI(); } }
function drawWorld() { const stage = getStage(); const scale = min(1.8, 1 + state.growth / 120); const pulse = sin(frameCount * .06) * (state.mood < 30 ? .8 : 2) + playPulse; if (stage > previousStage) { showToast("世界が小さくなった！"); previousStage = stage; } drawHabitat(stage); drawComparison(stage, scale); const bodyW = min(width * .48, 320 + scale * 20); const bodyH = bodyW * .68; const cx = width*.5; const cy = height*.53 + pulse; const bodyColor = mixedColor(); marpan.setPosition(cx, cy); marpan.lookAt(mouseX, mouseY); marpan.setBodyColor(bodyColor); marpan.setExpression(feed ? "happy" : state.mood < 30 ? "worried" : "pupil"); marpan.drawAt(cx, cy, { bodyWidth:bodyW, bodyHeight:bodyH, scaleX:1 + (feed ? sin(frameCount*.35)*.05 : 0), scaleY:1 - (feed ? abs(sin(frameCount*.35))*.04 : 0) }); drawFeed(); drawRests(); drawMessage(); drawStageLabel(stage, scale); playPulse *= .86; }
function drawHabitat(stage) { background(stageBackground(stage)); drawStars(stage); noStroke(); fill(stage === 1 ? "#9dd5d0" : "#c9e7d9"); ellipse(width*.5,height*.53,width*.9,height*.66); stroke("#8ebeb4"); strokeWeight(3); noFill(); rect(10,10,width-20,height-20,18); noStroke(); if (stage === 1) drawWaterLife(); }
function stageBackground(stage) { return ["#dff0ea","#cde9e7","#e6efd2","#f4eacb","#efe4d5","#e5ddd2","#d9dce7","#cbd5dd","#cbd9eb","#1e3346"][stage]; }
function drawStars(stage) { noStroke(); for (let i=0;i<18;i++) { const x=(i*83+frameCount*(stage>7?.05:.18))%width; const y=32+(i*47)%height; fill(stage>8?"#f6e8a9":stage>4?"#c2b39e":"#a9d8c9"); ellipse(x,y,stage>8?3:5,stage>8?3:5); } }
function drawComparison(stage, scale) { if (stage === 1) return; push(); const drift=sin(frameCount*.012)*4; if(stage===0) drawCells(drift); if(stage===2) drawMeadow(drift); if(stage===3) drawAnimals(drift); if(stage===4) drawHumanWorld(drift); if(stage===5) drawCity(drift,false); if(stage===6) drawCity(drift,true); if(stage===7) drawMountains(drift); if(stage===8) drawPlanetWorld(drift); if(stage===9) drawSpaceWorld(drift); pop(); }
function drawCells(drift) { noStroke(); [[150,170,34],[745,225,22],[120,430,18],[760,440,30]].forEach(([x,y,s],i)=>{fill(i%2?"#8fc9bd":"#a9d7c2");ellipse(x,y+drift,s,s*.8);fill("#6eaaa0");ellipse(x+3,y+drift,s*.28,s*.28);}); }
function drawMeadow(drift) { noStroke(); for(let i=0;i<17;i++){const x=35+i*53,h=30+(i%4)*12;fill(i%2?"#73a963":"#8abd72");triangle(x,height*.82,x+10,height*.82-h,x+18,height*.82);} fill("#8d8072");ellipse(105,440,72,39);ellipse(775,405,54,31);drawButterfly(145,185+drift,.8);drawButterfly(760,245-drift,.65); }
function drawButterfly(x,y,s){push();translate(x,y);scale(s);noStroke();fill("#e89a75");ellipse(-13,0,24,31);ellipse(13,0,24,31);fill("#655b58");ellipse(0,2,7,30);stroke("#655b58");strokeWeight(2);line(-2,-11,-9,-22);line(2,-11,9,-22);pop();}
function drawAnimals(drift) { drawBird(135,180+drift,.8);drawCat(760,390-drift*.3,.85);drawFish(125,420,.7); }
function drawBird(x,y,s){push();translate(x,y);scale(s);noStroke();fill("#e8a66e");ellipse(0,0,58,39);triangle(-27,0,-52,-17,-45,13);fill("#f5c95f");triangle(28,-2,47,5,28,10);fill("#fff");ellipse(14,-9,10);fill("#263c40");ellipse(16,-9,4);pop();}
function drawCat(x,y,s){push();translate(x,y);scale(s);noStroke();fill("#9a8b80");ellipse(0,18,65,75);ellipse(0,-24,55,49);triangle(-25,-40,-16,-69,-4,-44);triangle(25,-40,16,-69,4,-44);fill("#f5d7a2");ellipse(-11,-25,8);ellipse(11,-25,8);stroke("#6f625a");strokeWeight(4);noFill();arc(30,20,55,70,-HALF_PI,HALF_PI);pop();}
function drawHumanWorld(drift){drawPerson(130,350,1);drawBicycle(760,405,.75);drawChair(735,180+drift,.8);}
function drawPerson(x,y,s){push();translate(x,y);scale(s);stroke("#6b7772");strokeWeight(9);strokeCap(ROUND);fill("#e2aa78");ellipse(0,-65,35);line(0,-45,0,25);line(0,-15,-35,5);line(0,-15,35,5);line(0,25,-25,70);line(0,25,25,70);pop();}
function drawBicycle(x,y,s){push();translate(x,y);scale(s);stroke("#628984");strokeWeight(6);noFill();ellipse(-45,20,62);ellipse(48,20,62);line(-45,20,-8,-28);line(-8,-28,18,20);line(18,20,-45,20);line(18,20,43,-35);line(31,-35,57,-35);line(-19,-29,1,-29);pop();}
function drawChair(x,y,s){push();translate(x,y);scale(s);stroke("#96745f");strokeWeight(10);strokeCap(ROUND);line(-25,-45,-25,28);line(-25,5,32,5);line(30,5,30,55);line(-20,28,-20,55);pop();}
function drawCity(drift,giant){noStroke();const base=height*.81,factor=giant?1.45:1;[[45,92,120],[155,72,180],[700,85,150],[805,52,105]].forEach(([x,w,h],i)=>{fill(i%2?"#8fa5a6":"#a7b5ad");rect(x,base-h*factor,w,h*factor,5);fill("#f1d583");for(let yy=base-h*factor+20;yy<base-18;yy+=28)for(let xx=x+14;xx<x+w-10;xx+=25)rect(xx,yy,9,12,2);});drawCar(120,base-12,giant?.65:.8);drawLamp(780,base,giant?1.2:1);}
function drawCar(x,y,s){push();translate(x,y);scale(s);noStroke();fill("#dd806e");rect(-52,-37,104,35,11);quad(-31,-37,-12,-61,27,-61,43,-37);fill("#364b50");ellipse(-31,0,25);ellipse(31,0,25);pop();}
function drawLamp(x,y,s){push();translate(x,y);scale(s);stroke("#596b6b");strokeWeight(7);line(0,0,0,-150);line(0,-150,-28,-150);noStroke();fill("#f2d477");ellipse(-32,-145,31,22);pop();}
function drawMountains(drift){noStroke();fill("#91a99d");triangle(10,height*.8,235,130+drift,430,height*.8);fill("#e8eee4");triangle(165,230+drift,235,130+drift,300,230+drift);fill("#7f9a91");triangle(480,height*.8,700,175-drift,900,height*.8);fill("#eef2e9");triangle(630,270-drift,700,175-drift,770,275-drift);fill(255,255,255,180);ellipse(135,150,100,35);ellipse(720,115,130,38);drawBird(800,210+drift,.55);}
function drawPlanetWorld(drift){noStroke();fill("#e8d69c");ellipse(125,175+drift,88);fill("#85aaa7");ellipse(760,390-drift,120);fill("#c3e0d4");arc(760,390-drift,115,115,.2,2.2);stroke("#9e89b3");strokeWeight(9);noFill();ellipse(760,390-drift,185,48);fill("#cabbd8");noStroke();ellipse(620,165,24);}
function drawSpaceWorld(drift){noStroke();for(let i=0;i<25;i++){fill(i%3?"#f5e7ac":"#c8dbea");ellipse((i*97)%width,45+(i*71)%520,3+i%3);}fill("#d99077");ellipse(130,180+drift,105);fill("#7d9fc6");ellipse(760,390-drift,145);stroke("#e9c891");strokeWeight(12);noFill();ellipse(760,390-drift,220,62);noStroke();fill(255,240,190,80);ellipse(450,120,180,55);ellipse(450,120,70,140);}
function drawWaterLife() { noStroke(); fill("#bce9e4"); for (let i=0;i<12;i++) ellipse((i*97+frameCount*.22)%width, 40+(i*53)%height, 7+i%3*3, 7+i%3*3); stroke("#579d98"); strokeWeight(4); for (let i=0;i<6;i++) { const x=55+i*155; line(x,height*.82,x+sin(frameCount*.025+i)*12,height*.45); line(x+12,height*.82,x+22+sin(frameCount*.025+i)*10,height*.57); } noStroke(); for (let i=0;i<3;i++) drawFish(100+i*330,height*(.27+.18*(i%2)),1+i*.15); }
function drawFish(x,y,fishScale) { push(); translate(x+sin(frameCount*.012+x)*18,y); scale(fishScale); fill("#5a9ea5"); ellipse(0,0,58,30); triangle(-25,0,-48,-18,-48,18); fill("#f7f3df"); ellipse(17,-5,7,7); fill("#20343a"); ellipse(18,-5,3,3); pop(); }
function drawStageLabel(stage, scale) { noStroke(); fill(stage>8?"#f5e9c4":"#547871"); textAlign(LEFT,TOP); textSize(12); text(language === "ja" ? `世界 ${stage+1} / 10  ・  成長 ${floor(state.growth)}%` : `WORLD ${stage+1} / 10  ·  GROWTH ${floor(state.growth)}%`,18,16); }
function drawFeed() { if (!feed) return; push(); translate(feed.x, feed.y); rotate(sin(frameCount*.12)*.15); noStroke(); fill(NOTE_COLORS[feed.index]); ellipse(0,0,38,38); fill("#fffdf6"); textAlign(CENTER,CENTER); textStyle(BOLD); textSize(22); text("♪",0,-1); pop(); }
function drawRests() { textAlign(CENTER,CENTER); textSize(164); rests.forEach((rest)=>{ push(); translate(rest.x,rest.y+sin(frameCount*.04+rest.wobble)*9); rotate(frameCount*rest.spin); stroke("#f8f1d9"); strokeWeight(9); fill("#416f69"); text("𝄽",0,0); pop(); }); }
function drawMessage() { if (!message) return; const bubbleX=width*.68,bubbleY=height*.18; push(); stroke("#6e9c90"); strokeWeight(2); fill("#fffdf4"); rect(bubbleX-125,bubbleY-28,250,56,12); noStroke(); triangle(bubbleX-15,bubbleY+28,bubbleX+4,bubbleY+28,bubbleX-10,bubbleY+43); fill("#355e59"); textAlign(CENTER,CENTER); textSize(15); text(message.text,bubbleX,bubbleY); pop(); }
function mixedColor() { let total = state.notes.reduce((sum,value)=>sum+value,0); if (!total) return "#f9fff6"; let red=0,green=0,blue=0; state.notes.forEach((count,index)=>{ const color = colorFromHex(NOTE_COLORS[index]); red += color[0]*count; green += color[1]*count; blue += color[2]*count; }); const tint=.3, base=[249,255,246]; return `rgb(${floor(lerp(base[0],red/total,tint))},${floor(lerp(base[1],green/total,tint))},${floor(lerp(base[2],blue/total,tint))})`; }
function colorFromHex(hex) { return [parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)]; }
function feedNote(index, source="手動") { ensureAudio(); const pitch = FREQUENCIES[index]; tone(pitch,.18,.28); pressKey(index); if (feed) return; if (state.hunger >= 100) { playPulse=-7; marpan.bounce(.55); showToast(language === "ja" ? "おなかいっぱい。でも演奏できるよ♪" : "Full—but you can still play ♪"); return; } state.notes[index % 7]++; state.total++; source === "マイク" ? state.micTotal++ : state.manualTotal++; state.hunger = min(100,state.hunger+4); state.mood = min(100,state.mood+3); if (message && message.note === index % 7) { state.mood = min(100,state.mood+15); playPulse = -16; burstSparkles(width*.5,height*.5); showToast(language === "ja" ? "それ！うれしい！" : "That's it! So happy!"); message = null; } state.growth += .9; state.history.push({ note:NOTE_NAMES[index % 7], pitch, volume:source === "マイク" ? .6 : .4, duration:.28, source, at:Date.now() }); state.history = state.history.slice(-120); feed = { index:index%7, label:NOTE_NAMES[index], source, progress:0, startX:width*.5, startY:height*.96 }; for (let i=0;i<10;i++) particles.push({x:feed.startX+random(-25,25),y:feed.startY, vx:random(-2,2),vy:random(-4,-1),life:45+random(25),color:NOTE_COLORS[index%7],label:i%2?"♪":NOTE_NAMES[index]}); syncUI(); }
function pressKey(index) { const key=document.querySelectorAll(".note-button")[index]; if (!key) return; key.classList.add("is-pressed"); setTimeout(()=>key.classList.remove("is-pressed"),140); }
function finishFeed() { const label = feed.label; feed = null; marpan.bounce(1); showToast(language === "ja" ? `${label}をみつけた！` : `Found ${["C","D","E","F","G","A","B"][NOTE_NAMES.indexOf(label)]}!`); saveState(); }
function ensureAudio() { if (audioReady) return; userStartAudio(); audioReady = true; nextBgmAt = millis() + 500; }
function tone(frequency, volume, duration) { if (!audioReady) return; const oscillator = new p5.Oscillator("sine"); oscillator.freq(frequency); oscillator.amp(volume); oscillator.start(); oscillator.stop(duration); }
function playBgmNote() { const cleanFactor = state.clean / 100; nextBgmAt = millis() + 520; if (random() > cleanFactor) { bgmIndex = (bgmIndex + 1) % TWINKLE.length; return; } tone(FREQUENCIES[TWINKLE[bgmIndex]], .035 * cleanFactor, .22); bgmIndex = (bgmIndex + 1) % TWINKLE.length; }
function getStage() { return min(STAGES.length-1, floor(state.growth / 12)); }
function makeNoteButtons() { const container=document.querySelector("#note-buttons"); NOTE_NAMES.forEach((name,index)=>{ const button=document.createElement("button"); button.type="button"; button.className="note-button"; button.textContent=name; button.setAttribute("aria-label",`${name}の鍵盤`); button.style.setProperty("--note-color",NOTE_COLORS[index%7]); button.addEventListener("click",()=>feedNote(index)); container.append(button); }); }
function makeLegend() { const container=document.querySelector("#note-legend"); NOTE_NAMES.slice(0,7).forEach((name,index)=>{ const row=document.createElement("div"); row.className="legend-row"; row.innerHTML=`<i class="legend-dot" style="background:${NOTE_COLORS[index]}"></i><span>${name}</span><div class="legend-track"><i data-bar="${index}" style="width:0;background:${NOTE_COLORS[index]}"></i></div><b data-count="${index}">0</b>`; container.append(row); }); }
function syncUI() { const stage=getStage(); const latest=state.history[state.history.length-1], enStages=["Micro world","Underwater","Meadow","Animal world","Human world","City","Giant life","Mountain","Planet","Space"]; document.querySelector("#stage-label").textContent=language === "ja" ? STAGES[stage] : enStages[stage]; document.querySelector("#hunger").textContent=floor(state.hunger); document.querySelector("#mood").textContent=floor(state.mood); document.querySelector("#clean").textContent=floor(state.clean); document.querySelector("#total-notes").textContent=state.total; document.querySelector("#time-lived").textContent=language === "ja" ? `一緒に過ごした時間 ${floor((Date.now()-state.bornAt)/60000)}分` : `Time together: ${floor((Date.now()-state.bornAt)/60000)} min`; document.querySelector("#last-note").textContent=latest ? `${language === "ja" ? latest.note : ["C","D","E","F","G","A","B"][NOTE_NAMES.indexOf(latest.note)]} ♪` : (language === "ja" ? "まだ食べていないよ" : "Nothing eaten yet"); document.querySelector("#last-source").textContent=latest ? (language === "ja" ? `${latest.source}から見つけた音` : `Found via ${latest.source === "マイク" ? "microphone" : "piano"}`) : (language === "ja" ? "音をひとつ選んでね" : "Choose a note"); const max=maxValue(state.notes); state.notes.slice(0,7).forEach((count,index)=>{ document.querySelector(`[data-count="${index}"]`).textContent=count; document.querySelector(`[data-bar="${index}"]`).style.width=`${max?count/max*100:0}%`; }); }
function maxValue(values) { return max(1,...values); }
function drawParticles() { textAlign(CENTER,CENTER); textStyle(BOLD); for (const p of particles) { fill(p.color); textSize(p.label === "♪" ? 20 : 14); text(p.label,p.x,p.y); } textStyle(NORMAL); }
function setupMic() { mic = new p5.AudioIn(); fft = new p5.FFT(.72,2048); mic.start(()=>{ micOn=true; micListening=true; document.querySelector("#mic-button").classList.add("is-on"); updateMicLabel(); showToast(language === "ja" ? "聞こえた音を自動で食べるよ" : "Listening and catching notes"); },()=>showToast(language === "ja" ? "マイクを使えないので鍵盤で遊べるよ" : "Microphone unavailable—use the piano")); fft.setInput(mic); }
function toggleMic() { ensureAudio(); if (!micOn) return setupMic(); micListening=!micListening; document.querySelector("#mic-button").classList.toggle("is-on",micListening); updateMicLabel(); }
function updateMicLabel() { document.querySelector("#mic-label").textContent = micListening ? (language === "ja" ? "聞いています（停止）" : "Listening (stop)") : (language === "ja" ? "マイクから音をあげる" : "Feed from microphone"); }
function analyzeMicContinuously() { if (!micOn || !micListening || feed || millis()-lastMicNoteAt<850 || mic.getLevel()<.045) return; const spectrum=fft.analyze(); const nyquist=getAudioContext().sampleRate/2; let peak=0, peakFrequency=0; for(let i=ceil(180/nyquist*spectrum.length);i<=floor(560/nyquist*spectrum.length);i++){ if(spectrum[i]>peak){peak=spectrum[i];peakFrequency=i*nyquist/spectrum.length;} } if(peak<65) return; let index=0,best=Infinity; FREQUENCIES.forEach((frequency,i)=>{const difference=abs(frequency-peakFrequency);if(difference<best){best=difference;index=i;}}); lastMicNoteAt=millis(); feedNote(index,"マイク"); }
function showToast(message) { const toast=document.querySelector("#toast"); toast.textContent=message; toast.classList.remove("show"); void toast.offsetWidth; toast.classList.add("show"); clearTimeout(toastTimer); toastTimer=setTimeout(()=>toast.classList.remove("show"),1100); }
function setupDOM() { document.querySelector("#mic-button").addEventListener("click",toggleMic); document.querySelector("#language-button").addEventListener("click",toggleLanguage); document.querySelector("#record-button").addEventListener("click",openRecord); document.querySelector("#close-record").addEventListener("click",closeRecord); document.querySelector("#record-modal").addEventListener("click",(event)=>{if(event.target.id === "record-modal") closeRecord();}); if(state.total) document.querySelector("#welcome").textContent="おかえり！"; }
const EN_TEXT = {"音を食べて育つ、マーパンの記録":"A life with Marpan, who grows by eating sound","はじめまして":"Nice to meet you","おかえり！":"Welcome back!","きろく":"Record","おなか":"FULLNESS","ごきげん":"MOOD","きれいさ":"CLEAN","鍵盤を弾くと音が生まれます。マーパンをタップすると一緒に遊べます。":"Play the piano to make sound. Tap Marpan to play together.","いまの音":"Latest sound","まだ食べていないよ":"Nothing eaten yet","音をひとつ選んでね":"Choose a note","食べた音の色":"Colors of eaten sounds","音を食べたよ":"notes eaten","一緒に過ごした時間 0分":"Time together: 0 min","音のきろく":"Sound record","食べた音":"Notes eaten","いちばん好きな音":"Favorite note","マイクから":"From mic","手動から":"From piano"};
let translatableNodes=[];
function toggleLanguage() { language=language === "ja" ? "en" : "ja"; document.documentElement.lang=language; document.querySelector("#language-button").textContent=language === "ja" ? "EN" : "日本語"; if(!translatableNodes.length){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){const original=node.nodeValue.trim();if(EN_TEXT[original])translatableNodes.push({node,original});}} translatableNodes.forEach(({node,original})=>node.nodeValue=node.nodeValue.replace(language === "en" ? original : EN_TEXT[original],language === "en" ? EN_TEXT[original] : original)); document.querySelectorAll(".note-button").forEach((button,index)=>button.textContent=language === "ja" ? NOTE_NAMES[index] : ["C","D","E","F","G","A","B","C"][index]); document.querySelectorAll(".legend-row span").forEach((label,index)=>label.textContent=language === "ja" ? NOTE_NAMES[index] : ["C","D","E","F","G","A","B"][index]); updateMicLabel(); syncUI(); }
window.addEventListener("keydown",event=>{const index=["a","s","d","f","g","h","j","k"].indexOf(event.key.toLowerCase());if(index>=0&&!event.repeat){event.preventDefault();feedNote(index);}});
function openRecord() { document.querySelector("#record-modal").hidden=false; const favorite=state.notes.indexOf(max(...state.notes)), enNotes=["C","D","E","F","G","A","B"], enStages=["Micro world","Underwater","Meadow","Animal world","Human world","City","Giant life","Mountain","Planet","Space"]; document.querySelector("#record-total").textContent=state.total; document.querySelector("#record-favorite").textContent=state.total?(language === "ja" ? NOTE_NAMES[favorite] : enNotes[favorite]):"-"; document.querySelector("#record-mic").textContent=state.micTotal; document.querySelector("#record-manual").textContent=state.manualTotal; document.querySelector("#record-stage").textContent=language === "ja" ? `成長段階：${STAGES[getStage()]}` : `Growth stage: ${enStages[getStage()]}`; document.querySelector("#record-born").textContent=language === "ja" ? `誕生：${new Date(state.bornAt).toLocaleDateString("ja-JP")} ／ 一緒に過ごした時間 ${floor((Date.now()-state.bornAt)/60000)}分` : `Born: ${new Date(state.bornAt).toLocaleDateString("en-US")} · Time together: ${floor((Date.now()-state.bornAt)/60000)} min`; document.querySelector("#record-bars").innerHTML=state.notes.slice(0,7).map((count,index)=>`<div class="record-bar"><b>${language === "ja" ? NOTE_NAMES[index] : enNotes[index]}</b><i style="width:${state.total?count/state.total*100:0}%;background:${NOTE_COLORS[index]}"></i><span>${state.total?floor(count/state.total*100):0}%</span></div>`).join(""); }
function closeRecord() { document.querySelector("#record-modal").hidden=true; }
function createMessage() { const options = language === "ja" ? [{ text:"ドがたべたい！", note:0 }, { text:"レの音がきになる", note:1 }, { text:"ミがたべたい！", note:2 }, { text:"おそとの音がたべたい", note:null }, { text:"ひまだなあ…", note:null }, { text:"いっしょにあそぼ", note:null }] : [{text:"I want a C!",note:0},{text:"I'm curious about D",note:1},{text:"I want an E!",note:2},{text:"I want an outside sound",note:null},{text:"I'm a little bored…",note:null},{text:"Let's play!",note:null}]; message = random(options); }
function playWithMarpan() { ensureAudio(); state.mood=min(100,state.mood+5); playPulse=-12; marpan.bounce(1); tone(523.25,.08,.08); burstSparkles(width*.5,height*.5); if (message && message.note === null) { state.mood=min(100,state.mood+12); message=null; showToast("いっしょにあそべた！"); } syncUI(); }
function burstSparkles(x,y) { for(let i=0;i<14;i++) particles.push({x,y,vx:random(-4,4),vy:random(-5,1),life:35+random(20),color:random(NOTE_COLORS),label:"✦"}); }
function mousePressed() { if (mouseY>height*.9) return false; for (let index=rests.length-1;index>=0;index--){ if(dist(mouseX,mouseY,rests[index].x,rests[index].y)<105){ const rest=rests.splice(index,1)[0]; state.clean=min(100,state.clean+7); ensureAudio(); tone(784,.08,.08); burstSparkles(rest.x,rest.y); showToast(language === "ja" ? "休符を掃除したよ" : "Rest cleaned!"); syncUI(); return false;} } playWithMarpan(); return false; }
function touchStarted() { return false; } function windowResized() { resizeCanvas(900,width<760?650:610); }
