"use strict";

const CONFIG = Object.freeze({
  startingNotes:120, spinCost:10, bodyReward:1, keyReward:1,
  reelSpeed:0.0065, slipMs:440, feverSpins:10,
  rewards:{seven:300,replay:0,note:65,star:35,cherry:12,watermelon:22},
  score:{spin:20,seven:1800,replay:0,note:300,star:180,cherry:60,watermelon:100},
  feverRewardMultiplier:2, feverScoreMultiplier:2,
  skins:[
    {id:"cream",name:"クリーム",color:"#fff5df",cost:0},
    {id:"red",name:"あか",color:"#f28a83",cost:80},
    {id:"blue",name:"あお",color:"#84bde8",cost:100},
    {id:"yellow",name:"きいろ",color:"#f2d66f",cost:120}
  ],
  strips:[
    ["7","♪","🍒","★","Replay","🍉","♪","★","7","🍒","♪","🍉"],
    ["♪","7","★","🍉","Replay","🍒","♪","7","★","🍉","♪","🍒"],
    ["★","♪","7","🍒","Replay","♪","🍉","★","7","♪","🍒","🍉"]
  ],
  feverStrips:[
    ["7","♪","★","7","♪","🍒","★","7","♪"],
    ["7","♪","★","7","♪","🍉","★","7","♪"],
    ["7","♪","★","7","♪","Replay","★","7","♪"]
  ]
});

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={notes:CONFIG.startingNotes,score:0,sevens:0,bestFever:0,high:0,fever:0,feverRun:0,spinning:false,freeSpin:false,sound:true,debug:false,skin:"cream",skinsOwned:["cream"],reels:[],lastFrame:0,reach:false};
const dom={stage:$("#stage"),notes:$("#notes"),score:$("#score"),sevens:$("#sevens"),best:$("#bestFever"),high:$("#highScore"),message:$("#message"),lever:$("#lever"),eyes:$$(".eye"),particles:$("#particles"),badge:$("#feverBadge"),feverLeft:$("#feverLeft"),sound:$("#soundButton"),debugPanel:$("#debugPanel"),debugReadout:$("#debugReadout")};
let audio=null,marpan=null,canvasW=0,canvasH=0;

class MusicBox{
  constructor(){this.ctx=null;this.master=null;this.timer=null;this.step=0}
  wake(){if(!this.ctx){this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=.18;this.master.connect(this.ctx.destination);this.loop()}if(this.ctx.state==="suspended")this.ctx.resume()}
  tone(freq,dur=.12,type="sine",vol=.16,when=0){if(!state.sound||!this.ctx)return;const t=this.ctx.currentTime+when,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.001,t+dur);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+dur)}
  noise(dur=.08,vol=.09){if(!state.sound||!this.ctx)return;const n=this.ctx.sampleRate*dur,b=this.ctx.createBuffer(1,n,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);const s=this.ctx.createBufferSource(),g=this.ctx.createGain();s.buffer=b;g.gain.value=vol;s.connect(g);g.connect(this.master);s.start()}
  click(){this.tone(660,.05,"triangle",.12);this.tone(990,.06,"sine",.07,.03)}
  lever(){this.tone(150,.08,"square",.13);this.noise(.09,.11);this.tone(82,.18,"sine",.18,.08)}
  stop(){this.tone(105,.09,"square",.15);this.noise(.07,.13);this.tone(58,.14,"sine",.15,.04)}
  win(kind){const notes=kind==="seven"?[523,659,784,1047]:kind==="replay"?[784,659,784]:[523,659,784];notes.forEach((n,i)=>this.tone(n,.24,"triangle",.15,i*.09))}
  loop(){clearInterval(this.timer);this.timer=setInterval(()=>{if(!state.sound||!this.ctx)return;const fever=state.fever>0,seq=fever?[262,330,392,523,440,523,659,784]:[262,330,392,330,294,349,440,349];this.tone(seq[this.step++%seq.length],fever?.13:.18,"triangle",fever?.07:.045)},state.fever>0?150:280)}
}
audio=new MusicBox();

function setup(){const wrap=$("#canvasWrap");canvasW=wrap.clientWidth;canvasH=wrap.clientHeight;const c=createCanvas(canvasW,canvasH);c.parent("canvasWrap");pixelDensity(Math.min(devicePixelRatio,2));marpan=new Marpan25D({id:"marpan-slot-42",bodyColor:"#fff5d9",autoBlink:false});marpan.setExpression("flat");initGame()}
function windowResized(){const wrap=$("#canvasWrap");canvasW=wrap.clientWidth;canvasH=wrap.clientHeight;resizeCanvas(canvasW,canvasH);positionEyes()}
function draw(){clear();const fever=state.fever>0,pulse=fever?(sin(millis()*.009)+1)*.12:0,skin=CONFIG.skins.find(item=>item.id===state.skin)??CONFIG.skins[0];marpan.setPosition(width*.49,height*(width<600?.57:.61));marpan.draw({bodyWidth:Math.min(width*(width<600?.85:.63),height*.7),bodyColor:skin.color,pulse});positionEyes();updateReels();drawAccents(fever)}
function drawAccents(fever){push();noFill();stroke(fever?color(255,216,91,90):color(142,119,210,45));strokeWeight(2);const cx=width*.49,cy=height*(width<600?.57:.61);for(let i=0;i<3;i++){const r=height*(.34+i*.055)+sin(millis()*.002+i)*8;arc(cx,cy,r*1.7,r,.1,PI-.1)}pop()}
function positionEyes(){if(!dom.eyes.length)return;const bodyW=Math.min(width*(width<600?.85:.63),height*.7),centerX=width*.49,centerY=height*(width<600?.57:.61),eyeW=Math.max(62,bodyW*.18),eyeH=eyeW*1.08;dom.eyes.forEach((el,i)=>{const x=centerX+(i-1)*bodyW*.205;el.style.left=`${x}px`;el.style.top=`${centerY}px`;el.style.width=`${eyeW}px`;el.style.height=`${eyeH}px`;el.style.transform="translate(-50%,-50%)"});const lever=dom.lever,bodyRight=centerX+bodyW*.47,leverX=Math.min(bodyRight-2,width-(width<600?88:105));lever.style.left=`${leverX}px`;lever.style.top=`${centerY-119}px`}

function initGame(){loadSave();state.reels=CONFIG.strips.map((strip,i)=>({strip,pos:i*2.6,stopped:true,stopAt:0,stopStart:0,symbol:"♪",accuracy:0,manualUntil:0}));state.reels.forEach((r,i)=>{r.symbol=r.strip[Math.round(r.pos)%r.strip.length];renderReel(i)});bind();renderShop();render();requestAnimationFrame(frame)}
function bind(){dom.lever.addEventListener("click",startSpin);dom.eyes.forEach((e,i)=>{e.addEventListener("pointerdown",ev=>{ev.preventDefault();ev.stopPropagation();stopReel(i)});e.addEventListener("wheel",ev=>adjustReelWithWheel(ev,i),{passive:false})});$("#bodyTap").addEventListener("click",gainBody);$$('.keyboard button').forEach(b=>b.addEventListener("click",()=>playKey(b)));dom.sound.addEventListener("click",()=>{state.sound=!state.sound;dom.sound.textContent=state.sound?"♪ ON":"♪ OFF";dom.sound.setAttribute("aria-pressed",String(state.sound));if(state.sound)audio.wake()});window.addEventListener("keydown",ev=>{if(ev.key.toLowerCase()==="d"&&!ev.repeat){ev.preventDefault();toggleDebug()}})}
function frame(t){state.lastFrame=t;requestAnimationFrame(frame)}
function startSpin(){audio.wake();if(state.spinning)return;if(!state.debug&&!state.freeSpin&&state.notes<CONFIG.spinCost){say("音符がたりないよ。マーパンか鍵盤をタップ！");audio.tone(120,.2,"sawtooth",.09);return}if(!state.debug&&!state.freeSpin)state.notes-=CONFIG.spinCost;else state.freeSpin=false;state.spinning=true;state.reach=false;dom.stage.classList.remove("reach");dom.lever.classList.add("pulled");setTimeout(()=>dom.lever.classList.remove("pulled"),260);audio.lever();if(state.fever>0)burst("★",12);const activeStrips=state.fever>0?CONFIG.feverStrips:CONFIG.strips;state.reels.forEach((r,i)=>{r.strip=activeStrips[i];r.stopped=false;r.stopStart=0;r.pos=(r.pos+i*.37)%r.strip.length;dom.eyes[i].className="eye spinning";dom.eyes[i].disabled=false});say(state.debug?"DEBUG：目のどこを押してもSTOP":"目をタップして とめよう！");render()}
function updateReels(){if(!state.spinning)return;const now=millis(),baseSpeed=CONFIG.reelSpeed,speed=state.debug?baseSpeed*.12:baseSpeed;state.reels.forEach((r,i)=>{if(r.stopped)return;if(r.stopStart){const p=Math.min(1,(now-r.stopStart)/CONFIG.slipMs),ease=1-Math.pow(1-p,3);r.pos=r.stopFrom+(r.stopAt-r.stopFrom)*ease;if(p>=1)finishStop(i)}else if(now>=r.manualUntil)r.pos=(r.pos+deltaTime*speed*(1+i*.035))%r.strip.length;renderReel(i)});updateDebugReadout()}
function adjustReelWithWheel(ev,i){if(!state.debug)return;ev.preventDefault();ev.stopPropagation();const r=state.reels[i];if(!state.spinning||r.stopped||r.stopStart)return;const direction=ev.deltaY>0?1:-1;r.pos=(r.pos+direction*.08+r.strip.length)%r.strip.length;r.manualUntil=millis()+900;renderReel(i);updateDebugReadout()}
function renderReel(i){const r=state.reels[i],win=dom.eyes[i].querySelector(".reel-window"),base=Math.floor(r.pos),fraction=r.pos-base;win.replaceChildren();for(let offset=-2;offset<=2;offset++){const absolute=base+offset,index=((absolute%r.strip.length)+r.strip.length)%r.strip.length,symbol=r.strip[index],item=document.createElement("i"),symbolClass=symbol==="7"?" is-seven":symbol==="★"?" is-star":symbol==="♪"?" is-note":symbol==="Replay"?" is-replay":symbol==="🍒"||symbol==="🍉"?" is-fruit":"";item.className="reel-symbol"+symbolClass;item.textContent=symbol;item.style.top=`${50+(fraction-offset)*52}%`;item.style.transform="translateY(-50%)";win.append(item)}}
function stopReel(i){audio.wake();const r=state.reels[i];if(!state.spinning||r.stopped||r.stopStart)return;const incoming=Math.ceil(r.pos+.04),distance=incoming-r.pos;r.accuracy=Math.max(0,1-Math.abs(distance-.28)*1.7);r.stopFrom=r.pos;r.stopAt=incoming;r.stopStart=millis();dom.eyes[i].classList.remove("spinning");dom.eyes[i].classList.add("stopping");if(navigator.vibrate)navigator.vibrate(28)}
function finishStop(i){const r=state.reels[i];r.pos=r.stopAt;r.stopped=true;r.stopStart=0;r.symbol=r.strip[((r.pos%r.strip.length)+r.strip.length)%r.strip.length];renderReel(i);const eye=dom.eyes[i];eye.classList.remove("stopping");eye.classList.add("hit");eye.disabled=true;if(navigator.vibrate)navigator.vibrate(18);audio.stop();setTimeout(()=>eye.classList.remove("hit"),310);checkReach();if(state.reels.every(x=>x.stopped))setTimeout(resolveSpin,state.reels.filter(x=>x.symbol==="7").length===3?520:260)}
function checkReach(){const stopped=state.reels.filter(r=>r.stopped),sevens=stopped.filter(r=>r.symbol==="7").length,open=state.reels.filter(r=>!r.stopped);if(sevens===2&&open.length===1){state.reach=true;dom.stage.classList.add("reach");dom.message.textContent="7・7・…… さいごの目をねらえ！";dom.eyes[state.reels.indexOf(open[0])].classList.add("reach-target");audio.tone(1047,.45,"sine",.14);if(audio.master)audio.master.gain.setTargetAtTime(.08,audio.ctx.currentTime,.08)}}
function resolveSpin(){state.spinning=false;state.reach=false;dom.stage.classList.remove("reach");dom.eyes.forEach(e=>e.classList.remove("reach-target"));if(audio.master)audio.master.gain.setTargetAtTime(.18,audio.ctx.currentTime,.1);const syms=state.reels.map(r=>r.symbol),same=syms.every(s=>s===syms[0]),kind=same?({"7":"seven","Replay":"replay","♪":"note","★":"star","🍒":"cherry","🍉":"watermelon"}[syms[0]]):syms.filter(s=>s==="🍒").length>=2?"cherry":syms.filter(s=>s==="🍉").length>=2?"watermelon":null;const timingBonus=Math.round(state.reels.reduce((a,r)=>a+r.accuracy,0)/3*100);let reward=kind?CONFIG.rewards[kind]:0,points=CONFIG.score.spin+(kind?CONFIG.score[kind]:0)+timingBonus;if(state.fever){reward*=CONFIG.feverRewardMultiplier;points*=CONFIG.feverScoreMultiplier;state.fever--;state.feverRun++;state.bestFever=Math.max(state.bestFever,state.feverRun);dom.feverLeft.textContent=state.fever;if(state.fever===0)endFever()}state.notes+=reward;if(reward>0)sendNotesToScore(reward);state.score+=Math.round(points);state.high=Math.max(state.high,state.score);if(kind){audio.win(kind);if(kind==="replay"){state.freeSpin=true;say("REPLAY！ つぎは無料でもう一回");burst("↻",12)}else if(kind==="seven")win777();else{say(`${label(kind)}！ ♪ +${reward}`);burst(kind==="note"?"♪":syms[0],Math.min(20,6+reward/5))}}else say("もう一回！");persistGame();render()}
function win777(){state.sevens++;say("7・7・7 ！！");dom.eyes.forEach(e=>e.classList.add("hit"));marpan.bounce(2);setTimeout(()=>{burst("♪",34);burst("★",20);state.fever=CONFIG.feverSpins;state.feverRun=0;dom.stage.classList.add("fever");dom.badge.hidden=false;dom.feverLeft.textContent=state.fever;say("FEVER！ 10スピンの音楽祭");audio.loop();persistGame();render()},650)}
function endFever(){dom.stage.classList.remove("fever");dom.badge.hidden=true;say("FEVER おしまい。また7をねらおう！");audio.tone(523,.35,"triangle",.12);audio.loop()}
function label(k){return{note:"おんぷぞろい",star:"ほしぞろい",cherry:"チェリー",watermelon:"スイカ"}[k]||k}
function gainBody(e){audio.wake();if(state.spinning)return;state.notes+=CONFIG.bodyReward;state.score+=1;marpan.bounce(.65);audio.click();sendNotesToScore(CONFIG.bodyReward,e.clientX,e.clientY);render()}
function playKey(b){audio.wake();const i=Number(b.dataset.note),freq=[261.63,293.66,329.63,349.23,392,440,493.88,523.25][i];state.notes+=CONFIG.keyReward;state.score+=2;audio.tone(freq,.35,"sine",.2);b.classList.add("playing");setTimeout(()=>b.classList.remove("playing"),120);const rect=b.getBoundingClientRect();sendNotesToScore(CONFIG.keyReward,rect.left+rect.width/2,rect.top);render()}
function sendNotesToScore(amount,startX=null,startY=null){const stage=dom.stage.getBoundingClientRect(),target=dom.notes.getBoundingClientRect(),sx=startX??stage.left+stage.width*.49,sy=startY??stage.top+stage.height*.62,tx=target.left+target.width*.45,ty=target.top+target.height*.5,count=Math.min(18,Math.max(1,Math.ceil(Math.sqrt(amount))));for(let i=0;i<count;i++){const note=document.createElement("i"),spread=(i-(count-1)/2)*8;note.className="score-note";note.textContent="♪";note.style.setProperty("--sx",`${sx+spread}px`);note.style.setProperty("--sy",`${sy+Math.random()*22-11}px`);note.style.setProperty("--mx",`${(sx+tx)/2+spread*2}px`);note.style.setProperty("--my",`${Math.min(sy,ty)-70-Math.random()*45}px`);note.style.setProperty("--tx",`${tx}px`);note.style.setProperty("--ty",`${ty}px`);note.style.setProperty("--delay",`${i*.035}s`);document.body.append(note);setTimeout(()=>note.remove(),1500)}setTimeout(()=>{dom.notes.parentElement.classList.remove("absorb");void dom.notes.parentElement.offsetWidth;dom.notes.parentElement.classList.add("absorb");audio.tone(1175,.08,"sine",.06)},Math.min(900,520+count*35))}
function renderShop(){const shop=$("#bodyShopItems");shop.replaceChildren(...CONFIG.skins.map(skin=>{const owned=state.skinsOwned.includes(skin.id),selected=state.skin===skin.id,button=document.createElement("button");button.type="button";button.className="skin-item"+(selected?" selected":"");button.style.setProperty("--skin",skin.color);button.innerHTML=`<span class="skin-swatch"></span><span class="skin-copy"><b>${skin.name}</b><small>${selected?"装着中":owned?"着せ替える":`♪ ${skin.cost}`}</small></span>`;button.disabled=selected;button.addEventListener("click",()=>buyOrWearSkin(skin));return button}))}
function buyOrWearSkin(skin){audio.wake();const owned=state.skinsOwned.includes(skin.id);if(!owned){if(state.notes<skin.cost){say(`${skin.name}には ♪${skin.cost} 必要です`);audio.tone(120,.2,"sawtooth",.09);return}state.notes-=skin.cost;state.skinsOwned.push(skin.id);burst("✦",10);audio.win("star")}state.skin=skin.id;marpan.bounce(.8);say(`${skin.name}ボディにアップデート！`);persistGame();renderShop();render()}
function burst(text,count,x=null,y=null){const box=dom.stage.getBoundingClientRect();for(let i=0;i<count;i++){const p=document.createElement("i");p.className="particle";p.textContent=text;p.style.left=`${x==null?box.width*(.35+Math.random()*.3):x-box.left}px`;p.style.top=`${y==null?box.height*(.55+Math.random()*.18):y-box.top}px`;p.style.color=["#ffd85b","#ff78a0","#79e8c7","#fff"][i%4];p.style.setProperty("--dx",`${(Math.random()-.5)*220}px`);p.style.setProperty("--rot",`${(Math.random()-.5)*100}deg`);p.style.animationDelay=`${Math.random()*.16}s`;dom.particles.append(p);setTimeout(()=>p.remove(),1400)}}
function say(s){dom.message.textContent=s}
function toggleDebug(){state.debug=!state.debug;dom.debugPanel.hidden=!state.debug;say(state.debug?"DEBUG MODE：超低速／目の上でホイール微調整":"デバッグモードを終了しました");updateDebugReadout();render()}
function updateDebugReadout(){if(!state.debug)return;dom.debugReadout.textContent=state.reels.map((r,i)=>`${i+1}: ${r.pos.toFixed(2)}  ${r.stopped?r.symbol:"RUN"}`).join("\n")}
function render(){dom.notes.textContent=`♪ ${Math.floor(state.notes).toLocaleString("ja-JP")}`;dom.score.textContent=Math.floor(state.score).toLocaleString("ja-JP");dom.sevens.textContent=state.sevens;dom.best.textContent=state.bestFever;dom.high.textContent=Math.floor(state.high).toLocaleString("ja-JP");dom.lever.disabled=state.spinning;dom.lever.querySelector("small").textContent=state.debug?"DEBUG FREE":state.freeSpin?"FREE":"♪ "+CONFIG.spinCost;dom.badge.hidden=state.fever<=0;updateDebugReadout()}
function persistGame(){try{localStorage.setItem("marpan-slot-42",JSON.stringify({notes:state.notes,score:state.score,sevens:state.sevens,bestFever:state.bestFever,high:state.high,skin:state.skin,skinsOwned:state.skinsOwned}))}catch{}}
function loadSave(){try{const d=JSON.parse(localStorage.getItem("marpan-slot-42"));if(d)Object.assign(state,d);if(!Array.isArray(state.skinsOwned))state.skinsOwned=["cream"]}catch{}}
